// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package amazonbedrockconnector.actions;

import static java.util.Objects.requireNonNull;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import amazonbedrockconnector.impl.AmazonBedrockClient;
import amazonbedrockconnector.impl.MxDataSource;
import amazonbedrockconnector.impl.MxLogger;
import amazonbedrockconnector.proxies.DeleteDataSourceResponse;
import amazonbedrockconnector.proxies.ENUM_DataSourceStatus;
import software.amazon.awssdk.services.bedrockagent.BedrockAgentClient;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;

public class DeleteDataSource extends UserAction<IMendixObject>
{
	/** @deprecated use Credentials.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __Credentials;
	private final awsauthentication.proxies.Credentials Credentials;
	private final awsauthentication.proxies.ENUM_Region Region;
	/** @deprecated use DeleteDataSourceRequest.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __DeleteDataSourceRequest;
	private final amazonbedrockconnector.proxies.DeleteDataSourceRequest DeleteDataSourceRequest;

	public DeleteDataSource(
		IContext context,
		IMendixObject _credentials,
		java.lang.String _region,
		IMendixObject _deleteDataSourceRequest
	)
	{
		super(context);
		this.__Credentials = _credentials;
		this.Credentials = _credentials == null ? null : awsauthentication.proxies.Credentials.initialize(getContext(), _credentials);
		this.Region = _region == null ? null : awsauthentication.proxies.ENUM_Region.valueOf(_region);
		this.__DeleteDataSourceRequest = _deleteDataSourceRequest;
		this.DeleteDataSourceRequest = _deleteDataSourceRequest == null ? null : amazonbedrockconnector.proxies.DeleteDataSourceRequest.initialize(getContext(), _deleteDataSourceRequest);
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		try {
			// Validating JA input parameters
			requireNonNull(Credentials, "AWS Credentials are required");
			requireNonNull(DeleteDataSourceRequest, "DeleteDataSourceRequest is required");
			requireNonNull(Region, "AWS Region is required");
			
			validateRequest();
						
			BedrockAgentClient client = AmazonBedrockClient.getBedrockAgentClient(Credentials, Region, DeleteDataSourceRequest);
			
			software.amazon.awssdk.services.bedrockagent.model.DeleteDataSourceRequest awsRequest = createAwsRequest();
			LOGGER.info("AWS request: " + awsRequest);
			
			software.amazon.awssdk.services.bedrockagent.model.DeleteDataSourceResponse awsResponse = client.deleteDataSource(awsRequest);
			LOGGER.info("AWS response: " + awsResponse);
			
			return getMxResponse(awsResponse).getMendixObject();
		
		} catch (Exception e) {
			LOGGER.error(e.getMessage());
			throw e;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "DeleteDataSource";
	}

	// BEGIN EXTRA CODE
	private static final MxLogger LOGGER = new MxLogger(DeleteDataSource.class);
	
	private void validateRequest() throws CoreException {
		
		if (this.DeleteDataSourceRequest.getKnowledgeBaseId() == null || this.DeleteDataSourceRequest.getKnowledgeBaseId().isBlank()) {
			throw new IllegalArgumentException("KnowledgeBaseId is required.");
		}
		if (this.DeleteDataSourceRequest.getDataSourceId() == null || this.DeleteDataSourceRequest.getDataSourceId().isBlank()) {
			throw new IllegalArgumentException("DataSourceId is required.");
		}
	}
	
	private software.amazon.awssdk.services.bedrockagent.model.DeleteDataSourceRequest createAwsRequest() throws CoreException{
			
			software.amazon.awssdk.services.bedrockagent.model.DeleteDataSourceRequest.Builder awsRequestBuilder = software.amazon.awssdk.services.bedrockagent.model.DeleteDataSourceRequest.builder();
			awsRequestBuilder.knowledgeBaseId(this.DeleteDataSourceRequest.getKnowledgeBaseId());
			awsRequestBuilder.dataSourceId(this.DeleteDataSourceRequest.getDataSourceId());
			return awsRequestBuilder.build();
		}
	
	private DeleteDataSourceResponse getMxResponse(software.amazon.awssdk.services.bedrockagent.model.DeleteDataSourceResponse awsResponse) {
		
		DeleteDataSourceResponse mxResponse = new DeleteDataSourceResponse(getContext());
		
		mxResponse.setDataSourceId(awsResponse.dataSourceId());
		mxResponse.setKnowledgeBaseId(awsResponse.knowledgeBaseId());
		mxResponse.setStatus(MxDataSource.getMxDataSourceStatus(awsResponse.status()));
		return mxResponse;
	}
	// END EXTRA CODE
}
