// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package amazonbedrockconnector.actions;

import static java.util.Objects.requireNonNull;
import java.util.List;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import amazonbedrockconnector.impl.AmazonBedrockClient;
import amazonbedrockconnector.impl.MxLogger;
import amazonbedrockconnector.proxies.ENUM_CustomizationType;
import amazonbedrockconnector.proxies.ENUM_InferenceType;
import amazonbedrockconnector.proxies.ENUM_InputOutputModality;
import amazonbedrockconnector.proxies.ENUM_ModelLifecycleStatus;
import amazonbedrockconnector.proxies.FoundationModelLifecycle;
import amazonbedrockconnector.proxies.FoundationModelSummary;
import amazonbedrockconnector.proxies.InputModality;
import amazonbedrockconnector.proxies.ListFoundationModelsResponse;
import amazonbedrockconnector.proxies.OutputModality;
import amazonbedrockconnector.proxies.SupportedCustomization;
import amazonbedrockconnector.proxies.SupportedInferenceType;
import software.amazon.awssdk.services.bedrock.BedrockClient;
import software.amazon.awssdk.services.bedrock.model.ModelCustomization;
import software.amazon.awssdk.services.bedrock.model.InferenceType;
import software.amazon.awssdk.services.bedrock.model.ModelModality;
import software.amazon.awssdk.services.bedrock.model.FoundationModelLifecycleStatus;
import com.mendix.systemwideinterfaces.core.UserAction;

public class ListFoundationModels extends UserAction<IMendixObject>
{
	/** @deprecated use Credentials.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __Credentials;
	private final awsauthentication.proxies.Credentials Credentials;
	private final awsauthentication.proxies.ENUM_Region Region;
	/** @deprecated use ListFoundationModelsRequest.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __ListFoundationModelsRequest;
	private final amazonbedrockconnector.proxies.ListFoundationModelsRequest ListFoundationModelsRequest;

	public ListFoundationModels(
		IContext context,
		IMendixObject _credentials,
		java.lang.String _region,
		IMendixObject _listFoundationModelsRequest
	)
	{
		super(context);
		this.__Credentials = _credentials;
		this.Credentials = _credentials == null ? null : awsauthentication.proxies.Credentials.initialize(getContext(), _credentials);
		this.Region = _region == null ? null : awsauthentication.proxies.ENUM_Region.valueOf(_region);
		this.__ListFoundationModelsRequest = _listFoundationModelsRequest;
		this.ListFoundationModelsRequest = _listFoundationModelsRequest == null ? null : amazonbedrockconnector.proxies.ListFoundationModelsRequest.initialize(getContext(), _listFoundationModelsRequest);
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		try {
			// Validating JA input parameters
			requireNonNull(Credentials, "AWS Credentials are required");
			requireNonNull(ListFoundationModelsRequest, "ListFoundationalModelsRequest is required");
			requireNonNull(Region, "AWS Region is required");
						
			BedrockClient client = AmazonBedrockClient.getBedrockClient(Credentials, Region, ListFoundationModelsRequest);
			
			software.amazon.awssdk.services.bedrock.model.ListFoundationModelsRequest awsRequest = createAwsRequest();
			LOGGER.info("AWS request: " + awsRequest);
			
			software.amazon.awssdk.services.bedrock.model.ListFoundationModelsResponse awsResponse = client.listFoundationModels(awsRequest);
			LOGGER.info("AWS response: " + awsResponse);
			
			return getMxResponse(awsResponse).getMendixObject();
		
		} catch (Exception e) {
			LOGGER.error(e.getMessage());
			throw e;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ListFoundationModels";
	}

	// BEGIN EXTRA CODE
	private static final MxLogger LOGGER = new MxLogger(ListFoundationModels.class);
	
	private software.amazon.awssdk.services.bedrock.model.ListFoundationModelsRequest createAwsRequest(){
		
		software.amazon.awssdk.services.bedrock.model.ListFoundationModelsRequest.Builder awsRequestBuilder = software.amazon.awssdk.services.bedrock.model.ListFoundationModelsRequest.builder();
		
		if (this.ListFoundationModelsRequest.getByCustomizationType() != null) {
			awsRequestBuilder.byCustomizationType(this.ListFoundationModelsRequest.getByCustomizationType().getCaption());
		}
		if (this.ListFoundationModelsRequest.getByInferenceType() != null) {
			awsRequestBuilder.byInferenceType(this.ListFoundationModelsRequest.getByInferenceType().name());
		}
		if (this.ListFoundationModelsRequest.getByOutputModality() != null) {
			awsRequestBuilder.byOutputModality(this.ListFoundationModelsRequest.getByOutputModality().getCaption());
		}
		if (this.ListFoundationModelsRequest.getByProvider() != null && !this.ListFoundationModelsRequest.getByProvider().isBlank()) {
			awsRequestBuilder.byProvider(this.ListFoundationModelsRequest.getByProvider());
		}	
		
		return awsRequestBuilder.build();
		
	}
	
	private ListFoundationModelsResponse getMxResponse(software.amazon.awssdk.services.bedrock.model.ListFoundationModelsResponse awsResponse) {
		
		ListFoundationModelsResponse mxResponse = new ListFoundationModelsResponse(getContext());
		
		List<software.amazon.awssdk.services.bedrock.model.FoundationModelSummary> awsFoundationalModelList = awsResponse.modelSummaries();
		
		for (software.amazon.awssdk.services.bedrock.model.FoundationModelSummary awsFoundationModel : awsFoundationalModelList) {
			FoundationModelSummary mxFoundationalModel = new FoundationModelSummary(getContext());
			mxFoundationalModel.setModelARN(awsFoundationModel.modelArn());
			mxFoundationalModel.setModelID(awsFoundationModel.modelId());
			awsFoundationModel.customizationsSupported().forEach(awsCustomizationsSupported -> createMxSupportedCustomizations(awsCustomizationsSupported,mxFoundationalModel));
			awsFoundationModel.inferenceTypesSupported().forEach(awsInferenceTypesSupported -> createMxSupportedInferenceType(awsInferenceTypesSupported,mxFoundationalModel));
			awsFoundationModel.inputModalities().forEach(awsInputModality -> createMxInputModality(awsInputModality,mxFoundationalModel));
			createMxModelLifecycle(awsFoundationModel.modelLifecycle(),mxFoundationalModel);
			mxFoundationalModel.setModelName(awsFoundationModel.modelName());
			awsFoundationModel.outputModalities().forEach(awsOutputModality -> createMxOutputModality(awsOutputModality,mxFoundationalModel));
			mxFoundationalModel.setProviderName(awsFoundationModel.providerName());
			if (awsFoundationModel.responseStreamingSupported() != null) {
				mxFoundationalModel.setResponseStreamingSupported(awsFoundationModel.responseStreamingSupported());
			} else {
				mxFoundationalModel.setResponseStreamingSupported(false);
			}
			mxFoundationalModel.setFoundationModelSummary_ListFoundationModelsResponse(mxResponse);
		}
		
		return mxResponse;
	}


	private static ENUM_CustomizationType getCustomizationType(ModelCustomization modelCustomization) throws java.lang.IllegalStateException {
			switch (modelCustomization){
			case CONTINUED_PRE_TRAINING:
			case FINE_TUNING:
				return ENUM_CustomizationType.valueOf(modelCustomization.name());
			default:
				LOGGER.debug("Unknown CustomizationType returned: ", modelCustomization.toString());
				return ENUM_CustomizationType.UNKNOWN_TO_SDK_VERSION;
			}
		}

	
	void createMxSupportedCustomizations(ModelCustomization awsCustomizationsSupported, FoundationModelSummary mxFoundationalModel) {
		
		SupportedCustomization mxSupportedCustomizations = new SupportedCustomization(getContext());		

		mxSupportedCustomizations.setCustomizationType(getCustomizationType(awsCustomizationsSupported));
		mxSupportedCustomizations.setSupportedCustomization_FoundationModelSummary(mxFoundationalModel);		
	}


	private static ENUM_InferenceType getInferenceType(InferenceType inferenceType) throws java.lang.IllegalStateException {
		switch(inferenceType){
			case ON_DEMAND:
			case PROVISIONED:
				return ENUM_InferenceType.valueOf(inferenceType.name());
			default: 
				LOGGER.debug("Unknown InferenceType returned: ", inferenceType.toString());
				return ENUM_InferenceType.UNKNOWN_TO_SDK_VERSION;
		}
	}

	
	void createMxSupportedInferenceType(InferenceType awsInferenceTypesSupported, FoundationModelSummary mxFoundationalModel) {
		
		SupportedInferenceType mxSupportedInferenceType = new SupportedInferenceType(getContext());

		mxSupportedInferenceType.setInferenceType(getInferenceType(awsInferenceTypesSupported));
		mxSupportedInferenceType.setSupportedInferenceType_FoundationModelSummary(mxFoundationalModel);		
	}


	private static ENUM_InputOutputModality getInputOutputModality(ModelModality modelModality) throws java.lang.IllegalStateException {
		switch(modelModality){
			case EMBEDDING:
			case IMAGE:
			case TEXT:
				return ENUM_InputOutputModality.valueOf(modelModality.name());
			default: 
				LOGGER.debug("Unknown InputOutputModality returned: ", modelModality.toString());
				return ENUM_InputOutputModality.UNKNOWN_TO_SDK_VERSION;
		}
	}

	
	void createMxInputModality(ModelModality awsInputModality, FoundationModelSummary mxFoundationalModel) {
		
		InputModality mxInputModality = new InputModality(getContext());
		mxInputModality.setInputModalityType(getInputOutputModality(awsInputModality));
		mxInputModality.setInputModality_FoundationModelSummary(mxFoundationalModel);		
	}

	
	void createMxOutputModality(ModelModality awsOutputModality, FoundationModelSummary mxFoundationalModel) {
		
		OutputModality mxOutputModality = new OutputModality(getContext());

		mxOutputModality.setOutputModalityType(getInputOutputModality(awsOutputModality));
		mxOutputModality.setOutputModality_FoundationModelSummary(mxFoundationalModel);
		
	}
	

	private static ENUM_ModelLifecycleStatus getLifecycleStatus(FoundationModelLifecycleStatus lifeCycleStatus) throws java.lang.IllegalStateException {
		switch(lifeCycleStatus){
			case ACTIVE:
			case LEGACY:
				return ENUM_ModelLifecycleStatus.valueOf(lifeCycleStatus.toString());
			default:
				LOGGER.debug("Unknown LifeCycleStatus returned: ", lifeCycleStatus.toString());
				return ENUM_ModelLifecycleStatus.UNKNOWN_TO_SDK_VERSION;
		}
	}

	void createMxModelLifecycle(software.amazon.awssdk.services.bedrock.model.FoundationModelLifecycle awsModelLifecycle, FoundationModelSummary mxFoundationalModel) {
		
		FoundationModelLifecycle mxFoundationModelLifecycle = new FoundationModelLifecycle(getContext());
		
		mxFoundationModelLifecycle.setStatus(getLifecycleStatus(awsModelLifecycle.status()));
		mxFoundationModelLifecycle.setFoundationModelLifecycle_FoundationModelSummary(mxFoundationalModel);
		
	}

	// END EXTRA CODE
}
