// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mxdock.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import mxdock.proxies.AdminOption;
import mxdock.proxies.AdminType;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * Local admin option:
 * Link to an admin page that is available in this app
 */
public class CreateLocalAdminOption extends CustomJavaAction<IMendixObject>
{
	private final java.lang.String label;
	private final java.lang.Long order;
	private final java.lang.String deeplinkURL;
	private final java.lang.String openPageMf;

	public CreateLocalAdminOption(
		IContext context,
		java.lang.String _label,
		java.lang.Long _order,
		java.lang.String _deeplinkURL,
		java.lang.String _openPageMf
	)
	{
		super(context);
		this.label = _label;
		this.order = _order;
		this.deeplinkURL = _deeplinkURL;
		this.openPageMf = _openPageMf;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		AdminOption adminOption = new AdminOption(getContext());
		adminOption.setadminType(AdminType.Local);
		adminOption.setlabel(this.label);
		adminOption.setorder(this.order.intValue());
		adminOption.seturl(this.deeplinkURL);
		adminOption.setmicroflow(this.openPageMf);
		return adminOption.getMendixObject();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "CreateLocalAdminOption";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
