// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mxdock.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

public class DecodeJwtTokenBody extends CustomJavaAction<java.lang.String>
{
	private java.lang.String token;

	public DecodeJwtTokenBody(IContext context, java.lang.String token)
	{
		super(context);
		this.token = token;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		java.util.Base64.Decoder decoder = java.util.Base64.getUrlDecoder();
		String[] split_string = this.token.split("\\.");
        // String base64EncodedHeader = split_string[0];
        String base64EncodedBody = split_string[1];
        // String base64EncodedSignature = split_string[2];
        
        String parsedBody = new String(decoder.decode(base64EncodedBody));

        return parsedBody;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "DecodeJwtTokenBody";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
