// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package conversationalui.actions;

import static java.util.Objects.requireNonNull;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import conversationalui.impl.MxLogger;
import conversationalui.impl.ProviderConfigImpl;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class ProviderConfig_ExecuteAction extends CustomJavaAction<java.lang.Boolean>
{
	/** @deprecated use ProviderConfig.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __ProviderConfig;
	private final conversationalui.proxies.ProviderConfig ProviderConfig;
	/** @deprecated use ChatContext.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __ChatContext;
	private final conversationalui.proxies.ChatContext ChatContext;

	public ProviderConfig_ExecuteAction(
		IContext context,
		IMendixObject _providerConfig,
		IMendixObject _chatContext
	)
	{
		super(context);
		this.__ProviderConfig = _providerConfig;
		this.ProviderConfig = _providerConfig == null ? null : conversationalui.proxies.ProviderConfig.initialize(getContext(), _providerConfig);
		this.__ChatContext = _chatContext;
		this.ChatContext = _chatContext == null ? null : conversationalui.proxies.ChatContext.initialize(getContext(), _chatContext);
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		try {
			requireNonNull(ProviderConfig, "ProviderConfig is required.");
			requireNonNull(ChatContext, "ChatContext is required.");
			ProviderConfigImpl.validate(ProviderConfig.getActionMicroflow());
			
			return Core.microflowCall(ProviderConfig.getActionMicroflow()).withParam("ChatContext", ChatContext.getMendixObject()).execute(this.getContext());
		
		} catch (Exception e) {
			LOGGER.error(e.getMessage());
			throw e;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ProviderConfig_ExecuteAction";
	}

	// BEGIN EXTRA CODE
	
	private static final MxLogger LOGGER = new MxLogger(ProviderConfig_ExecuteAction.class);
	
	// END EXTRA CODE
}
