// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package conversationalui.actions;

import java.util.stream.Collectors;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;
import conversationalui.impl.MxLogger;

public class TraceFiltering_GetUniqueConversationCount extends UserAction<java.lang.Long>
{
	/** @deprecated use com.mendix.utils.ListUtils.map(TraceList, com.mendix.systemwideinterfaces.core.IEntityProxy::getMendixObject) instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final java.util.List<IMendixObject> __TraceList;
	private final java.util.List<genaicommons.proxies.Trace> TraceList;

	public TraceFiltering_GetUniqueConversationCount(
		IContext context,
		java.util.List<IMendixObject> _traceList
	)
	{
		super(context);
		this.__TraceList = _traceList;
		this.TraceList = java.util.Optional.ofNullable(_traceList)
			.orElse(java.util.Collections.emptyList())
			.stream()
			.map(traceListElement -> genaicommons.proxies.Trace.initialize(getContext(), traceListElement))
			.collect(java.util.stream.Collectors.toList());
	}

	@java.lang.Override
	public java.lang.Long executeAction() throws Exception
	{
		// BEGIN USER CODE
		try {
			java.util.List<String> uniqueList = TraceList.stream()
				    .map(t -> t.get_ConversationId())
				    .distinct() // removes duplicates
				    .collect(Collectors.toList());
			
			int count = uniqueList.size();
			
			return (long) count;

		} catch (Exception e) {
		    LOGGER.error(e);
		    return null;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "TraceFiltering_GetUniqueConversationCount";
	}

	// BEGIN EXTRA CODE
	private static final MxLogger LOGGER = new MxLogger(TraceFiltering_GetUniqueConversationCount.class);
	// END EXTRA CODE
}
