// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package conversationalui.actions;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.util.stream.Collectors;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;
import conversationalui.impl.MxLogger;

public class TraceFiltering_CalculateDurationPercentile extends UserAction<java.math.BigDecimal>
{
	/** @deprecated use com.mendix.utils.ListUtils.map(TraceList, com.mendix.systemwideinterfaces.core.IEntityProxy::getMendixObject) instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final java.util.List<IMendixObject> __TraceList;
	private final java.util.List<genaicommons.proxies.Trace> TraceList;
	private final java.lang.Long Percentile;

	public TraceFiltering_CalculateDurationPercentile(
		IContext context,
		java.util.List<IMendixObject> _traceList,
		java.lang.Long _percentile
	)
	{
		super(context);
		this.__TraceList = _traceList;
		this.TraceList = java.util.Optional.ofNullable(_traceList)
			.orElse(java.util.Collections.emptyList())
			.stream()
			.map(traceListElement -> genaicommons.proxies.Trace.initialize(getContext(), traceListElement))
			.collect(java.util.stream.Collectors.toList());
		this.Percentile = _percentile;
	}

	@java.lang.Override
	public java.math.BigDecimal executeAction() throws Exception
	{
		// BEGIN USER CODE
		try {
			
			java.util.List<Integer> durations = TraceList.stream()
				    .map(t -> t.getDurationMilliseconds())
				    .sorted()
				    .collect(Collectors.toList());
			
			var calculatedDuration = calculateDuration(durations,this.Percentile);
			
			return calculatedDuration.setScale(1, RoundingMode.HALF_UP);
			

		} catch (Exception e) {
		    LOGGER.error(e);
		    return null;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "TraceFiltering_CalculateDurationPercentile";
	}

	// BEGIN EXTRA CODE
	private static final MxLogger LOGGER = new MxLogger(TraceFiltering_CalculateDurationPercentile.class);
	
	private BigDecimal calculateDuration(java.util.List<Integer> durations, java.lang.Long percentile) {
		
		int n = durations.size();
		
        if (n == 0) return BigDecimal.valueOf(0);

        double rank = (percentile / 100.0) * (n - 1);
        int lower = (int) Math.floor(rank);
        int upper = (int) Math.ceil(rank);

        if (lower == upper) {
            return BigDecimal.valueOf(durations.get(lower)/1000);
        } else {
            double weight = rank - lower;
            return BigDecimal.valueOf((durations.get(lower) * (1 - weight) + durations.get(upper) * weight)/1000);
        }
    }
	// END EXTRA CODE
}
