// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package agentcommons.actions;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.UserAction;
import com.mendix.systemwideinterfaces.core.meta.IMetaObject;
import agentcommons.impl.MxLogger;
import agentcommons.proxies.Entity;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * Returns an Entity object if it can be found in the metaobject list. Returns null, if no Entity with the specififed name exists.
 */
public class Entity_GetByName extends UserAction<IMendixObject>
{
	private final java.lang.String EntityName;

	public Entity_GetByName(
		IContext context,
		java.lang.String _entityName
	)
	{
		super(context);
		this.EntityName = _entityName;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		try {
			if(EntityName == null || EntityName.isBlank()) {
				return null;
			}
			
			for (IMetaObject metaObject : Core.getMetaObjects())
			    if (metaObject.getName().equals(EntityName)) {
			    	Entity entity = new Entity(getContext());
			    	entity.setName(EntityName);
			    	entity.setIsPersistable(metaObject.isPersistable());
			    	return entity.getMendixObject();
			    }
			return null;
		} catch (Exception e) {
			LOGGER.error(e);
			return null;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Entity_GetByName";
	}

	// BEGIN EXTRA CODE
	private static final MxLogger LOGGER = new MxLogger(Entity_GetByName.class);
	// END EXTRA CODE
}
