// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package agentcommons.actions;

import static java.util.Objects.requireNonNull;
import java.util.ArrayList;
import java.util.List;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IDataType;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;
import agentcommons.impl.MxLogger;
import agentcommons.proxies.Module;

/**
 * Returns a list of modules available in the current project.
 * Association MicroflowSelection_Module is set.
 */
public class Module_GetList extends UserAction<java.util.List<IMendixObject>>
{
	/** @deprecated use MicroflowSelection.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __MicroflowSelection;
	private final agentcommons.proxies.MicroflowSelection MicroflowSelection;

	public Module_GetList(
		IContext context,
		IMendixObject _microflowSelection
	)
	{
		super(context);
		this.__MicroflowSelection = _microflowSelection;
		this.MicroflowSelection = _microflowSelection == null ? null : agentcommons.proxies.MicroflowSelection.initialize(getContext(), _microflowSelection);
	}

	@java.lang.Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		// BEGIN USER CODE
		try {
			requireNonNull(MicroflowSelection, "MicroflowSelection is required.");
			
			Core.getMicroflowNames().stream()
				.filter(microflowName -> !microflowName.isBlank() && microflowName.contains("."))
				.filter(microflow -> Core.getReturnType(microflow).getType().equals(IDataType.DataTypeEnum.String))
				.sorted()
				.forEach(microflowName -> getCreateModule(microflowName.substring(0, microflowName.indexOf('.'))));
			
			MicroflowSelection.setMicroflowSelection_Module(uniqueModuleList);
			
			return uniqueModuleList.stream().map(e -> e.getMendixObject()).toList();
		} catch (Exception e) {
		    LOGGER.error(e);
		    return null;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Module_GetList";
	}

	// BEGIN EXTRA CODE
	private static final MxLogger LOGGER = new MxLogger(Module_GetList.class);
	
	private List<Module> uniqueModuleList = new ArrayList<Module>();

	private void getCreateModule(String moduleName) {
		Module moduleInList = uniqueModuleList.stream()
				.filter(o -> o.getModuleName().equals(moduleName))
				.findFirst()
				.orElse(null);
		
		if(moduleInList != null) {
			return;
		}
		
		Module module = new Module(getContext());
		module.setModuleName(moduleName);
		uniqueModuleList.add(module);
	}
	// END EXTRA CODE
}
