// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package agentcommons.actions;

import static java.util.Objects.requireNonNull;
import java.util.List;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IDataType;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;
import agentcommons.impl.MxLogger;
import agentcommons.proxies.Microflow;

/**
 * Gets a list of microflows available in the given module that have a string return type. Association MicroflowSelection_Microflow is set.
 */
public class Module_GetMicroflowList extends UserAction<java.util.List<IMendixObject>>
{
	/** @deprecated use MicroflowSelection.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __MicroflowSelection;
	private final agentcommons.proxies.MicroflowSelection MicroflowSelection;
	/** @deprecated use Module.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __Module;
	private final agentcommons.proxies.Module Module;

	public Module_GetMicroflowList(
		IContext context,
		IMendixObject _microflowSelection,
		IMendixObject _module
	)
	{
		super(context);
		this.__MicroflowSelection = _microflowSelection;
		this.MicroflowSelection = _microflowSelection == null ? null : agentcommons.proxies.MicroflowSelection.initialize(getContext(), _microflowSelection);
		this.__Module = _module;
		this.Module = _module == null ? null : agentcommons.proxies.Module.initialize(getContext(), _module);
	}

	@java.lang.Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		// BEGIN USER CODE
		try {
			requireNonNull(MicroflowSelection, "MicroflowSelection is required.");
			requireNonNull(Module, "Module is required.");
			
			List<Microflow> microflowList = Core.getMicroflowNames().stream()
				.filter(microflowName -> !microflowName.isBlank() && microflowName.contains("."))
				.filter(microflowName -> {
					if(Module.getModuleName() == null || Module.getModuleName().isBlank() ) {
						return false;
					} else {
						return microflowName.startsWith(Module.getModuleName());
					}
				})
				.filter(microflow -> Core.getReturnType(microflow).getType().equals(IDataType.DataTypeEnum.String))
				.sorted()
				.map(microflowName -> createMicroflow(microflowName))
				.toList();
			
			MicroflowSelection.setMicroflowSelection_Microflow(microflowList);
			
			return microflowList.stream().map(e -> e.getMendixObject()).toList();
		} catch (Exception e) {
		    LOGGER.error(e);
		    return null;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Module_GetMicroflowList";
	}

	// BEGIN EXTRA CODE
	private static final MxLogger LOGGER = new MxLogger(Module_GetMicroflowList.class);
	
	private Microflow createMicroflow(String fullName) {
		Microflow microflow = new Microflow(getContext());
		microflow.setFullName(fullName);
		microflow.setMicroflowName(fullName.substring(fullName.indexOf('.') + 1));
		return microflow;
	}
	// END EXTRA CODE
}
