// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package askmeanything.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.text.PDFTextStripper;
import java.io.InputStream;
import askmeanything.proxies.PDFContent;
import com.mendix.core.Core;

public class PDFContent_CreateFromFile extends CustomJavaAction<IMendixObject>
{
	/** @deprecated use Document.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __Document;
	private final system.proxies.FileDocument Document;

	public PDFContent_CreateFromFile(
		IContext context,
		IMendixObject _document
	)
	{
		super(context);
		this.__Document = _document;
		this.Document = _document == null ? null : system.proxies.FileDocument.initialize(getContext(), _document);
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		PDFContent pdfContent = new PDFContent(getContext());
		try(InputStream inputStream = Core.getFileDocumentContent(getContext(), Document.getMendixObject())){
			PDDocument pdfdocument = PDDocument.load(inputStream);
			PDFTextStripper pdfTextStripper = new PDFTextStripper();
			pdfContent.setContent(pdfTextStripper.getText(pdfdocument));
		}
		return pdfContent.getMendixObject();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "PDFContent_CreateFromFile";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
