// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package openaiconnector.actions;

import static java.util.Objects.requireNonNull;
import java.util.List;
import java.util.Map;
import java.util.HashMap;
import java.util.stream.Collectors;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IDataType;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.fasterxml.jackson.databind.node.ArrayNode;
import genaicommons.impl.MessageImpl;
import genaicommons.impl.FunctionImpl;
import genaicommons.impl.FunctionMappingImpl;
import genaicommons.proxies.Message;
import genaicommons.proxies.Request;
import genaicommons.proxies.Tool;
import genaicommons.proxies.ToolCall;
import genaicommons.proxies.ToolCollection;
import genaicommons.proxies.ArgumentInput;
import genaicommons.proxies.ENUM_MessageRole;
import openaiconnector.impl.MxLogger;
import openaiconnector.proxies.OpenAIRequest_Extension;
import openaiconnector.proxies.RequestMapping;

public class RequestMapping_ManipulateJson extends UserAction<java.lang.String>
{
	/** @deprecated use RequestMapping.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __RequestMapping;
	private final openaiconnector.proxies.RequestMapping RequestMapping;
	private final java.lang.String Request_Json;
	private final java.lang.String Architecture;

	public RequestMapping_ManipulateJson(
		IContext context,
		IMendixObject _requestMapping,
		java.lang.String _request_Json,
		java.lang.String _architecture
	)
	{
		super(context);
		this.__RequestMapping = _requestMapping;
		this.RequestMapping = _requestMapping == null ? null : openaiconnector.proxies.RequestMapping.initialize(getContext(), _requestMapping);
		this.Request_Json = _request_Json;
		this.Architecture = _architecture;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		try {
			requireNonNull(RequestMapping, "RequestMapping is required.");
			requireNonNull(Request_Json, "Request_JSON is required.");
			
			validateRequestMapping();

			rootNode = MAPPER.readTree(Request_Json);
            
            //find stop node and remove if array is empty
            removeEmptyArrayNode(rootNode, "stop");
            
			updateMessages(rootNode);
			setFunctionToolChoice(rootNode);
			mapFunctionParameters();

			return MAPPER.writeValueAsString(rootNode);
		} catch (Exception e) {
			throw e;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "RequestMapping_ManipulateJson";
	}

	// BEGIN EXTRA CODE
	private static final MxLogger LOGGER = new MxLogger(RequestMapping_ManipulateJson.class);
	private static final ObjectMapper MAPPER = new ObjectMapper();
	private JsonNode rootNode;
	
	private boolean validateRequestMapping() throws CoreException {
		Request request = getRequest(RequestMapping);
		requireNonNull(request, "RequestMapping is not associated to a Request");
		return request != null; 
		
	}
	
	private void updateMessages(JsonNode rootNode) throws Exception {
		//Get messages node
		JsonNode messagesNode = rootNode.path("messages");
		//Loop over all messages

		for (JsonNode messageNode : messagesNode) {
			//find tool_calls node and remove if array is empty
            removeEmptyArrayNode(messageNode, "tool_calls");
            
            //If a fileCollection has been added replace content node with array of text content and file content
            updateMessagesWithFiles(messageNode);
            
    		//Set Arguments in tool call messages
            JsonNode toolCalls = messageNode.path("tool_calls");
            if(toolCalls != null && !toolCalls.isEmpty()) {
            	setToolCallArguments(toolCalls);
            }
        }
		//Update messages within rootNode
		((ObjectNode) rootNode).set("messages", messagesNode);
	}

	private void removeEmptyArrayNode(JsonNode jsonNode, String path) {
		JsonNode arrayNode = jsonNode.path(path);
		if (arrayNode != null && arrayNode.isArray() && arrayNode.size() == 0) {
		    ((ObjectNode) jsonNode).remove(path);
		}
	}
	
	
	private void updateMessagesWithFiles(JsonNode messageNode) {
		JsonNode fileCollection = messageNode.path("filecollection");
		
		//Return if there no images will be sent
		if(fileCollection == null || fileCollection.size() == 0) {
			return;
		}
		ArrayNode content = MAPPER.createArrayNode();
			
		//set text content string as first element in array
		addTextContentNode(content, messageNode.path("content").asText());
		
		//add image content to array
		for (JsonNode file : fileCollection) {
			String filetype = file.path("filetype") != null ? file.path("filetype").asText() : null;
			LOGGER.debug("filetype ", filetype, " file ", file);
			if(filetype != null && filetype.equals("image")) {
				addImage(content, file);
			} else if (filetype != null && filetype.equals("document")) {
				addDocument(content, file);
			}
		}
			
		//Remove imageCollection helper structure
		((ObjectNode) messageNode).remove("filecollection");
		//Overwrite content node including images
		((ObjectNode) messageNode).set("content", content);
	}
	
	private void setToolCallArguments(JsonNode toolCallsArray) throws Exception {
		for (JsonNode toolCall : toolCallsArray) {
			JsonNode function = toolCall.path("function");
			JsonNode argumentsArray = function.path("arguments");
			Map<String, String> argumentsMap = new HashMap<>();
	        for (JsonNode argument : argumentsArray) {
	            String key = argument.get("key").asText();
	            String value = argument.get("value").asText();
	            argumentsMap.put(key, value);
	        }
	        String argumentsString = MAPPER.writeValueAsString(argumentsMap);
	       ((ObjectNode) function).put("arguments", argumentsString);
		}
	}

	private void addImage(ArrayNode content, JsonNode file) {
		ObjectNode imageURL = MAPPER.createObjectNode();
		if(file.path("textcontent") != null && !file.path("textcontent").asText().isBlank()) {
			addTextContentNode(content, file.path("textcontent").asText());
		}
		
		imageURL.put("url", file.path("filecontent").asText());
		
		if(file.path("detail") != null && !file.path("detail").asText().isBlank()) {
			imageURL.put("detail", file.path("detail").asText());
		}
		
		ObjectNode imageContent = MAPPER.createObjectNode();
		imageContent.put("type", "image_url");
		imageContent.set("image_url", imageURL);
		content.add(imageContent);
	}
	
	private void addDocument(ArrayNode content, JsonNode file) {
		ObjectNode document = MAPPER.createObjectNode();
		if(file.path("textcontent") != null && !file.path("textcontent").asText().isBlank()) {
			addTextContentNode(content, file.path("textcontent").asText());
		}
		document.put("file_data", file.path("filecontent").asText());
		document.put("filename", file.path("filename") != null ? file.path("filename").asText() : null);
		ObjectNode documentContent = MAPPER.createObjectNode();
		documentContent.put("type", "file");
		documentContent.set("file", document);
		LOGGER.debug("documentContent ", documentContent);
		content.add(documentContent);
	}

	private void addTextContentNode(ArrayNode content, String text) {
		ObjectNode textContent = MAPPER.createObjectNode();
		textContent.put("type", "text");
		textContent.put("text", text);
		content.add(textContent);
	}
	

	private void setFunctionToolChoice(JsonNode rootNode) throws CoreException {
		// ToolChoice is not function and thus empty, auto or none
		if (RequestMapping.getToolChoice() == null) {
			return;
		}
			
		switch (RequestMapping.getToolChoice()) {
        case tool:
        	setToolChoiceTool();
            break;
        case any: 			
        	setToolChoiceAny();					
			break;
        //auto and none work out of the box
        case auto:
        	break;
        case none:
        	break;
        default:
        	LOGGER.warn(("Unknown type for ToolChoice: " + RequestMapping.getToolChoice().toString()));
            break;
		}
		
	}
	
	//"any" choice can only be used once at the first iteration to prevent infinity loops
	private void setToolChoiceAny() throws CoreException {
		if(FunctionMappingImpl.getToolCallMessages(getRequest(RequestMapping),getContext()).size() == 0) {
			if (Architecture != null && Architecture.toLowerCase().contains("openai")) {
            ((ObjectNode) rootNode).put("tool_choice", "required");
			}
		}
    	else {
    		((ObjectNode) rootNode).remove("tool_choice");
    	}
	}
	
	
	private void setToolChoiceTool() throws CoreException {
		// Add ToolChoice Tool if it has not yet been called in a previous iteration
		if(getToolCollection(RequestMapping) != null) {
			Tool toolChoiceTool = getToolCollection(RequestMapping).getToolCollection_ToolChoice();
			
			// Remove tool choice function, because it has already been called
			// This prevents and infinite loop
			if (toolChoiceTool == null || isToolRecall(toolChoiceTool)) {
				LOGGER.debug("ToolChoice " + toolChoiceTool.getName() + " has already been called. Removing ToolChoice from Request.");
				((ObjectNode)rootNode).remove("tool_choice");
			
			} else {
				// Create a new tool_choice node
		        ObjectNode toolChoiceNode = createToolChoiceNode(toolChoiceTool);
		        LOGGER.debug("ToolChoice has not been called yet. Updating ToolChoice function placeholder with: " + toolChoiceNode);
		        
		        // Update the original JsonNode with the tool_choice object
		        ((ObjectNode) rootNode).set("tool_choice", toolChoiceNode);
			}
		}
	}
	
	private ToolCollection getToolCollection(RequestMapping requestMapping) throws CoreException {
		Request request = getRequest(requestMapping);
		if (request == null) {
			return null;
		}
		return request.getRequest_ToolCollection();
	}
	
	private Request getRequest(RequestMapping requestMapping) throws CoreException {
		if (requestMapping.getRequestMapping_OpenAIRequest_Extension() == null) {
			LOGGER.warn("RequestMapper is not associated to a OpenAI_Extension instance");
			return null;
		}
		OpenAIRequest_Extension openAIRequestExtension = requestMapping.getRequestMapping_OpenAIRequest_Extension();
		if (openAIRequestExtension.getOpenAIRequest_Extension_Request() == null) {
			LOGGER.warn("OpenAIRequest_Extension is not associated to a Request instance");
			return null;
		}
		return openAIRequestExtension.getOpenAIRequest_Extension_Request();
	}
	
	private ObjectNode createToolChoiceNode(Tool toolChoiceTool) {
		ObjectNode toolChoiceNode = MAPPER.createObjectNode();
        toolChoiceNode.put("type", toolChoiceTool.getToolType() != null ? toolChoiceTool.getToolType() : "function"); //currently only "function" is supported
        ObjectNode functionNode = MAPPER.createObjectNode();
        functionNode.put("name", toolChoiceTool.getName());
        toolChoiceNode.set("function", functionNode);
        return toolChoiceNode;
	}

	private boolean isToolRecall(Tool toolChoiceTool) throws CoreException {
		// Get all messages with role 'tool'
		List<Message> messageListTool = MessageImpl
				.retrieveMessageListByRole(getRequest(RequestMapping), ENUM_MessageRole.tool, getContext());

		// No tool calls yet; thus no tool recall
		if (messageListTool.size() == 0) {
			return false;
		}

		// Get all messages with role assistant
		// Assistant messages optionally have an array of tool_calls that contain an id and the functionName
		List<Message> messageListAssistant = MessageImpl
				.retrieveMessageListByRole(getRequest(RequestMapping), ENUM_MessageRole.assistant, getContext());

		// HashMap with ToolCall._id and ToolCallFunction.Name created from the messageListAssistant
		// The map contains only those tool calls, where functionName equals the toolChoiceFunctionName
		Map<String, String> toolChoiceToolCallMap = new HashMap<>();

		for (Message message : messageListAssistant) {

			// Get ToolCall list for each assistant message where the function name equals
			// the function name from the tool choice (toolChoiceFunctionName)
			List<ToolCall> toolCallList = Core.retrieveByPath(getContext(), message.getMendixObject(),
							Message.MemberNames.Message_ToolCall.toString())
					.stream()
					.filter(mxObject -> {
						return filterToolCallByFunctionName(toolChoiceTool.getName(), mxObject);
					})
					.map(mxObject -> ToolCall.initialize(getContext(), mxObject))
					.collect(Collectors.toList());

			// Loop over toolCallList and add _id and functionName to a HashMap
			for (ToolCall toolCall : toolCallList) {
				String toolCallId = toolCall.getToolCallId();
				String toolName = toolCall.getName();
				toolChoiceToolCallMap.put(toolCallId, toolName);
			}
		}

		// Loop over Tool messages and compare ToolCallId with Ids from Assistant
		// messages in HashMap to see whether the function from the Tool Choice has
		// already been called
		for (Message messageTool : messageListTool) {
			String toolId = messageTool.getToolCallId();
			if (toolChoiceToolCallMap.containsKey(toolId)) {
				return true;
			}
		}
		return false;
	}

	private boolean filterToolCallByFunctionName(String toolChoiceFunctionName, IMendixObject mxObject) {
		String functionName = "";
		functionName = ToolCall.initialize(getContext(), mxObject).getName();
		// Return true if the functionName equals toolChoiceFunctionName
		return functionName.equals(toolChoiceFunctionName);
	}
	
	private void mapFunctionParameters() throws CoreException {		
		// Loop through all tools, find FunctionRequest object by functionName that contains the FunctionMicroflow,
		// get InputParameterName of the FunctionMicroflow, create parametersNode and add to toolNode
		JsonNode toolsNode = rootNode.path("tools");
		for (JsonNode toolNode : toolsNode) {
			String toolName = toolNode.path("function").path("name").asText();
			Tool functionMatch = FunctionImpl.getToolByName(getRequest(RequestMapping), toolName ,getContext());
			if(functionMatch != null) {
			ObjectNode parametersNode = createToolParametersNode(functionMatch);
				if(parametersNode != null) {
					JsonNode functionNode = toolNode.path("function");
					((ObjectNode) functionNode).set("parameters", parametersNode);
					((ObjectNode) toolNode).set("function", functionNode);
				}
			}
		}
		// Update tools within rootNode
		((ObjectNode) rootNode).set("tools", toolsNode);
	}
	
	private ObjectNode createToolParametersNode(Tool tool) throws CoreException {
		
		List<ArgumentInput> arguments = tool.getTool_ArgumentInput();
		Map<String, IDataType> inputParameters = FunctionMappingImpl.getInputParametersForModel(tool.getMicroflow());
		
		if(arguments == null && (inputParameters == null || inputParameters.entrySet().isEmpty())) {
			return null;
		}
		
		ObjectNode parametersNode = MAPPER.createObjectNode();
		ObjectNode propertiesNode = MAPPER.createObjectNode();
		ArrayNode requiredNode = MAPPER.createArrayNode();
		if(arguments == null || arguments.isEmpty()) {
			inputParameters.entrySet().forEach(t -> FunctionImpl.addProperty(propertiesNode, requiredNode, t));
			
		} else {
			FunctionImpl.addPropertiesForTool(arguments, propertiesNode, requiredNode);
		}
		
		
		parametersNode.put("type", "object");
		parametersNode.set("properties", propertiesNode);
		parametersNode.set("required", requiredNode);
		
		return parametersNode;
	}		
	// END EXTRA CODE
}
