// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package openaisynthiabridge.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import openaisynthiabridge.impl.MxLogger;
import openaisynthiabridge.proxies.OpenAIConfig;
import synthiaui.impl.ProviderConfigImpl;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class OpenAIConfig_Create extends CustomJavaAction<IMendixObject>
{
	private java.lang.String ActionMicroflow;

	public OpenAIConfig_Create(IContext context, java.lang.String ActionMicroflow)
	{
		super(context);
		this.ActionMicroflow = ActionMicroflow;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		try {
		ProviderConfigImpl.validate(ActionMicroflow);
		
		OpenAIConfig openAIConfig = new OpenAIConfig(getContext());
		openAIConfig.setActionMicroflow(ActionMicroflow);
		
		return openAIConfig.getMendixObject();
		
		} catch (Exception e) {
			LOGGER.error(e.getMessage());
			throw e;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "OpenAIConfig_Create";
	}

	// BEGIN EXTRA CODE
	
	private static final MxLogger LOGGER = new MxLogger(OpenAIConfig_Create.class);
	
	// END EXTRA CODE
}
