// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mcpclient.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;
import io.modelcontextprotocol.client.McpSyncClient;
import mcpclient.impl.McpClientRegistry;
import mcpclient.impl.MxLogger;

/**
 * Closes an MCPClient that is connected to an MCP Server. Each time a client connection was started (via the "Create MCP Client" action), Mendix registers a sync client with the server. It is recommended to clean this up using this action after the connection is no longer needed, for example when the chat was closed.
 */
public class CloseMCPClient extends UserAction<java.lang.Void>
{
	/** @deprecated use MCPClient.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __MCPClient;
	private final mcpclient.proxies.MCPClient MCPClient;

	public CloseMCPClient(
		IContext context,
		IMendixObject _mCPClient
	)
	{
		super(context);
		this.__MCPClient = _mCPClient;
		this.MCPClient = _mCPClient == null ? null : mcpclient.proxies.MCPClient.initialize(getContext(), _mCPClient);
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		try {
			McpSyncClient client = McpClientRegistry.getClient(MCPClient.getMendixObject().getId().toLong());
			if(client == null) {
				LOGGER.info("The client with id " + MCPClient.getMendixObject().getId().toLong() + " could not be closed because it is not registered (anymore).");
				return null;
			}
			client.closeGracefully();
			McpClientRegistry.closeClient(MCPClient.getMendixObject().getId().toLong(), client);
		} catch (Exception e) {
			LOGGER.error("The client with id " + MCPClient.getMendixObject().getId().toLong() + " could not be closed.");
		}
		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "CloseMCPClient";
	}

	// BEGIN EXTRA CODE
	private static final MxLogger LOGGER = new mcpclient.impl.MxLogger(CloseMCPClient.class);
	// END EXTRA CODE
}
