// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mcpclient.actions;

import static java.util.Objects.requireNonNull;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;
import mcpclient.proxies.MCPClientConfig;
import system.proxies.HttpHeader;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Create an MCP Client from a Consumed MCP Service object.
 */
public class ConsumedMCPService_CreateMCPClient extends UserAction<IMendixObject>
{
	/** @deprecated use ConsumedMCPService.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __ConsumedMCPService;
	private final mcpclient.proxies.ConsumedMCPService ConsumedMCPService;

	public ConsumedMCPService_CreateMCPClient(
		IContext context,
		IMendixObject _consumedMCPService
	)
	{
		super(context);
		this.__ConsumedMCPService = _consumedMCPService;
		this.ConsumedMCPService = _consumedMCPService == null ? null : mcpclient.proxies.ConsumedMCPService.initialize(getContext(), _consumedMCPService);
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		try {
			requireNonNull(ConsumedMCPService, "ConsumedMCPService is required.");
			MCPClientConfig mcpClientConfig = new MCPClientConfig(getContext());
			mcpClientConfig.setMCPEndpoint(ConsumedMCPService.getMCPEndpoint());
			mcpClientConfig.setName(ConsumedMCPService.getName());
			mcpClientConfig.setProtocolVersion(ConsumedMCPService.getProtocolVersion());
			mcpClientConfig.setVersion(ConsumedMCPService.getVersion() != null ? ConsumedMCPService.getVersion() : "");
			mcpClientConfig.setConnectionTimeOutInSeconds(ConsumedMCPService.getConnectionTimeOutInSeconds());
	
		
			if(ConsumedMCPService.getGetCredentialsMicroflow() != null && !ConsumedMCPService.getGetCredentialsMicroflow().isBlank()) {
				List<IMendixObject> mendixObjectHeaders = Core.microflowCall(ConsumedMCPService.getGetCredentialsMicroflow()).execute(getContext());
				
				List<HttpHeader> httpheaderList = mendixObjectHeaders != null ?
		                mendixObjectHeaders.stream()
		                    .map(headerObject -> HttpHeader.initialize(getContext(), headerObject))
		                    .collect(Collectors.toList())
		                : new ArrayList<>();
				
				mcpClientConfig.setMCPClientConfig_HttpHeader(httpheaderList);
			}
		
			return Core.userActionCall("MCPClient." + CreateMCPClient.class.getSimpleName())
					.withParams(mcpClientConfig.getMendixObject())
					.execute(getContext());
		} catch (Exception e) {
			throw e;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ConsumedMCPService_CreateMCPClient";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
