// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mcpclient.actions;

import static java.util.Objects.requireNonNull;
import java.util.List;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;
import io.modelcontextprotocol.client.McpSyncClient;
import io.modelcontextprotocol.spec.McpSchema;
import io.modelcontextprotocol.spec.McpSchema.PromptArgument;
import mcpclient.impl.McpClientRegistry;
import mcpclient.impl.MxLogger;
import mcpclient.proxies.ListPromptsResult;
import mcpclient.proxies.Prompt;

/**
 * Returns a ListPromptsResult which contains a list of all available prompts the MCP Server exposes. The Prompt's name can be used in the "Get Prompt" action.
 * 
 */
public class ListPromptsResult_Get extends UserAction<IMendixObject>
{
	/** @deprecated use MCPClient.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __MCPClient;
	private final mcpclient.proxies.MCPClient MCPClient;

	public ListPromptsResult_Get(
		IContext context,
		IMendixObject _mCPClient
	)
	{
		super(context);
		this.__MCPClient = _mCPClient;
		this.MCPClient = _mCPClient == null ? null : mcpclient.proxies.MCPClient.initialize(getContext(), _mCPClient);
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		try {
			requireNonNull(MCPClient,"MCP Client is required.");
			
			McpSyncClient client = McpClientRegistry.getClient(MCPClient.getMendixObject().getId().toLong());

			McpSchema.ListPromptsResult listPromptResultMcp = client.listPrompts();

			ListPromptsResult listPromptResultMendix = createListPromptsResult(listPromptResultMcp);

			return listPromptResultMendix.getMendixObject();
		} catch (Exception e) {
			LOGGER.error(e, "Failed to list prompts for endpoint: ", MCPClient != null ? MCPClient.getMCPEndpoint() : null);
			return null;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ListPromptsResult_Get";
	}

	// BEGIN EXTRA CODE
	private static final MxLogger LOGGER = new mcpclient.impl.MxLogger(ListPromptsResult_Get.class);
	
	/**
	 * Create a Mendix ListPromptsResult based on the MCP ListPromptsResult
	 * @param listPromptResultsMcp as returned from the server via MCP 
	 */
	private ListPromptsResult createListPromptsResult(McpSchema.ListPromptsResult listPromptsResultMcp) {
		ListPromptsResult listPromptsResultMendix = new ListPromptsResult(getContext());
		List<io.modelcontextprotocol.spec.McpSchema.Prompt> promptListMcp = listPromptsResultMcp.prompts();
		listPromptsResultMendix.setNextCursor(listPromptsResultMcp.nextCursor());
		
		if(promptListMcp == null || promptListMcp.isEmpty()) {
			LOGGER.debug("List Prompts Result returned no prompts.");
			return listPromptsResultMendix;
		}
		
		for(McpSchema.Prompt promptMcp : promptListMcp ) {
			createPrompt(listPromptsResultMendix, promptMcp);			
		}
		
		return listPromptsResultMendix;
	}
	
	/**
	 * Create Mendix Prompts based on the MCP Prompts
	 * @param listPromptResultMendix
	 * @param promptMcp
	 */
	private void createPrompt(ListPromptsResult listPromptsResultMendix, McpSchema.Prompt promptMcp ) {
		Prompt promptMendix = new Prompt(getContext());
		promptMendix.setPrompt_ListPromptsResult(listPromptsResultMendix);
		promptMendix.setName(promptMcp.name());
		promptMendix.setDescription(promptMcp.description());
		
		List<PromptArgument> argumentsMcp =  promptMcp.arguments();
		
		if(argumentsMcp == null || argumentsMcp.isEmpty()) {
			return;
		}
		createPromptArguments(argumentsMcp, promptMendix);
	}
	
	/**
	 * Create Mendix PromptArguments based on the MCP Prompt's arguments
	 * @param promptMcp
	 * @param promptMendix
	 */
	private void createPromptArguments(List<PromptArgument> argumentsMcp, Prompt promptMendix) {
		
		for (McpSchema.PromptArgument promptArgumentMcp : argumentsMcp ) {
			mcpclient.proxies.PromptArgument promptArg = new mcpclient.proxies.PromptArgument(getContext());
			promptArg.setDescription(promptArgumentMcp.description());
			promptArg.setName(promptArgumentMcp.name());
			promptArg.setRequired(promptArgumentMcp.required().booleanValue());
			promptArg.setPromptArgument_Prompt(promptMendix);
		}
	}
	// END EXTRA CODE
}
