// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mcpclient.actions;

import static java.util.Objects.requireNonNull;
import java.util.List;
import java.util.Map;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;
import io.modelcontextprotocol.client.McpSyncClient;
import io.modelcontextprotocol.spec.McpSchema;
import io.modelcontextprotocol.spec.McpSchema.JsonSchema;
import mcpclient.impl.McpClientRegistry;
import mcpclient.impl.MxLogger;
import mcpclient.proxies.EnumValue;
import mcpclient.proxies.ListToolsResult;
import mcpclient.proxies.Tool;

/**
 * Returns a ListToolsResult which contains a list of all available tools the MCP Server exposes. The Tool's name can be used in the "Call Tool" action.
 * 
 */
public class ListToolsResult_Get extends UserAction<IMendixObject>
{
	/** @deprecated use MCPClient.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __MCPClient;
	private final mcpclient.proxies.MCPClient MCPClient;

	public ListToolsResult_Get(
		IContext context,
		IMendixObject _mCPClient
	)
	{
		super(context);
		this.__MCPClient = _mCPClient;
		this.MCPClient = _mCPClient == null ? null : mcpclient.proxies.MCPClient.initialize(getContext(), _mCPClient);
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		try {
			requireNonNull(MCPClient,"MCP Client is required.");

			McpSyncClient client = McpClientRegistry.getClient(MCPClient.getMendixObject().getId().toLong());	
			McpSchema.ListToolsResult listToolsResultMcp = client.listTools();	
			ListToolsResult listToolResultMendix = createListToolsResult(listToolsResultMcp);	
			return listToolResultMendix.getMendixObject();
		} catch (Exception e) {
			LOGGER.error(e, "Failed to list tools for endpoint: ", MCPClient != null ? MCPClient.getMCPEndpoint() : null);
			return null;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ListToolsResult_Get";
	}

	// BEGIN EXTRA CODE
	
	private static final MxLogger LOGGER = new mcpclient.impl.MxLogger(ListToolsResult_Get.class);
	
	/**Create a Mendix ListToolsResult based on the MCP ListToolsResult
	 * 
	 * @param listToolsResultMcp
	 * @return
	 */
	private ListToolsResult createListToolsResult(McpSchema.ListToolsResult listToolsResultMcp) {
		ListToolsResult listToolResultMendix = new ListToolsResult(getContext());
		
		listToolResultMendix.setNextCursor(listToolsResultMcp.nextCursor());
		List<McpSchema.Tool> toolListMcp = listToolsResultMcp.tools();
		
		if(toolListMcp == null || toolListMcp.isEmpty()){
			LOGGER.debug("List Tools Result returned no tools.");
			return listToolResultMendix;
		}
		
		for(McpSchema.Tool toolMcp : toolListMcp) {
			createTool(toolMcp, listToolResultMendix);
		}
		return listToolResultMendix;
	}
	
	/**
	 * Create the Mendix Tool with its argument based on the MCP Tools
	 * @param toolMcp
	 * @param listToolResultMendix
	 */
	private void createTool(McpSchema.Tool toolMcp, ListToolsResult listToolResultMendix) {
		Tool toolMendix = new Tool(getContext());
		toolMendix.setName(toolMcp.name());
		toolMendix.setDescription(toolMcp.description());
		toolMendix.setTool_ListToolsResult(listToolResultMendix);
		
		JsonSchema inputSchema = toolMcp.inputSchema();
		Map<String, Object> argumentsMcp = inputSchema.properties();
		List<String> requiredList = inputSchema.required();
		
		if(argumentsMcp == null || argumentsMcp.isEmpty()) {
			return;
		}
		createToolArguments(argumentsMcp, requiredList, toolMendix);
	}
	
	/**
	 * Creates tool arguments based on the MCP tool's arguments. 
	 * Handles Enum arguments to create EnumValue objects
	 * @param argumentsMcp
	 * @param requiredList
	 * @param toolMendix
	 */
	private void createToolArguments(Map<String, Object> argumentsMcp,List<String> requiredList, Tool toolMendix) {	
		for (Map.Entry<String, Object> entry : argumentsMcp.entrySet()) {
		    String propertyName = entry.getKey();
		    
		    //Check if the value list is a list before mapping
		    if (!(entry.getValue() instanceof Map<?, ?>)) {
		    	continue;
		    }
		    
		    Map<String, Object> propertyMap = (Map<String, Object>) entry.getValue();
		    //Safety check to ensure that rawEnum is really the expected type
		    List<Object> enumValues = null;
		    Object rawEnum = propertyMap.get("enum");
		    if (rawEnum instanceof List<?>) {
		        enumValues = (List<Object>) rawEnum;
		    }
		    
		    //Get type or change to enum if there are values
		    String type = (String) propertyMap.get("type");
		    if(enumValues != null) {
		    	type = "enum";
		    }

		    // Create ToolArgument
		    mcpclient.proxies.ToolArgument toolArg = new mcpclient.proxies.ToolArgument(getContext());
		    toolArg.setName(propertyName);
		    toolArg.set_Type(type);
		    toolArg.setRequired(requiredList != null && requiredList.contains(propertyName));
		    toolArg.setToolArgument_Tool(toolMendix);
		    
		    if (type == "enum") {
		    	createEnumValues(enumValues, toolArg);
		    }   
		}
	}
	
	/**
	 * Creates EnumValues if the property is enum
	 * @param enumValues
	 * @param toolArg
	 */
	private void createEnumValues(List<Object> enumValues, mcpclient.proxies.ToolArgument toolArg) {
		for (Object enumValueMcp : enumValues) {
            EnumValue enumValueMendix = new mcpclient.proxies.EnumValue(getContext());
            enumValueMendix.setKey(enumValueMcp.toString());
            enumValueMendix.setEnumValue_ToolArgument(toolArg);
        }
	}
	
	// END EXTRA CODE
}
