// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mcpclient.actions;

import static java.util.Objects.requireNonNull;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;
import mcpclient.proxies.MCPClientConfig;
import mcpclient.impl.MxLogger;
import system.proxies.HttpHeader;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Create an MCP Client from an MCP Server Configuration.
 */
public class MCPServerConfiguration_CreateMCPClient extends UserAction<IMendixObject>
{
	/** @deprecated use MCPServerConfiguration.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __MCPServerConfiguration;
	private final mcpclient.proxies.MCPServerConfiguration MCPServerConfiguration;

	public MCPServerConfiguration_CreateMCPClient(
		IContext context,
		IMendixObject _mCPServerConfiguration
	)
	{
		super(context);
		this.__MCPServerConfiguration = _mCPServerConfiguration;
		this.MCPServerConfiguration = _mCPServerConfiguration == null ? null : mcpclient.proxies.MCPServerConfiguration.initialize(getContext(), _mCPServerConfiguration);
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		try {
			requireNonNull(MCPServerConfiguration, "MCPServerConfiguration is required.");
			MCPClientConfig mcpClientConfig = new MCPClientConfig(getContext());
			mcpClientConfig.setMCPEndpoint(MCPServerConfiguration.getMCPEndpoint());
			mcpClientConfig.setName(MCPServerConfiguration.getName());
			mcpClientConfig.setProtocolVersion(MCPServerConfiguration.getProtocolVersion());
			mcpClientConfig.setVersion(MCPServerConfiguration.getVersion());
		
			if(MCPServerConfiguration.getGetCredentialsMicroflow() != null && !MCPServerConfiguration.getGetCredentialsMicroflow().isBlank()) {
				List<IMendixObject> mendixObjectHeaders = Core.microflowCall(MCPServerConfiguration.getGetCredentialsMicroflow()).execute(getContext());
				
				List<HttpHeader> httpheaderList = mendixObjectHeaders != null ?
		                mendixObjectHeaders.stream()
		                    .map(headerObject -> HttpHeader.initialize(getContext(), headerObject))
		                    .collect(Collectors.toList())
		                : new ArrayList<>();
				
				mcpClientConfig.setMCPClientConfig_HttpHeader(httpheaderList);
			}
		
			return Core.userActionCall("MCPClient." + CreateMCPClient.class.getSimpleName())
					.withParams(mcpClientConfig.getMendixObject())
					.execute(getContext());
		} catch (Exception e) {
			LOGGER.error(e);
			return null;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "MCPServerConfiguration_CreateMCPClient";
	}

	// BEGIN EXTRA CODE
	private static final MxLogger LOGGER = new mcpclient.impl.MxLogger(MCPServerConfiguration_CreateMCPClient.class);
	// END EXTRA CODE
}
