// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mcpclient.actions;

import java.util.stream.Collectors;
import java.util.List;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import mcpclient.impl.MxLogger;
import mcpclient.proxies.Microflow;
import system.proxies.HttpHeader;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;

public class Microflow_GetList extends UserAction<java.util.List<IMendixObject>>
{
	/** @deprecated use MicroflowSelection.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __MicroflowSelection;
	private final mcpclient.proxies.MicroflowSelection MicroflowSelection;

	public Microflow_GetList(
		IContext context,
		IMendixObject _microflowSelection
	)
	{
		super(context);
		this.__MicroflowSelection = _microflowSelection;
		this.MicroflowSelection = _microflowSelection == null ? null : mcpclient.proxies.MicroflowSelection.initialize(getContext(), _microflowSelection);
	}

	@java.lang.Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		// BEGIN USER CODE
		try {
			List<IMendixObject> modelMicroflowList = Core.getMicroflowNames().stream()
				.filter(microflowName -> !microflowName.isBlank() && microflowName.contains("."))
				.filter(microflow -> Core.getReturnType(microflow).isList())
				.filter(microflow -> Core.getMetaObject(Core.getReturnType(microflow).getObjectType()).isSubClassOf(HttpHeader.getType()))
				.filter(microflow -> Core.getInputParameters(microflow).isEmpty())
				.sorted()
				.map(microflowName -> {
					Microflow microflowImport = new Microflow(getContext());
		        	microflowImport.setName(microflowName);
		        	return microflowImport.getMendixObject();
				})
				.collect(Collectors.toList());
			return modelMicroflowList; 
		} catch (Exception e) {
		    LOGGER.error(e);
		    return null;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Microflow_GetList";
	}

	// BEGIN EXTRA CODE
	private static final MxLogger LOGGER = new MxLogger(Microflow_GetList.class);
	// END EXTRA CODE
}
