// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mcpclient.actions;

import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;
import io.modelcontextprotocol.client.McpSyncClient;
import io.modelcontextprotocol.spec.McpSchema;
import io.modelcontextprotocol.spec.McpSchema.Role;
import io.modelcontextprotocol.spec.McpSchema.TextContent;
import mcpclient.impl.McpClientRegistry;
import mcpclient.impl.MxLogger;
import mcpclient.proxies.ArgumentInput;
import mcpclient.proxies.Audience;
import mcpclient.proxies.PromptMessage;
import mcpclient.proxies.PromptResult;
import static java.util.Objects.requireNonNull;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.stream.Collectors;

/**
 * Returns a PromptResult from the MCP Server which contains the final prompt message(s) augmented with the prompt arguments (if applicable).
 */
public class PromptResult_Get extends UserAction<IMendixObject>
{
	/** @deprecated use MCPClient.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __MCPClient;
	private final mcpclient.proxies.MCPClient MCPClient;
	private final java.lang.String PromptName;
	/** @deprecated use ArgumentCollection.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __ArgumentCollection;
	private final mcpclient.proxies.ArgumentCollection ArgumentCollection;

	public PromptResult_Get(
		IContext context,
		IMendixObject _mCPClient,
		java.lang.String _promptName,
		IMendixObject _argumentCollection
	)
	{
		super(context);
		this.__MCPClient = _mCPClient;
		this.MCPClient = _mCPClient == null ? null : mcpclient.proxies.MCPClient.initialize(getContext(), _mCPClient);
		this.PromptName = _promptName;
		this.__ArgumentCollection = _argumentCollection;
		this.ArgumentCollection = _argumentCollection == null ? null : mcpclient.proxies.ArgumentCollection.initialize(getContext(), _argumentCollection);
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		try {
			requireNonNull(MCPClient,"MCP Client is required.");
			requireNonNull(PromptName,"Prompt name is required.");
			
			McpSyncClient client = McpClientRegistry.getClient(MCPClient.getMendixObject().getId().toLong());

			Map<String, Object> arguments = getArguments();
			
			McpSchema.GetPromptRequest request = new McpSchema.GetPromptRequest(PromptName, arguments);

			McpSchema.GetPromptResult resultMcp =  client.getPrompt(request);
			PromptResult getPromptResultMendix = createPromptResult(resultMcp);
			
			return getPromptResultMendix.getMendixObject();
		} catch (Exception e) {
			LOGGER.error(e, "Failed to get prompt result for endpoint: ", MCPClient != null ? MCPClient.getMCPEndpoint() : null, " and prompt name ", PromptName);
			return null;
		}

		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "PromptResult_Get";
	}

	// BEGIN EXTRA CODE
	private static final MxLogger LOGGER = new mcpclient.impl.MxLogger(PromptResult_Get.class);
	
	/**
	 * Create a Mendix GetPromptResult based on the MCP GetPromptResult
	 * @param getPromptResultMcp as returned from the server via MCP 
	 */
	private PromptResult createPromptResult(McpSchema.GetPromptResult getPromptResultMcp) {
		
		PromptResult getPromptResultMendix = new PromptResult(getContext());
		getPromptResultMendix.setDescription(getPromptResultMcp.description());
		
		List<io.modelcontextprotocol.spec.McpSchema.PromptMessage> promptMessageListMcp = getPromptResultMcp.messages();
		
		if(promptMessageListMcp == null || promptMessageListMcp.isEmpty()) {
			LOGGER.debug("Get Prompt Result returned no prompt messages.");
			return getPromptResultMendix;
		}
		
		for(io.modelcontextprotocol.spec.McpSchema.PromptMessage promptMessageMcp : promptMessageListMcp) {
			createPromptMessages(promptMessageMcp, getPromptResultMendix);
		}	
		
		return getPromptResultMendix;
	}
	
	/**
	 * For a given GetPromptResult the messages are extracted and mapped to Mendix PromptMessages
	 * @param promptMessageMcp
	 * @param getPromptResultMendix
	 */
	private void createPromptMessages(io.modelcontextprotocol.spec.McpSchema.PromptMessage promptMessageMcp, PromptResult getPromptResultMendix) {
		PromptMessage promptMessageMendix = new PromptMessage(getContext());
		TextContent textContent = (TextContent) promptMessageMcp.content();
		createAudiences(textContent, promptMessageMendix);
		promptMessageMendix.setContent(textContent.text());
		promptMessageMendix.setRole(promptMessageMcp.role().toString());
		promptMessageMendix.setPromptMessage_PromptResult(getPromptResultMendix);	
	}
	
	/**
	 * Mendix Audiences are created if they are part of the PromptMessage (Text Content)
	 * @param textContent
	 * @param promptMessageMendix
	 */
	private void createAudiences(TextContent textContent, PromptMessage promptMessageMendix){
		List<Role> audienceListMcp = textContent.audience();
		if(audienceListMcp == null || audienceListMcp.isEmpty()) {
			return;
		}
		
		for(Role role : audienceListMcp) {
			Audience audienceMendix = new Audience(getContext());
			audienceMendix.setRole(role.name());
			audienceMendix.setAudience_PromptMessage(promptMessageMendix);
		}	
	}
	
	/**
	 * Get arguments map as input for the tool call based on ArgumentCollection
	 * @throws CoreException
	 */
	private Map<String, Object> getArguments() throws CoreException {
		Map<String, Object> arguments = new HashMap<>();;
		if(ArgumentCollection == null) {
			return arguments;
		}
		
		List<ArgumentInput> argumentInputList = ArgumentCollection.getArgumentCollection_ArgumentInput();
		if(argumentInputList == null || argumentInputList.isEmpty()) {
			return arguments;
		}

		arguments = argumentInputList.stream()
				.filter(Objects::nonNull)
				.filter(arg -> arg.getName() != null)
                .filter(arg -> arg.getValue() != null)
				.collect(Collectors.toMap(ArgumentInput::getName, ArgumentInput::getValue));
		return arguments;
	}
	
	// END EXTRA CODE
}
