// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mcpclient.actions;

import static java.util.Objects.requireNonNull;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.stream.Collectors;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;
import io.modelcontextprotocol.client.McpSyncClient;
import io.modelcontextprotocol.spec.McpSchema;
import io.modelcontextprotocol.spec.McpSchema.CallToolResult;
import io.modelcontextprotocol.spec.McpSchema.Content;
import io.modelcontextprotocol.spec.McpSchema.TextContent;
import mcpclient.impl.McpClientRegistry;
import mcpclient.impl.MxLogger;
import mcpclient.proxies.ToolResult;
import mcpclient.proxies.ArgumentInput;

/**
 * Calls the Tool on the MCP Server which returns a ToolResult. The ToolResult contains the response of the tool which is typically passed to the model.
 */
public class ToolResult_Get extends UserAction<IMendixObject>
{
	/** @deprecated use MCPClient.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __MCPClient;
	private final mcpclient.proxies.MCPClient MCPClient;
	private final java.lang.String ToolName;
	/** @deprecated use ArgumentCollection.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __ArgumentCollection;
	private final mcpclient.proxies.ArgumentCollection ArgumentCollection;

	public ToolResult_Get(
		IContext context,
		IMendixObject _mCPClient,
		java.lang.String _toolName,
		IMendixObject _argumentCollection
	)
	{
		super(context);
		this.__MCPClient = _mCPClient;
		this.MCPClient = _mCPClient == null ? null : mcpclient.proxies.MCPClient.initialize(getContext(), _mCPClient);
		this.ToolName = _toolName;
		this.__ArgumentCollection = _argumentCollection;
		this.ArgumentCollection = _argumentCollection == null ? null : mcpclient.proxies.ArgumentCollection.initialize(getContext(), _argumentCollection);
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		try {
			requireNonNull(ToolName,"Toolname is required.");
			requireNonNull(MCPClient,"MCP Client is required.");
			
			McpSyncClient client = McpClientRegistry.getClient(MCPClient.getMendixObject().getId().toLong());
			
			Map<String, Object> arguments = getArguments();
			
			
			McpSchema.CallToolRequest callToolRequest = new McpSchema.CallToolRequest(ToolName, arguments);

			CallToolResult callToolResultMcp =  client.callTool(callToolRequest);
			ToolResult toolResultMendix = createToolResult(callToolResultMcp);
			
			return toolResultMendix.getMendixObject();
		} catch (Exception e) {
			LOGGER.error(e, "Failed to get tool result for endpoint: ", MCPClient != null ? MCPClient.getMCPEndpoint() : null, " and tool name ", ToolName);
			return null;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ToolResult_Get";
	}

	// BEGIN EXTRA CODE
	private static final MxLogger LOGGER = new mcpclient.impl.MxLogger(ToolResult_Get.class);
	
	/**
	 * Create a Mendix ToolResult based on the MCP CallToolResult
	 * @param callToolResultMcp
	 */
	private ToolResult createToolResult(CallToolResult callToolResultMcp) {
		List<Content> content = callToolResultMcp.content();
		TextContent textContent = (TextContent) content.get(0);
		ToolResult toolResultMendix = new ToolResult(getContext());
		toolResultMendix.setContent(textContent.text());
		return toolResultMendix;
	}	
	
	/**
	 * Get arguments map as input for the tool call based on ArgumentCollection
	 * @throws CoreException
	 */
	private Map<String, Object> getArguments() throws CoreException {
		Map<String, Object> arguments = new HashMap<>();;
		if(ArgumentCollection == null) {
			return arguments;
		}
		
		List<ArgumentInput> argumentInputList = ArgumentCollection.getArgumentCollection_ArgumentInput();
		if(argumentInputList == null || argumentInputList.isEmpty()) {
			return arguments;
		}

		arguments = argumentInputList.stream()
				.filter(Objects::nonNull)
				.filter(arg -> arg.getName() != null)
                .filter(arg -> arg.getValue() != null)
				.collect(Collectors.toMap(ArgumentInput::getName, ArgumentInput::getValue));
		return arguments;
	}
	// END EXTRA CODE
}
