// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package genaicommons.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the GenAICommons module
	/**
	 * Microflow can be used to add a File to a FileCollection. The File Collection is an optional part of the input structure for the main operations.
	 */
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder fileCollection_AddFileBuilder(
		genaicommons.proxies.FileCollection _fileCollection,
		java.lang.String _uRL,
		system.proxies.FileDocument _fileDocument,
		genaicommons.proxies.ENUM_FileType _eNUM_FileType,
		java.lang.String _textContent
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("GenAICommons.FileCollection_AddFile");
		builder = builder.withParam("FileCollection", _fileCollection);
		builder = builder.withParam("URL", _uRL);
		builder = builder.withParam("FileDocument", _fileDocument);
		builder = builder.withParam("ENUM_FileType", _eNUM_FileType == null ? null : _eNUM_FileType.name());
		builder = builder.withParam("TextContent", _textContent);
		return builder;
	}

	/**
	 * Microflow can be used to add a File to a FileCollection. The File Collection is an optional part of the input structure for the main operations.
	 */
	public static void fileCollection_AddFile(
		IContext context,
		genaicommons.proxies.FileCollection _fileCollection,
		java.lang.String _uRL,
		system.proxies.FileDocument _fileDocument,
		genaicommons.proxies.ENUM_FileType _eNUM_FileType,
		java.lang.String _textContent
	)
	{
		fileCollection_AddFileBuilder(
				_fileCollection,
				_uRL,
				_fileDocument,
				_eNUM_FileType,
				_textContent
			)
			.execute(context);
	}
	/**
	 * Microflow can be used to create a File Collection and add the first File to it immediately. The File Collection is an optional part of the input for the main operations.
	 */
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder fileCollection_CreateAndAddFileBuilder(
		java.lang.String _uRL,
		system.proxies.FileDocument _fileDocument,
		genaicommons.proxies.ENUM_FileType _eNUM_FileType,
		java.lang.String _textContent
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("GenAICommons.FileCollection_CreateAndAddFile");
		builder = builder.withParam("URL", _uRL);
		builder = builder.withParam("FileDocument", _fileDocument);
		builder = builder.withParam("ENUM_FileType", _eNUM_FileType == null ? null : _eNUM_FileType.name());
		builder = builder.withParam("TextContent", _textContent);
		return builder;
	}

	/**
	 * Microflow can be used to create a File Collection and add the first File to it immediately. The File Collection is an optional part of the input for the main operations.
	 */
	public static genaicommons.proxies.FileCollection fileCollection_CreateAndAddFile(
		IContext context,
		java.lang.String _uRL,
		system.proxies.FileDocument _fileDocument,
		genaicommons.proxies.ENUM_FileType _eNUM_FileType,
		java.lang.String _textContent
	)
	{
		Object result = fileCollection_CreateAndAddFileBuilder(
				_uRL,
				_fileDocument,
				_eNUM_FileType,
				_textContent
			)
			.execute(context);
		return result == null ? null : genaicommons.proxies.FileCollection.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder fileContent_SetAttributesBuilder(
		genaicommons.proxies.FileContent _fileContent,
		genaicommons.proxies.FileCollection _fileCollection,
		system.proxies.FileDocument _fileDocument,
		genaicommons.proxies.ENUM_FileType _eNUM_FileType,
		java.lang.String _uRL,
		java.lang.String _textContent
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("GenAICommons.FileContent_SetAttributes");
		builder = builder.withParam("FileContent", _fileContent);
		builder = builder.withParam("FileCollection", _fileCollection);
		builder = builder.withParam("FileDocument", _fileDocument);
		builder = builder.withParam("ENUM_FileType", _eNUM_FileType == null ? null : _eNUM_FileType.name());
		builder = builder.withParam("URL", _uRL);
		builder = builder.withParam("TextContent", _textContent);
		return builder;
	}

	public static void fileContent_SetAttributes(
		IContext context,
		genaicommons.proxies.FileContent _fileContent,
		genaicommons.proxies.FileCollection _fileCollection,
		system.proxies.FileDocument _fileDocument,
		genaicommons.proxies.ENUM_FileType _eNUM_FileType,
		java.lang.String _uRL,
		java.lang.String _textContent
	)
	{
		fileContent_SetAttributesBuilder(
				_fileContent,
				_fileCollection,
				_fileDocument,
				_eNUM_FileType,
				_uRL,
				_textContent
			)
			.execute(context);
	}
	/**
	 * Microflow can be used to add a message to the Request object. The calling of this operation should happen in the correct order so that the messages are sent chronologically.
	 */
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder request_AddMessageBuilder(
		genaicommons.proxies.Request _request,
		genaicommons.proxies.ENUM_MessageRole _eNUM_MessageRole,
		genaicommons.proxies.FileCollection _fileCollection,
		java.lang.String _contentString
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("GenAICommons.Request_AddMessage");
		builder = builder.withParam("Request", _request);
		builder = builder.withParam("ENUM_MessageRole", _eNUM_MessageRole == null ? null : _eNUM_MessageRole.name());
		builder = builder.withParam("FileCollection", _fileCollection);
		builder = builder.withParam("ContentString", _contentString);
		return builder;
	}

	/**
	 * Microflow can be used to add a message to the Request object. The calling of this operation should happen in the correct order so that the messages are sent chronologically.
	 */
	public static void request_AddMessage(
		IContext context,
		genaicommons.proxies.Request _request,
		genaicommons.proxies.ENUM_MessageRole _eNUM_MessageRole,
		genaicommons.proxies.FileCollection _fileCollection,
		java.lang.String _contentString
	)
	{
		request_AddMessageBuilder(
				_request,
				_eNUM_MessageRole,
				_fileCollection,
				_contentString
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder request_AddMessage_ToolBuilder(
		genaicommons.proxies.Request _request,
		genaicommons.proxies.ENUM_MessageRole _eNUM_MessageRole,
		genaicommons.proxies.FileCollection _fileCollection,
		java.util.List<genaicommons.proxies.ToolCall> _toolCallList,
		java.lang.String _toolCallId,
		java.lang.String _contentString
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("GenAICommons.Request_AddMessage_Tool");
		builder = builder.withParam("Request", _request);
		builder = builder.withParam("ENUM_MessageRole", _eNUM_MessageRole == null ? null : _eNUM_MessageRole.name());
		builder = builder.withParam("FileCollection", _fileCollection);
		builder = builder.withParam("ToolCallList", _toolCallList);
		builder = builder.withParam("ToolCallId", _toolCallId);
		builder = builder.withParam("ContentString", _contentString);
		return builder;
	}

	public static void request_AddMessage_Tool(
		IContext context,
		genaicommons.proxies.Request _request,
		genaicommons.proxies.ENUM_MessageRole _eNUM_MessageRole,
		genaicommons.proxies.FileCollection _fileCollection,
		java.util.List<genaicommons.proxies.ToolCall> _toolCallList,
		java.lang.String _toolCallId,
		java.lang.String _contentString
	)
	{
		request_AddMessage_ToolBuilder(
				_request,
				_eNUM_MessageRole,
				_fileCollection,
				_toolCallList,
				_toolCallId,
				_contentString
			)
			.execute(context);
	}
	/**
	 * This microflow can be used to add an additional stop sequence to the request
	 */
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder request_AddStopSequenceBuilder(
		genaicommons.proxies.Request _request,
		java.lang.String _stopSequence
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("GenAICommons.Request_AddStopSequence");
		builder = builder.withParam("Request", _request);
		builder = builder.withParam("StopSequence", _stopSequence);
		return builder;
	}

	/**
	 * This microflow can be used to add an additional stop sequence to the request
	 */
	public static void request_AddStopSequence(
		IContext context,
		genaicommons.proxies.Request _request,
		java.lang.String _stopSequence
	)
	{
		request_AddStopSequenceBuilder(
				_request,
				_stopSequence
			)
			.execute(context);
	}
	/**
	 * This microflow can be used to create a request. This is the main request object that contains the functional input for the model to generate a response
	 */
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder request_CreateBuilder(
		java.lang.String _systemPrompt,
		java.math.BigDecimal _temperature,
		java.lang.Long _maxTokens,
		java.math.BigDecimal _topP
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("GenAICommons.Request_Create");
		builder = builder.withParam("SystemPrompt", _systemPrompt);
		builder = builder.withParam("Temperature", _temperature);
		builder = builder.withParam("MaxTokens", _maxTokens);
		builder = builder.withParam("TopP", _topP);
		return builder;
	}

	/**
	 * This microflow can be used to create a request. This is the main request object that contains the functional input for the model to generate a response
	 */
	public static genaicommons.proxies.Request request_Create(
		IContext context,
		java.lang.String _systemPrompt,
		java.math.BigDecimal _temperature,
		java.lang.Long _maxTokens,
		java.math.BigDecimal _topP
	)
	{
		Object result = request_CreateBuilder(
				_systemPrompt,
				_temperature,
				_maxTokens,
				_topP
			)
			.execute(context);
		return result == null ? null : genaicommons.proxies.Request.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder request_GetOrCreateBuilder(
		genaicommons.proxies.Request _request
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("GenAICommons.Request_GetOrCreate");
		builder = builder.withParam("Request", _request);
		return builder;
	}

	public static genaicommons.proxies.Request request_GetOrCreate(
		IContext context,
		genaicommons.proxies.Request _request
	)
	{
		Object result = request_GetOrCreateBuilder(
				_request
			)
			.execute(context);
		return result == null ? null : genaicommons.proxies.Request.initialize(context, (IMendixObject) result);
	}
	/**
	 * Use this microflow to set the ToolChoice. This controls which (if any) function is called by the model.
	 * If the ENUM_ToolChoice equals 'tool', the Tool input is required
	 * 
	 * 
	 */
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder request_SetToolChoiceBuilder(
		genaicommons.proxies.Request _request,
		genaicommons.proxies.Tool _tool,
		genaicommons.proxies.ENUM_ToolChoice _eNUM_ToolChoice
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("GenAICommons.Request_SetToolChoice");
		builder = builder.withParam("Request", _request);
		builder = builder.withParam("Tool", _tool);
		builder = builder.withParam("ENUM_ToolChoice", _eNUM_ToolChoice == null ? null : _eNUM_ToolChoice.name());
		return builder;
	}

	/**
	 * Use this microflow to set the ToolChoice. This controls which (if any) function is called by the model.
	 * If the ENUM_ToolChoice equals 'tool', the Tool input is required
	 * 
	 * 
	 */
	public static void request_SetToolChoice(
		IContext context,
		genaicommons.proxies.Request _request,
		genaicommons.proxies.Tool _tool,
		genaicommons.proxies.ENUM_ToolChoice _eNUM_ToolChoice
	)
	{
		request_SetToolChoiceBuilder(
				_request,
				_tool,
				_eNUM_ToolChoice
			)
			.execute(context);
	}
	/**
	 * This microflow can be used to get the model response text from the response structure returned from the main operation.
	 */
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder response_GetModelResponseStringBuilder(
		genaicommons.proxies.Response _response
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("GenAICommons.Response_GetModelResponseString");
		builder = builder.withParam("Response", _response);
		return builder;
	}

	/**
	 * This microflow can be used to get the model response text from the response structure returned from the main operation.
	 */
	public static java.lang.String response_GetModelResponseString(
		IContext context,
		genaicommons.proxies.Response _response
	)
	{
		Object result = response_GetModelResponseStringBuilder(
				_response
			)
			.execute(context);
		return (java.lang.String) result;
	}
	/**
	 * This microflow can be used to retrieve the references for a given model response. These indicate what the model response was based on, according to the model logic.
	 */
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder response_GetReferencesBuilder(
		genaicommons.proxies.Response _response
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("GenAICommons.Response_GetReferences");
		builder = builder.withParam("Response", _response);
		return builder;
	}

	/**
	 * This microflow can be used to retrieve the references for a given model response. These indicate what the model response was based on, according to the model logic.
	 */
	public static java.util.List<genaicommons.proxies.Reference> response_GetReferences(
		IContext context,
		genaicommons.proxies.Response _response
	)
	{
		Object result = response_GetReferencesBuilder(
				_response
			)
			.execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> genaicommons.proxies.Reference.initialize(context, obj));
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder response_GetSelfBuilder(
		genaicommons.proxies.Response _response
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("GenAICommons.Response_GetSelf");
		builder = builder.withParam("Response", _response);
		return builder;
	}

	public static genaicommons.proxies.Response response_GetSelf(
		IContext context,
		genaicommons.proxies.Response _response
	)
	{
		Object result = response_GetSelfBuilder(
				_response
			)
			.execute(context);
		return result == null ? null : genaicommons.proxies.Response.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder tool_CastTo_FunctionBuilder(
		genaicommons.proxies.Tool _tool
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("GenAICommons.Tool_CastTo_Function");
		builder = builder.withParam("Tool", _tool);
		return builder;
	}

	public static genaicommons.proxies.Function tool_CastTo_Function(
		IContext context,
		genaicommons.proxies.Tool _tool
	)
	{
		Object result = tool_CastTo_FunctionBuilder(
				_tool
			)
			.execute(context);
		return result == null ? null : genaicommons.proxies.Function.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder tool_GetSelfBuilder(
		genaicommons.proxies.Tool _tool
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("GenAICommons.Tool_GetSelf");
		builder = builder.withParam("Tool", _tool);
		return builder;
	}

	public static genaicommons.proxies.Tool tool_GetSelf(
		IContext context,
		genaicommons.proxies.Tool _tool
	)
	{
		Object result = tool_GetSelfBuilder(
				_tool
			)
			.execute(context);
		return result == null ? null : genaicommons.proxies.Tool.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder toolCall_GetSelfBuilder(
		genaicommons.proxies.ToolCall _toolCall
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("GenAICommons.ToolCall_GetSelf");
		builder = builder.withParam("ToolCall", _toolCall);
		return builder;
	}

	public static genaicommons.proxies.ToolCall toolCall_GetSelf(
		IContext context,
		genaicommons.proxies.ToolCall _toolCall
	)
	{
		Object result = toolCall_GetSelfBuilder(
				_toolCall
			)
			.execute(context);
		return result == null ? null : genaicommons.proxies.ToolCall.initialize(context, (IMendixObject) result);
	}
}
