// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package genaicommons.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the GenAICommons module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder fileCollection_AddFileBuilder(
		genaicommons.proxies.FileCollection _fileCollection,
		java.lang.String _uRL,
		system.proxies.FileDocument _fileDocument,
		genaicommons.proxies.ENUM_FileType _eNUM_FileType,
		java.lang.String _textContent
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("GenAICommons.FileCollection_AddFile");
		builder = builder.withParam("FileCollection", _fileCollection);
		builder = builder.withParam("URL", _uRL);
		builder = builder.withParam("FileDocument", _fileDocument);
		builder = builder.withParam("ENUM_FileType", _eNUM_FileType == null ? null : _eNUM_FileType.name());
		builder = builder.withParam("TextContent", _textContent);
		return builder;
	}

	public static void fileCollection_AddFile(
		IContext context,
		genaicommons.proxies.FileCollection _fileCollection,
		java.lang.String _uRL,
		system.proxies.FileDocument _fileDocument,
		genaicommons.proxies.ENUM_FileType _eNUM_FileType,
		java.lang.String _textContent
	)
	{
		fileCollection_AddFileBuilder(
				_fileCollection,
				_uRL,
				_fileDocument,
				_eNUM_FileType,
				_textContent
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder fileCollection_CreateAndAddFileBuilder(
		java.lang.String _uRL,
		system.proxies.FileDocument _fileDocument,
		genaicommons.proxies.ENUM_FileType _eNUM_FileType,
		java.lang.String _textContent
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("GenAICommons.FileCollection_CreateAndAddFile");
		builder = builder.withParam("URL", _uRL);
		builder = builder.withParam("FileDocument", _fileDocument);
		builder = builder.withParam("ENUM_FileType", _eNUM_FileType == null ? null : _eNUM_FileType.name());
		builder = builder.withParam("TextContent", _textContent);
		return builder;
	}

	public static genaicommons.proxies.FileCollection fileCollection_CreateAndAddFile(
		IContext context,
		java.lang.String _uRL,
		system.proxies.FileDocument _fileDocument,
		genaicommons.proxies.ENUM_FileType _eNUM_FileType,
		java.lang.String _textContent
	)
	{
		Object result = fileCollection_CreateAndAddFileBuilder(
				_uRL,
				_fileDocument,
				_eNUM_FileType,
				_textContent
			)
			.execute(context);
		return result == null ? null : genaicommons.proxies.FileCollection.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder fileContent_SetAttributesBuilder(
		genaicommons.proxies.FileContent _fileContent,
		genaicommons.proxies.FileCollection _fileCollection,
		system.proxies.FileDocument _fileDocument,
		genaicommons.proxies.ENUM_FileType _eNUM_FileType,
		java.lang.String _uRL,
		java.lang.String _textContent
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("GenAICommons.FileContent_SetAttributes");
		builder = builder.withParam("FileContent", _fileContent);
		builder = builder.withParam("FileCollection", _fileCollection);
		builder = builder.withParam("FileDocument", _fileDocument);
		builder = builder.withParam("ENUM_FileType", _eNUM_FileType == null ? null : _eNUM_FileType.name());
		builder = builder.withParam("URL", _uRL);
		builder = builder.withParam("TextContent", _textContent);
		return builder;
	}

	public static void fileContent_SetAttributes(
		IContext context,
		genaicommons.proxies.FileContent _fileContent,
		genaicommons.proxies.FileCollection _fileCollection,
		system.proxies.FileDocument _fileDocument,
		genaicommons.proxies.ENUM_FileType _eNUM_FileType,
		java.lang.String _uRL,
		java.lang.String _textContent
	)
	{
		fileContent_SetAttributesBuilder(
				_fileContent,
				_fileCollection,
				_fileDocument,
				_eNUM_FileType,
				_uRL,
				_textContent
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder request_AddMessageBuilder(
		genaicommons.proxies.Request _request,
		genaicommons.proxies.ENUM_MessageRole _eNUM_MessageRole,
		genaicommons.proxies.FileCollection _fileCollection,
		java.lang.String _contentString
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("GenAICommons.Request_AddMessage");
		builder = builder.withParam("Request", _request);
		builder = builder.withParam("ENUM_MessageRole", _eNUM_MessageRole == null ? null : _eNUM_MessageRole.name());
		builder = builder.withParam("FileCollection", _fileCollection);
		builder = builder.withParam("ContentString", _contentString);
		return builder;
	}

	public static void request_AddMessage(
		IContext context,
		genaicommons.proxies.Request _request,
		genaicommons.proxies.ENUM_MessageRole _eNUM_MessageRole,
		genaicommons.proxies.FileCollection _fileCollection,
		java.lang.String _contentString
	)
	{
		request_AddMessageBuilder(
				_request,
				_eNUM_MessageRole,
				_fileCollection,
				_contentString
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder request_AddMessage_ToolBuilder(
		genaicommons.proxies.Request _request,
		genaicommons.proxies.ENUM_MessageRole _eNUM_MessageRole,
		genaicommons.proxies.FileCollection _fileCollection,
		java.util.List<genaicommons.proxies.ToolCall> _toolCallList,
		java.lang.String _toolCallId,
		java.lang.String _contentString
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("GenAICommons.Request_AddMessage_Tool");
		builder = builder.withParam("Request", _request);
		builder = builder.withParam("ENUM_MessageRole", _eNUM_MessageRole == null ? null : _eNUM_MessageRole.name());
		builder = builder.withParam("FileCollection", _fileCollection);
		builder = builder.withParam("ToolCallList", _toolCallList);
		builder = builder.withParam("ToolCallId", _toolCallId);
		builder = builder.withParam("ContentString", _contentString);
		return builder;
	}

	public static void request_AddMessage_Tool(
		IContext context,
		genaicommons.proxies.Request _request,
		genaicommons.proxies.ENUM_MessageRole _eNUM_MessageRole,
		genaicommons.proxies.FileCollection _fileCollection,
		java.util.List<genaicommons.proxies.ToolCall> _toolCallList,
		java.lang.String _toolCallId,
		java.lang.String _contentString
	)
	{
		request_AddMessage_ToolBuilder(
				_request,
				_eNUM_MessageRole,
				_fileCollection,
				_toolCallList,
				_toolCallId,
				_contentString
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder request_AddStopSequenceBuilder(
		genaicommons.proxies.Request _request,
		java.lang.String _stopSequence
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("GenAICommons.Request_AddStopSequence");
		builder = builder.withParam("Request", _request);
		builder = builder.withParam("StopSequence", _stopSequence);
		return builder;
	}

	public static void request_AddStopSequence(
		IContext context,
		genaicommons.proxies.Request _request,
		java.lang.String _stopSequence
	)
	{
		request_AddStopSequenceBuilder(
				_request,
				_stopSequence
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder request_CreateBuilder(
		java.lang.String _systemPrompt,
		java.math.BigDecimal _temperature
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("GenAICommons.Request_Create");
		builder = builder.withParam("SystemPrompt", _systemPrompt);
		builder = builder.withParam("Temperature", _temperature);
		return builder;
	}

	public static genaicommons.proxies.Request request_Create(
		IContext context,
		java.lang.String _systemPrompt,
		java.math.BigDecimal _temperature
	)
	{
		Object result = request_CreateBuilder(
				_systemPrompt,
				_temperature
			)
			.execute(context);
		return result == null ? null : genaicommons.proxies.Request.initialize(context, (IMendixObject) result);
	}
	/**
	 * ToolChoice controls which (if any) function is called by the model.
	 * Inputs:
	 * - Request: The request for which to set a tool choice.
	 * - ENUM_ToolChoice: Determines the tool choice. See below for an explanation of the different values.
	 * - Tool: only required if the ENUM_ToolChoice equals 'tool'.
	 * 
	 *  ENUM_ToolChoice:
	 * - `none` means the model will not call a tool and instead generates a message.
	 * - `auto` means the model can pick between generating a message or calling atool.
	 * - `tool` means that the Tool passed as input will become the tool choice of the ToolCollection. This will force the model to call that particular tool.
	 * - 'any' means that any function must be called. This may not be available for all providers and might change be changed to 'auto'.
	 */
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder request_SetToolChoiceBuilder(
		genaicommons.proxies.Request _request,
		genaicommons.proxies.Tool _tool,
		genaicommons.proxies.ENUM_ToolChoice _eNUM_ToolChoice
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("GenAICommons.Request_SetToolChoice");
		builder = builder.withParam("Request", _request);
		builder = builder.withParam("Tool", _tool);
		builder = builder.withParam("ENUM_ToolChoice", _eNUM_ToolChoice == null ? null : _eNUM_ToolChoice.name());
		return builder;
	}

	/**
	 * ToolChoice controls which (if any) function is called by the model.
	 * Inputs:
	 * - Request: The request for which to set a tool choice.
	 * - ENUM_ToolChoice: Determines the tool choice. See below for an explanation of the different values.
	 * - Tool: only required if the ENUM_ToolChoice equals 'tool'.
	 * 
	 *  ENUM_ToolChoice:
	 * - `none` means the model will not call a tool and instead generates a message.
	 * - `auto` means the model can pick between generating a message or calling atool.
	 * - `tool` means that the Tool passed as input will become the tool choice of the ToolCollection. This will force the model to call that particular tool.
	 * - 'any' means that any function must be called. This may not be available for all providers and might change be changed to 'auto'.
	 */
	public static void request_SetToolChoice(
		IContext context,
		genaicommons.proxies.Request _request,
		genaicommons.proxies.Tool _tool,
		genaicommons.proxies.ENUM_ToolChoice _eNUM_ToolChoice
	)
	{
		request_SetToolChoiceBuilder(
				_request,
				_tool,
				_eNUM_ToolChoice
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder response_GetAssistantResponseStringBuilder(
		genaicommons.proxies.Response _response
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("GenAICommons.Response_GetAssistantResponseString");
		builder = builder.withParam("Response", _response);
		return builder;
	}

	public static java.lang.String response_GetAssistantResponseString(
		IContext context,
		genaicommons.proxies.Response _response
	)
	{
		Object result = response_GetAssistantResponseStringBuilder(
				_response
			)
			.execute(context);
		return (java.lang.String) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder response_GetReferencesBuilder(
		genaicommons.proxies.Response _response
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("GenAICommons.Response_GetReferences");
		builder = builder.withParam("Response", _response);
		return builder;
	}

	public static java.util.List<genaicommons.proxies.Reference> response_GetReferences(
		IContext context,
		genaicommons.proxies.Response _response
	)
	{
		Object result = response_GetReferencesBuilder(
				_response
			)
			.execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> genaicommons.proxies.Reference.initialize(context, obj));
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder response_GetSelfBuilder(
		genaicommons.proxies.Response _response
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("GenAICommons.Response_GetSelf");
		builder = builder.withParam("Response", _response);
		return builder;
	}

	public static genaicommons.proxies.Response response_GetSelf(
		IContext context,
		genaicommons.proxies.Response _response
	)
	{
		Object result = response_GetSelfBuilder(
				_response
			)
			.execute(context);
		return result == null ? null : genaicommons.proxies.Response.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder tool_CastTo_FunctionBuilder(
		genaicommons.proxies.Tool _tool
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("GenAICommons.Tool_CastTo_Function");
		builder = builder.withParam("Tool", _tool);
		return builder;
	}

	public static genaicommons.proxies.Function tool_CastTo_Function(
		IContext context,
		genaicommons.proxies.Tool _tool
	)
	{
		Object result = tool_CastTo_FunctionBuilder(
				_tool
			)
			.execute(context);
		return result == null ? null : genaicommons.proxies.Function.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder tool_GetSelfBuilder(
		genaicommons.proxies.Tool _tool
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("GenAICommons.Tool_GetSelf");
		builder = builder.withParam("Tool", _tool);
		return builder;
	}

	public static genaicommons.proxies.Tool tool_GetSelf(
		IContext context,
		genaicommons.proxies.Tool _tool
	)
	{
		Object result = tool_GetSelfBuilder(
				_tool
			)
			.execute(context);
		return result == null ? null : genaicommons.proxies.Tool.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder toolCall_GetSelfBuilder(
		genaicommons.proxies.ToolCall _toolCall
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("GenAICommons.ToolCall_GetSelf");
		builder = builder.withParam("ToolCall", _toolCall);
		return builder;
	}

	public static genaicommons.proxies.ToolCall toolCall_GetSelf(
		IContext context,
		genaicommons.proxies.ToolCall _toolCall
	)
	{
		Object result = toolCall_GetSelfBuilder(
				_toolCall
			)
			.execute(context);
		return result == null ? null : genaicommons.proxies.ToolCall.initialize(context, (IMendixObject) result);
	}
}
