// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package genaicommons.proxies;

/**
 * An optional citation. This entity can be used to visualize the link between a part of the generated text and the actual text in the source on which the generated text was based.
 */
public class Citation implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject citationMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "GenAICommons.Citation";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		StartIndex("StartIndex"),
		EndIndex("EndIndex"),
		Text("Text"),
		Quote("Quote");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Citation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Citation(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject citationMendixObject)
	{
		if (citationMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, citationMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.citationMendixObject = citationMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static genaicommons.proxies.Citation initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new genaicommons.proxies.Citation(context, mendixObject);
	}

	public static genaicommons.proxies.Citation load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return genaicommons.proxies.Citation.initialize(context, mendixObject);
	}

	/**
	 * @return value of StartIndex
	 */
	public final java.lang.Integer getStartIndex()
	{
		return getStartIndex(getContext());
	}

	/**
	 * @param context
	 * @return value of StartIndex
	 */
	public final java.lang.Integer getStartIndex(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.StartIndex.toString());
	}

	/**
	 * Set value of StartIndex
	 * @param startindex
	 */
	public final void setStartIndex(java.lang.Integer startindex)
	{
		setStartIndex(getContext(), startindex);
	}

	/**
	 * Set value of StartIndex
	 * @param context
	 * @param startindex
	 */
	public final void setStartIndex(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer startindex)
	{
		getMendixObject().setValue(context, MemberNames.StartIndex.toString(), startindex);
	}

	/**
	 * @return value of EndIndex
	 */
	public final java.lang.Integer getEndIndex()
	{
		return getEndIndex(getContext());
	}

	/**
	 * @param context
	 * @return value of EndIndex
	 */
	public final java.lang.Integer getEndIndex(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.EndIndex.toString());
	}

	/**
	 * Set value of EndIndex
	 * @param endindex
	 */
	public final void setEndIndex(java.lang.Integer endindex)
	{
		setEndIndex(getContext(), endindex);
	}

	/**
	 * Set value of EndIndex
	 * @param context
	 * @param endindex
	 */
	public final void setEndIndex(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer endindex)
	{
		getMendixObject().setValue(context, MemberNames.EndIndex.toString(), endindex);
	}

	/**
	 * @return value of Text
	 */
	public final java.lang.String getText()
	{
		return getText(getContext());
	}

	/**
	 * @param context
	 * @return value of Text
	 */
	public final java.lang.String getText(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Text.toString());
	}

	/**
	 * Set value of Text
	 * @param text
	 */
	public final void setText(java.lang.String text)
	{
		setText(getContext(), text);
	}

	/**
	 * Set value of Text
	 * @param context
	 * @param text
	 */
	public final void setText(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String text)
	{
		getMendixObject().setValue(context, MemberNames.Text.toString(), text);
	}

	/**
	 * @return value of Quote
	 */
	public final java.lang.String getQuote()
	{
		return getQuote(getContext());
	}

	/**
	 * @param context
	 * @return value of Quote
	 */
	public final java.lang.String getQuote(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Quote.toString());
	}

	/**
	 * Set value of Quote
	 * @param quote
	 */
	public final void setQuote(java.lang.String quote)
	{
		setQuote(getContext(), quote);
	}

	/**
	 * Set value of Quote
	 * @param context
	 * @param quote
	 */
	public final void setQuote(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String quote)
	{
		getMendixObject().setValue(context, MemberNames.Quote.toString(), quote);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return citationMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final genaicommons.proxies.Citation that = (genaicommons.proxies.Citation) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
