// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package genaicommons.proxies;

/**
 * The DeployedModel represents a GenAI model that can be invoked by the Mendix app. It contains a display name and a technical name/identifier. It also contains the name of the microflow to be executed for the specified model and other information relevant to connect to a model.
 * 
 * The DeployedModel entity replaces the capabilities that were coverd by the Connection entity in earlier versions of GenAI Commons.
 */
public class DeployedModel implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject deployedModelMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "GenAICommons.DeployedModel";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		DisplayName("DisplayName"),
		Architecture("Architecture"),
		Model("Model"),
		OutputModality("OutputModality"),
		Microflow("Microflow"),
		SupportsSystemPrompt("SupportsSystemPrompt"),
		SupportsConversationsWithHistory("SupportsConversationsWithHistory"),
		SupportsFunctionCalling("SupportsFunctionCalling"),
		IsActive("IsActive"),
		DeployedModel_InputModality("GenAICommons.DeployedModel_InputModality");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public DeployedModel(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected DeployedModel(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject deployedModelMendixObject)
	{
		if (deployedModelMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, deployedModelMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.deployedModelMendixObject = deployedModelMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static genaicommons.proxies.DeployedModel initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		if (com.mendix.core.Core.isSubClassOf("AmazonBedrockConnector.BedrockDeployedModel", mendixObject.getType())) {
			return amazonbedrockconnector.proxies.BedrockDeployedModel.initialize(context, mendixObject);
		}
		if (com.mendix.core.Core.isSubClassOf("MxGenAIConnector.MxCloudDeployedModel", mendixObject.getType())) {
			return mxgenaiconnector.proxies.MxCloudDeployedModel.initialize(context, mendixObject);
		}
		if (com.mendix.core.Core.isSubClassOf("OpenAIConnector.OpenAIDeployedModel", mendixObject.getType())) {
			return openaiconnector.proxies.OpenAIDeployedModel.initialize(context, mendixObject);
		}
		return new genaicommons.proxies.DeployedModel(context, mendixObject);
	}

	public static genaicommons.proxies.DeployedModel load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return genaicommons.proxies.DeployedModel.initialize(context, mendixObject);
	}

	public static java.util.List<? extends genaicommons.proxies.DeployedModel> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> genaicommons.proxies.DeployedModel.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of DisplayName
	 */
	public final java.lang.String getDisplayName()
	{
		return getDisplayName(getContext());
	}

	/**
	 * @param context
	 * @return value of DisplayName
	 */
	public final java.lang.String getDisplayName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DisplayName.toString());
	}

	/**
	 * Set value of DisplayName
	 * @param displayname
	 */
	public final void setDisplayName(java.lang.String displayname)
	{
		setDisplayName(getContext(), displayname);
	}

	/**
	 * Set value of DisplayName
	 * @param context
	 * @param displayname
	 */
	public final void setDisplayName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String displayname)
	{
		getMendixObject().setValue(context, MemberNames.DisplayName.toString(), displayname);
	}

	/**
	 * @return value of Architecture
	 */
	public final java.lang.String getArchitecture()
	{
		return getArchitecture(getContext());
	}

	/**
	 * @param context
	 * @return value of Architecture
	 */
	public final java.lang.String getArchitecture(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Architecture.toString());
	}

	/**
	 * Set value of Architecture
	 * @param architecture
	 */
	public final void setArchitecture(java.lang.String architecture)
	{
		setArchitecture(getContext(), architecture);
	}

	/**
	 * Set value of Architecture
	 * @param context
	 * @param architecture
	 */
	public final void setArchitecture(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String architecture)
	{
		getMendixObject().setValue(context, MemberNames.Architecture.toString(), architecture);
	}

	/**
	 * @return value of Model
	 */
	public final java.lang.String getModel()
	{
		return getModel(getContext());
	}

	/**
	 * @param context
	 * @return value of Model
	 */
	public final java.lang.String getModel(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Model.toString());
	}

	/**
	 * Set value of Model
	 * @param model
	 */
	public final void setModel(java.lang.String model)
	{
		setModel(getContext(), model);
	}

	/**
	 * Set value of Model
	 * @param context
	 * @param model
	 */
	public final void setModel(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String model)
	{
		getMendixObject().setValue(context, MemberNames.Model.toString(), model);
	}

	/**
	 * Get value of OutputModality
	 * @param outputmodality
	 */
	public final genaicommons.proxies.ENUM_ModelModality getOutputModality()
	{
		return getOutputModality(getContext());
	}

	/**
	 * @param context
	 * @return value of OutputModality
	 */
	public final genaicommons.proxies.ENUM_ModelModality getOutputModality(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.OutputModality.toString());
		if (obj == null) {
			return null;
		}
		return genaicommons.proxies.ENUM_ModelModality.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of OutputModality
	 * @param outputmodality
	 */
	public final void setOutputModality(genaicommons.proxies.ENUM_ModelModality outputmodality)
	{
		setOutputModality(getContext(), outputmodality);
	}

	/**
	 * Set value of OutputModality
	 * @param context
	 * @param outputmodality
	 */
	public final void setOutputModality(com.mendix.systemwideinterfaces.core.IContext context, genaicommons.proxies.ENUM_ModelModality outputmodality)
	{
		if (outputmodality != null) {
			getMendixObject().setValue(context, MemberNames.OutputModality.toString(), outputmodality.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.OutputModality.toString(), null);
		}
	}

	/**
	 * @return value of Microflow
	 */
	public final java.lang.String getMicroflow()
	{
		return getMicroflow(getContext());
	}

	/**
	 * @param context
	 * @return value of Microflow
	 */
	public final java.lang.String getMicroflow(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Microflow.toString());
	}

	/**
	 * Set value of Microflow
	 * @param microflow
	 */
	public final void setMicroflow(java.lang.String microflow)
	{
		setMicroflow(getContext(), microflow);
	}

	/**
	 * Set value of Microflow
	 * @param context
	 * @param microflow
	 */
	public final void setMicroflow(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String microflow)
	{
		getMendixObject().setValue(context, MemberNames.Microflow.toString(), microflow);
	}

	/**
	 * Get value of SupportsSystemPrompt
	 * @param supportssystemprompt
	 */
	public final genaicommons.proxies.ENUM_ModelSupport getSupportsSystemPrompt()
	{
		return getSupportsSystemPrompt(getContext());
	}

	/**
	 * @param context
	 * @return value of SupportsSystemPrompt
	 */
	public final genaicommons.proxies.ENUM_ModelSupport getSupportsSystemPrompt(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.SupportsSystemPrompt.toString());
		if (obj == null) {
			return null;
		}
		return genaicommons.proxies.ENUM_ModelSupport.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of SupportsSystemPrompt
	 * @param supportssystemprompt
	 */
	public final void setSupportsSystemPrompt(genaicommons.proxies.ENUM_ModelSupport supportssystemprompt)
	{
		setSupportsSystemPrompt(getContext(), supportssystemprompt);
	}

	/**
	 * Set value of SupportsSystemPrompt
	 * @param context
	 * @param supportssystemprompt
	 */
	public final void setSupportsSystemPrompt(com.mendix.systemwideinterfaces.core.IContext context, genaicommons.proxies.ENUM_ModelSupport supportssystemprompt)
	{
		if (supportssystemprompt != null) {
			getMendixObject().setValue(context, MemberNames.SupportsSystemPrompt.toString(), supportssystemprompt.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.SupportsSystemPrompt.toString(), null);
		}
	}

	/**
	 * Get value of SupportsConversationsWithHistory
	 * @param supportsconversationswithhistory
	 */
	public final genaicommons.proxies.ENUM_ModelSupport getSupportsConversationsWithHistory()
	{
		return getSupportsConversationsWithHistory(getContext());
	}

	/**
	 * @param context
	 * @return value of SupportsConversationsWithHistory
	 */
	public final genaicommons.proxies.ENUM_ModelSupport getSupportsConversationsWithHistory(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.SupportsConversationsWithHistory.toString());
		if (obj == null) {
			return null;
		}
		return genaicommons.proxies.ENUM_ModelSupport.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of SupportsConversationsWithHistory
	 * @param supportsconversationswithhistory
	 */
	public final void setSupportsConversationsWithHistory(genaicommons.proxies.ENUM_ModelSupport supportsconversationswithhistory)
	{
		setSupportsConversationsWithHistory(getContext(), supportsconversationswithhistory);
	}

	/**
	 * Set value of SupportsConversationsWithHistory
	 * @param context
	 * @param supportsconversationswithhistory
	 */
	public final void setSupportsConversationsWithHistory(com.mendix.systemwideinterfaces.core.IContext context, genaicommons.proxies.ENUM_ModelSupport supportsconversationswithhistory)
	{
		if (supportsconversationswithhistory != null) {
			getMendixObject().setValue(context, MemberNames.SupportsConversationsWithHistory.toString(), supportsconversationswithhistory.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.SupportsConversationsWithHistory.toString(), null);
		}
	}

	/**
	 * Get value of SupportsFunctionCalling
	 * @param supportsfunctioncalling
	 */
	public final genaicommons.proxies.ENUM_ModelSupport getSupportsFunctionCalling()
	{
		return getSupportsFunctionCalling(getContext());
	}

	/**
	 * @param context
	 * @return value of SupportsFunctionCalling
	 */
	public final genaicommons.proxies.ENUM_ModelSupport getSupportsFunctionCalling(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.SupportsFunctionCalling.toString());
		if (obj == null) {
			return null;
		}
		return genaicommons.proxies.ENUM_ModelSupport.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of SupportsFunctionCalling
	 * @param supportsfunctioncalling
	 */
	public final void setSupportsFunctionCalling(genaicommons.proxies.ENUM_ModelSupport supportsfunctioncalling)
	{
		setSupportsFunctionCalling(getContext(), supportsfunctioncalling);
	}

	/**
	 * Set value of SupportsFunctionCalling
	 * @param context
	 * @param supportsfunctioncalling
	 */
	public final void setSupportsFunctionCalling(com.mendix.systemwideinterfaces.core.IContext context, genaicommons.proxies.ENUM_ModelSupport supportsfunctioncalling)
	{
		if (supportsfunctioncalling != null) {
			getMendixObject().setValue(context, MemberNames.SupportsFunctionCalling.toString(), supportsfunctioncalling.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.SupportsFunctionCalling.toString(), null);
		}
	}

	/**
	 * @return value of IsActive
	 */
	public final java.lang.Boolean getIsActive()
	{
		return getIsActive(getContext());
	}

	/**
	 * @param context
	 * @return value of IsActive
	 */
	public final java.lang.Boolean getIsActive(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsActive.toString());
	}

	/**
	 * Set value of IsActive
	 * @param isactive
	 */
	public final void setIsActive(java.lang.Boolean isactive)
	{
		setIsActive(getContext(), isactive);
	}

	/**
	 * Set value of IsActive
	 * @param context
	 * @param isactive
	 */
	public final void setIsActive(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isactive)
	{
		getMendixObject().setValue(context, MemberNames.IsActive.toString(), isactive);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of DeployedModel_InputModality
	 */
	public final java.util.List<genaicommons.proxies.InputModality> getDeployedModel_InputModality() throws com.mendix.core.CoreException
	{
		return getDeployedModel_InputModality(getContext());
	}

	/**
	 * @param context
	 * @return value of DeployedModel_InputModality
	 * @throws com.mendix.core.CoreException
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<genaicommons.proxies.InputModality> getDeployedModel_InputModality(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<genaicommons.proxies.InputModality> result = new java.util.ArrayList<>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.DeployedModel_InputModality.toString());
		if (valueObject == null) {
			return result;
		}
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject)) {
			result.add(genaicommons.proxies.InputModality.initialize(context, mendixObject));
		}
		return result;
	}

	/**
	 * Set value of DeployedModel_InputModality
	 * @param deployedmodel_inputmodality
	 */
	public final void setDeployedModel_InputModality(java.util.List<genaicommons.proxies.InputModality> deployedmodel_inputmodality)
	{
		setDeployedModel_InputModality(getContext(), deployedmodel_inputmodality);
	}

	/**
	 * Set value of DeployedModel_InputModality
	 * @param context
	 * @param deployedmodel_inputmodality
	 */
	public final void setDeployedModel_InputModality(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<genaicommons.proxies.InputModality> deployedmodel_inputmodality)
	{
		var identifiers = deployedmodel_inputmodality
			.stream()
			.map(proxyObject -> proxyObject.getMendixObject().getId())
			.collect(java.util.stream.Collectors.toList());
		
		getMendixObject().setValue(context, MemberNames.DeployedModel_InputModality.toString(), identifiers);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return deployedModelMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final genaicommons.proxies.DeployedModel that = (genaicommons.proxies.DeployedModel) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
