// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package genaicommons.proxies;

/**
 * An optional input object for the embeddings operations to set optional request attributes.
 */
public class EmbeddingsOptions implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject embeddingsOptionsMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "GenAICommons.EmbeddingsOptions";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Dimensions("Dimensions");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public EmbeddingsOptions(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected EmbeddingsOptions(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject embeddingsOptionsMendixObject)
	{
		if (embeddingsOptionsMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, embeddingsOptionsMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.embeddingsOptionsMendixObject = embeddingsOptionsMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static genaicommons.proxies.EmbeddingsOptions initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new genaicommons.proxies.EmbeddingsOptions(context, mendixObject);
	}

	public static genaicommons.proxies.EmbeddingsOptions load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return genaicommons.proxies.EmbeddingsOptions.initialize(context, mendixObject);
	}

	/**
	 * @return value of Dimensions
	 */
	public final java.lang.Integer getDimensions()
	{
		return getDimensions(getContext());
	}

	/**
	 * @param context
	 * @return value of Dimensions
	 */
	public final java.lang.Integer getDimensions(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Dimensions.toString());
	}

	/**
	 * Set value of Dimensions
	 * @param dimensions
	 */
	public final void setDimensions(java.lang.Integer dimensions)
	{
		setDimensions(getContext(), dimensions);
	}

	/**
	 * Set value of Dimensions
	 * @param context
	 * @param dimensions
	 */
	public final void setDimensions(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer dimensions)
	{
		getMendixObject().setValue(context, MemberNames.Dimensions.toString(), dimensions);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return embeddingsOptionsMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final genaicommons.proxies.EmbeddingsOptions that = (genaicommons.proxies.EmbeddingsOptions) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
