// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package genaicommons.proxies;

/**
 * An optional input object for the image generations operations to set optional request attributes.
 */
public class ImageOptions implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject imageOptionsMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "GenAICommons.ImageOptions";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Height("Height"),
		Width("Width"),
		NumberOfImages("NumberOfImages"),
		Seed("Seed"),
		CfgScale("CfgScale"),
		ImageGenerationType("ImageGenerationType");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ImageOptions(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ImageOptions(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject imageOptionsMendixObject)
	{
		if (imageOptionsMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, imageOptionsMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.imageOptionsMendixObject = imageOptionsMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static genaicommons.proxies.ImageOptions initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new genaicommons.proxies.ImageOptions(context, mendixObject);
	}

	public static genaicommons.proxies.ImageOptions load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return genaicommons.proxies.ImageOptions.initialize(context, mendixObject);
	}

	/**
	 * @return value of Height
	 */
	public final java.lang.Integer getHeight()
	{
		return getHeight(getContext());
	}

	/**
	 * @param context
	 * @return value of Height
	 */
	public final java.lang.Integer getHeight(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Height.toString());
	}

	/**
	 * Set value of Height
	 * @param height
	 */
	public final void setHeight(java.lang.Integer height)
	{
		setHeight(getContext(), height);
	}

	/**
	 * Set value of Height
	 * @param context
	 * @param height
	 */
	public final void setHeight(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer height)
	{
		getMendixObject().setValue(context, MemberNames.Height.toString(), height);
	}

	/**
	 * @return value of Width
	 */
	public final java.lang.Integer getWidth()
	{
		return getWidth(getContext());
	}

	/**
	 * @param context
	 * @return value of Width
	 */
	public final java.lang.Integer getWidth(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Width.toString());
	}

	/**
	 * Set value of Width
	 * @param width
	 */
	public final void setWidth(java.lang.Integer width)
	{
		setWidth(getContext(), width);
	}

	/**
	 * Set value of Width
	 * @param context
	 * @param width
	 */
	public final void setWidth(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer width)
	{
		getMendixObject().setValue(context, MemberNames.Width.toString(), width);
	}

	/**
	 * @return value of NumberOfImages
	 */
	public final java.lang.Integer getNumberOfImages()
	{
		return getNumberOfImages(getContext());
	}

	/**
	 * @param context
	 * @return value of NumberOfImages
	 */
	public final java.lang.Integer getNumberOfImages(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.NumberOfImages.toString());
	}

	/**
	 * Set value of NumberOfImages
	 * @param numberofimages
	 */
	public final void setNumberOfImages(java.lang.Integer numberofimages)
	{
		setNumberOfImages(getContext(), numberofimages);
	}

	/**
	 * Set value of NumberOfImages
	 * @param context
	 * @param numberofimages
	 */
	public final void setNumberOfImages(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer numberofimages)
	{
		getMendixObject().setValue(context, MemberNames.NumberOfImages.toString(), numberofimages);
	}

	/**
	 * @return value of Seed
	 */
	public final java.lang.Integer getSeed()
	{
		return getSeed(getContext());
	}

	/**
	 * @param context
	 * @return value of Seed
	 */
	public final java.lang.Integer getSeed(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Seed.toString());
	}

	/**
	 * Set value of Seed
	 * @param seed
	 */
	public final void setSeed(java.lang.Integer seed)
	{
		setSeed(getContext(), seed);
	}

	/**
	 * Set value of Seed
	 * @param context
	 * @param seed
	 */
	public final void setSeed(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer seed)
	{
		getMendixObject().setValue(context, MemberNames.Seed.toString(), seed);
	}

	/**
	 * @return value of CfgScale
	 */
	public final java.math.BigDecimal getCfgScale()
	{
		return getCfgScale(getContext());
	}

	/**
	 * @param context
	 * @return value of CfgScale
	 */
	public final java.math.BigDecimal getCfgScale(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.CfgScale.toString());
	}

	/**
	 * Set value of CfgScale
	 * @param cfgscale
	 */
	public final void setCfgScale(java.math.BigDecimal cfgscale)
	{
		setCfgScale(getContext(), cfgscale);
	}

	/**
	 * Set value of CfgScale
	 * @param context
	 * @param cfgscale
	 */
	public final void setCfgScale(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal cfgscale)
	{
		getMendixObject().setValue(context, MemberNames.CfgScale.toString(), cfgscale);
	}

	/**
	 * Get value of ImageGenerationType
	 * @param imagegenerationtype
	 */
	public final genaicommons.proxies.ENUM_ImageGenerationType getImageGenerationType()
	{
		return getImageGenerationType(getContext());
	}

	/**
	 * @param context
	 * @return value of ImageGenerationType
	 */
	public final genaicommons.proxies.ENUM_ImageGenerationType getImageGenerationType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.ImageGenerationType.toString());
		if (obj == null) {
			return null;
		}
		return genaicommons.proxies.ENUM_ImageGenerationType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of ImageGenerationType
	 * @param imagegenerationtype
	 */
	public final void setImageGenerationType(genaicommons.proxies.ENUM_ImageGenerationType imagegenerationtype)
	{
		setImageGenerationType(getContext(), imagegenerationtype);
	}

	/**
	 * Set value of ImageGenerationType
	 * @param context
	 * @param imagegenerationtype
	 */
	public final void setImageGenerationType(com.mendix.systemwideinterfaces.core.IContext context, genaicommons.proxies.ENUM_ImageGenerationType imagegenerationtype)
	{
		if (imagegenerationtype != null) {
			getMendixObject().setValue(context, MemberNames.ImageGenerationType.toString(), imagegenerationtype.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.ImageGenerationType.toString(), null);
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return imageOptionsMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final genaicommons.proxies.ImageOptions that = (genaicommons.proxies.ImageOptions) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
