// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package genaicommons.proxies;

/**
 * A tool of type function, which represents a microflow that can be executed inside this app. Typically used internally inside of connector operations to enable the model with a knowledge base retrieval.
 */
public class KnowledgeBaseRetrieval extends genaicommons.proxies.Tool
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "GenAICommons.KnowledgeBaseRetrieval";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		MinimumSimilarity("MinimumSimilarity"),
		MaxNumberOfResults("MaxNumberOfResults"),
		Name("Name"),
		Description("Description"),
		ToolType("ToolType"),
		Microflow("Microflow"),
		KnowledgeBaseRetrieval_Connection("GenAICommons.KnowledgeBaseRetrieval_Connection"),
		KnowledgeBaseRetrieval_MetadataCollection("GenAICommons.KnowledgeBaseRetrieval_MetadataCollection");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public KnowledgeBaseRetrieval(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected KnowledgeBaseRetrieval(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject knowledgeBaseRetrievalMendixObject)
	{
		super(context, knowledgeBaseRetrievalMendixObject);
		if (!com.mendix.core.Core.isSubClassOf(entityName, knowledgeBaseRetrievalMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static genaicommons.proxies.KnowledgeBaseRetrieval initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new genaicommons.proxies.KnowledgeBaseRetrieval(context, mendixObject);
	}

	public static genaicommons.proxies.KnowledgeBaseRetrieval load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return genaicommons.proxies.KnowledgeBaseRetrieval.initialize(context, mendixObject);
	}

	/**
	 * @return value of MinimumSimilarity
	 */
	public final java.math.BigDecimal getMinimumSimilarity()
	{
		return getMinimumSimilarity(getContext());
	}

	/**
	 * @param context
	 * @return value of MinimumSimilarity
	 */
	public final java.math.BigDecimal getMinimumSimilarity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.MinimumSimilarity.toString());
	}

	/**
	 * Set value of MinimumSimilarity
	 * @param minimumsimilarity
	 */
	public final void setMinimumSimilarity(java.math.BigDecimal minimumsimilarity)
	{
		setMinimumSimilarity(getContext(), minimumsimilarity);
	}

	/**
	 * Set value of MinimumSimilarity
	 * @param context
	 * @param minimumsimilarity
	 */
	public final void setMinimumSimilarity(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal minimumsimilarity)
	{
		getMendixObject().setValue(context, MemberNames.MinimumSimilarity.toString(), minimumsimilarity);
	}

	/**
	 * @return value of MaxNumberOfResults
	 */
	public final java.lang.Integer getMaxNumberOfResults()
	{
		return getMaxNumberOfResults(getContext());
	}

	/**
	 * @param context
	 * @return value of MaxNumberOfResults
	 */
	public final java.lang.Integer getMaxNumberOfResults(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.MaxNumberOfResults.toString());
	}

	/**
	 * Set value of MaxNumberOfResults
	 * @param maxnumberofresults
	 */
	public final void setMaxNumberOfResults(java.lang.Integer maxnumberofresults)
	{
		setMaxNumberOfResults(getContext(), maxnumberofresults);
	}

	/**
	 * Set value of MaxNumberOfResults
	 * @param context
	 * @param maxnumberofresults
	 */
	public final void setMaxNumberOfResults(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer maxnumberofresults)
	{
		getMendixObject().setValue(context, MemberNames.MaxNumberOfResults.toString(), maxnumberofresults);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of KnowledgeBaseRetrieval_Connection
	 */
	public final genaicommons.proxies.Connection getKnowledgeBaseRetrieval_Connection() throws com.mendix.core.CoreException
	{
		return getKnowledgeBaseRetrieval_Connection(getContext());
	}

	/**
	 * @param context
	 * @return value of KnowledgeBaseRetrieval_Connection
	 * @throws com.mendix.core.CoreException
	 */
	public final genaicommons.proxies.Connection getKnowledgeBaseRetrieval_Connection(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		genaicommons.proxies.Connection result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.KnowledgeBaseRetrieval_Connection.toString());
		if (identifier != null) {
			result = genaicommons.proxies.Connection.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of KnowledgeBaseRetrieval_Connection
	 * @param knowledgebaseretrieval_connection
	 */
	public final void setKnowledgeBaseRetrieval_Connection(genaicommons.proxies.Connection knowledgebaseretrieval_connection)
	{
		setKnowledgeBaseRetrieval_Connection(getContext(), knowledgebaseretrieval_connection);
	}

	/**
	 * Set value of KnowledgeBaseRetrieval_Connection
	 * @param context
	 * @param knowledgebaseretrieval_connection
	 */
	public final void setKnowledgeBaseRetrieval_Connection(com.mendix.systemwideinterfaces.core.IContext context, genaicommons.proxies.Connection knowledgebaseretrieval_connection)
	{
		if (knowledgebaseretrieval_connection == null) {
			getMendixObject().setValue(context, MemberNames.KnowledgeBaseRetrieval_Connection.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.KnowledgeBaseRetrieval_Connection.toString(), knowledgebaseretrieval_connection.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of KnowledgeBaseRetrieval_MetadataCollection
	 */
	public final genaicommons.proxies.MetadataCollection getKnowledgeBaseRetrieval_MetadataCollection() throws com.mendix.core.CoreException
	{
		return getKnowledgeBaseRetrieval_MetadataCollection(getContext());
	}

	/**
	 * @param context
	 * @return value of KnowledgeBaseRetrieval_MetadataCollection
	 * @throws com.mendix.core.CoreException
	 */
	public final genaicommons.proxies.MetadataCollection getKnowledgeBaseRetrieval_MetadataCollection(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		genaicommons.proxies.MetadataCollection result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.KnowledgeBaseRetrieval_MetadataCollection.toString());
		if (identifier != null) {
			result = genaicommons.proxies.MetadataCollection.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of KnowledgeBaseRetrieval_MetadataCollection
	 * @param knowledgebaseretrieval_metadatacollection
	 */
	public final void setKnowledgeBaseRetrieval_MetadataCollection(genaicommons.proxies.MetadataCollection knowledgebaseretrieval_metadatacollection)
	{
		setKnowledgeBaseRetrieval_MetadataCollection(getContext(), knowledgebaseretrieval_metadatacollection);
	}

	/**
	 * Set value of KnowledgeBaseRetrieval_MetadataCollection
	 * @param context
	 * @param knowledgebaseretrieval_metadatacollection
	 */
	public final void setKnowledgeBaseRetrieval_MetadataCollection(com.mendix.systemwideinterfaces.core.IContext context, genaicommons.proxies.MetadataCollection knowledgebaseretrieval_metadatacollection)
	{
		if (knowledgebaseretrieval_metadatacollection == null) {
			getMendixObject().setValue(context, MemberNames.KnowledgeBaseRetrieval_MetadataCollection.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.KnowledgeBaseRetrieval_MetadataCollection.toString(), knowledgebaseretrieval_metadatacollection.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final genaicommons.proxies.KnowledgeBaseRetrieval that = (genaicommons.proxies.KnowledgeBaseRetrieval) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
