// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package genaicommons.proxies;

/**
 * The response returned by model contains usage metrics as well as a response message.
 */
public class Response implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject responseMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "GenAICommons.Response";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		RequestTokens("RequestTokens"),
		ResponseTokens("ResponseTokens"),
		TotalTokens("TotalTokens"),
		StopReason("StopReason"),
		Response_Message("GenAICommons.Response_Message");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Response(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Response(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject responseMendixObject)
	{
		if (responseMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, responseMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.responseMendixObject = responseMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static genaicommons.proxies.Response initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		if (com.mendix.core.Core.isSubClassOf("AmazonBedrockConnector.ChatCompletionsResponse", mendixObject.getType())) {
			return amazonbedrockconnector.proxies.ChatCompletionsResponse.initialize(context, mendixObject);
		}
		if (com.mendix.core.Core.isSubClassOf("AmazonBedrockConnector.RetrieveAndGenerateResponse", mendixObject.getType())) {
			return amazonbedrockconnector.proxies.RetrieveAndGenerateResponse.initialize(context, mendixObject);
		}
		if (com.mendix.core.Core.isSubClassOf("AmazonBedrockConnector.TitanImageResponse", mendixObject.getType())) {
			return amazonbedrockconnector.proxies.TitanImageResponse.initialize(context, mendixObject);
		}
		return new genaicommons.proxies.Response(context, mendixObject);
	}

	public static genaicommons.proxies.Response load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return genaicommons.proxies.Response.initialize(context, mendixObject);
	}

	/**
	 * @return value of RequestTokens
	 */
	public final java.lang.Integer getRequestTokens()
	{
		return getRequestTokens(getContext());
	}

	/**
	 * @param context
	 * @return value of RequestTokens
	 */
	public final java.lang.Integer getRequestTokens(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.RequestTokens.toString());
	}

	/**
	 * Set value of RequestTokens
	 * @param requesttokens
	 */
	public final void setRequestTokens(java.lang.Integer requesttokens)
	{
		setRequestTokens(getContext(), requesttokens);
	}

	/**
	 * Set value of RequestTokens
	 * @param context
	 * @param requesttokens
	 */
	public final void setRequestTokens(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer requesttokens)
	{
		getMendixObject().setValue(context, MemberNames.RequestTokens.toString(), requesttokens);
	}

	/**
	 * @return value of ResponseTokens
	 */
	public final java.lang.Integer getResponseTokens()
	{
		return getResponseTokens(getContext());
	}

	/**
	 * @param context
	 * @return value of ResponseTokens
	 */
	public final java.lang.Integer getResponseTokens(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.ResponseTokens.toString());
	}

	/**
	 * Set value of ResponseTokens
	 * @param responsetokens
	 */
	public final void setResponseTokens(java.lang.Integer responsetokens)
	{
		setResponseTokens(getContext(), responsetokens);
	}

	/**
	 * Set value of ResponseTokens
	 * @param context
	 * @param responsetokens
	 */
	public final void setResponseTokens(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer responsetokens)
	{
		getMendixObject().setValue(context, MemberNames.ResponseTokens.toString(), responsetokens);
	}

	/**
	 * @return value of TotalTokens
	 */
	public final java.lang.Integer getTotalTokens()
	{
		return getTotalTokens(getContext());
	}

	/**
	 * @param context
	 * @return value of TotalTokens
	 */
	public final java.lang.Integer getTotalTokens(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.TotalTokens.toString());
	}

	/**
	 * Set value of TotalTokens
	 * @param totaltokens
	 */
	public final void setTotalTokens(java.lang.Integer totaltokens)
	{
		setTotalTokens(getContext(), totaltokens);
	}

	/**
	 * Set value of TotalTokens
	 * @param context
	 * @param totaltokens
	 */
	public final void setTotalTokens(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer totaltokens)
	{
		getMendixObject().setValue(context, MemberNames.TotalTokens.toString(), totaltokens);
	}

	/**
	 * @return value of StopReason
	 */
	public final java.lang.String getStopReason()
	{
		return getStopReason(getContext());
	}

	/**
	 * @param context
	 * @return value of StopReason
	 */
	public final java.lang.String getStopReason(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.StopReason.toString());
	}

	/**
	 * Set value of StopReason
	 * @param stopreason
	 */
	public final void setStopReason(java.lang.String stopreason)
	{
		setStopReason(getContext(), stopreason);
	}

	/**
	 * Set value of StopReason
	 * @param context
	 * @param stopreason
	 */
	public final void setStopReason(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String stopreason)
	{
		getMendixObject().setValue(context, MemberNames.StopReason.toString(), stopreason);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Response_Message
	 */
	public final genaicommons.proxies.Message getResponse_Message() throws com.mendix.core.CoreException
	{
		return getResponse_Message(getContext());
	}

	/**
	 * @param context
	 * @return value of Response_Message
	 * @throws com.mendix.core.CoreException
	 */
	public final genaicommons.proxies.Message getResponse_Message(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		genaicommons.proxies.Message result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Response_Message.toString());
		if (identifier != null) {
			result = genaicommons.proxies.Message.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Response_Message
	 * @param response_message
	 */
	public final void setResponse_Message(genaicommons.proxies.Message response_message)
	{
		setResponse_Message(getContext(), response_message);
	}

	/**
	 * Set value of Response_Message
	 * @param context
	 * @param response_message
	 */
	public final void setResponse_Message(com.mendix.systemwideinterfaces.core.IContext context, genaicommons.proxies.Message response_message)
	{
		if (response_message == null) {
			getMendixObject().setValue(context, MemberNames.Response_Message.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Response_Message.toString(), response_message.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return responseMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final genaicommons.proxies.Response that = (genaicommons.proxies.Response) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
