// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package genaicommons.proxies.constants;

import com.mendix.core.Core;

public final class Constants
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Constants() {}

	// These are the constants for the GenAICommons module

	/**
	* This controls whether Usage data is stored in the operations that follow the principles of GenAI Commons. Currently only chat completions and embeddings support token usage storage.
	*/
	public static boolean getStoreUsageMetrics()
	{
		return (java.lang.Boolean)Core.getConfiguration().getConstantValue("GenAICommons.StoreUsageMetrics");
	}

	/**
	* Controls the cleanup interval in days for the Usage data. If a positive value is set, Usage records are kept for the specified amount of days (UTC), older records are deleted in ScE_Usage_Cleanup, if enabled for the environment in the Mendix Cloud portal.
	* If this constant is set to empty, zero or a negative value, nothing will be deleted.
	*/
	public static java.lang.Long getUsage_CleanUpAfterDays()
	{
		return (java.lang.Long)Core.getConfiguration().getConstantValue("GenAICommons.Usage_CleanUpAfterDays");
	}
}