// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mxgenaiconnector.actions;

import static java.util.Objects.requireNonNull;
import com.mendix.systemwideinterfaces.core.IContext;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ArrayNode;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.mendix.systemwideinterfaces.core.UserAction;
import mxgenaiconnector.impl.MxLogger;

public class CohereEmbedResponse_ModifyJson extends UserAction<java.lang.String>
{
	private final java.lang.String ResponseBody_ToBeModified;

	public CohereEmbedResponse_ModifyJson(
		IContext context,
		java.lang.String _responseBody_ToBeModified
	)
	{
		super(context);
		this.ResponseBody_ToBeModified = _responseBody_ToBeModified;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		// Import necessary packages


		try {
			requireNonNull(this.ResponseBody_ToBeModified, "ResponseBody String is required");
        // Initialize ObjectMapper with full response body as received from Cohere Embed
			ObjectMapper mapper = new ObjectMapper();
			ObjectNode root = (ObjectNode) mapper.readTree(ResponseBody_ToBeModified);
			
			if (isRootEmpty(root)) {
				LOGGER.warn("Root node is empty or does not contain required fields.");
				return null;
			}

			// Create output JSON object
			ObjectNode outputNode = mapper.createObjectNode();
			outputNode.set("id", root.get("id"));
			outputNode.set("response_type", root.get("response_type"));

			// Create the embeddings array for the output
			ArrayNode outputEmbeddingsArray = mapper.createArrayNode();

			// Get input embeddings - handle both direct array and nested object formats
			JsonNode embeddingsNode = root.get("embeddings");
			ArrayNode inputEmbeddingsArray;
			
			if (embeddingsNode.isArray()) {
				// Case 1: embeddings is a direct array
				inputEmbeddingsArray = (ArrayNode) embeddingsNode;
			} else if (embeddingsNode.isObject() && embeddingsNode.has("float")) {
				// Case 2: embeddings is an object with a "float" key containing the array
				inputEmbeddingsArray = (ArrayNode) embeddingsNode.get("float");
			} else {
				LOGGER.warn("Embeddings format not recognized.");
				return null;
			}
			

			// Iterate over the embeddings and texts
			for (JsonNode embeddingArray : inputEmbeddingsArray) {
				ObjectNode embeddingObject = mapper.createObjectNode();

				// Convert embedding array to string
				String embeddingString = (embeddingArray != null ? mapper.writeValueAsString(embeddingArray) : "");

				// Populate the embedding object with vector and index
				embeddingObject.put("vector", embeddingString);
				embeddingObject.put("_index", outputEmbeddingsArray.size());

				// Add the object to the output array
				outputEmbeddingsArray.add(embeddingObject);
			}

			// Add embeddings array to output
			outputNode.set("embeddings", outputEmbeddingsArray);

			return mapper.writeValueAsString(outputNode);

		} catch (Exception e) {
				throw e;
			}

		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "CohereEmbedResponse_ModifyJson";
	}

	// BEGIN EXTRA CODE

	private static final MxLogger LOGGER = new MxLogger(CohereEmbedResponse_ModifyJson.class);

	private boolean isRootEmpty(ObjectNode root) {
		if (root == null || !root.hasNonNull("id") || !root.hasNonNull("response_type") ||
		    !root.hasNonNull("texts") || !root.hasNonNull("embeddings") ||
		    !root.get("texts").isArray() || ((ArrayNode) root.get("texts")).size() == 0) {
			return true;
		}
		
		// Check embeddings format - either direct array or object with "float" key
		JsonNode embeddingsNode = root.get("embeddings");
		if (embeddingsNode.isArray()) {
			return ((ArrayNode) embeddingsNode).size() == 0;
		} else if (embeddingsNode.isObject() && embeddingsNode.has("float")) {
			JsonNode floatArray = embeddingsNode.get("float");
			return !floatArray.isArray() || ((ArrayNode) floatArray).size() == 0;
		}
		
		return true; // Unrecognized embeddings format
	}

	// END EXTRA CODE
}
