// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mxgenaiconnector.actions;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.meta.IMetaObject;
import com.mendix.systemwideinterfaces.core.UserAction;
import genaicommons.proxies.KnowledgeBaseChunk;
import mxgenaiconnector.impl.ChunkUtils;
import mxgenaiconnector.impl.MxLogger;

/**
 * Use this operation to retrieve chunks from a collection. The retrieval is based on similarity with respect to the input query string (Content) provided.  This operation returns a list of KnowledgeBaseChunk. The returned list is sorted on vector similarity which is handled internally.
 * Additional filtering can be done by specifying the optional input parameters.
 * 
 * The TargetChunk entity (type parameter) must be a specialization of the KnowledgeBaseChunk entity from the GenAICommons. If it contains associations to (specializations of) the related mendix object for which the chunk was created originally, this will be set by this operation for easy processing afterwards.
 * 
 * Previously inserted or changed chunks are only available in the knowledge base after 60-120 seconds due to asynchronous data synchronization for better scalability.
 */
public class KnowledgeBaseChunkList_Embed_RetrieveNearestNeighbors_SetAssociation extends UserAction<java.util.List<IMendixObject>>
{
	/** @deprecated use DeployedKnowledgeBase.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __DeployedKnowledgeBase;
	private final genaicommons.proxies.DeployedKnowledgeBase DeployedKnowledgeBase;
	private final java.lang.String TargetChunk;
	private final java.lang.String Content;
	/** @deprecated use MetadataCollection.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __MetadataCollection;
	private final genaicommons.proxies.MetadataCollection MetadataCollection;
	private final java.lang.Long MaxNumberOfResults;
	private final java.math.BigDecimal MinimumSimilarity;

	public KnowledgeBaseChunkList_Embed_RetrieveNearestNeighbors_SetAssociation(
		IContext context,
		IMendixObject _deployedKnowledgeBase,
		java.lang.String _targetChunk,
		java.lang.String _content,
		IMendixObject _metadataCollection,
		java.lang.Long _maxNumberOfResults,
		java.math.BigDecimal _minimumSimilarity
	)
	{
		super(context);
		this.__DeployedKnowledgeBase = _deployedKnowledgeBase;
		this.DeployedKnowledgeBase = _deployedKnowledgeBase == null ? null : genaicommons.proxies.DeployedKnowledgeBase.initialize(getContext(), _deployedKnowledgeBase);
		this.TargetChunk = _targetChunk;
		this.Content = _content;
		this.__MetadataCollection = _metadataCollection;
		this.MetadataCollection = _metadataCollection == null ? null : genaicommons.proxies.MetadataCollection.initialize(getContext(), _metadataCollection);
		this.MaxNumberOfResults = _maxNumberOfResults;
		this.MinimumSimilarity = _minimumSimilarity;
	}

	@java.lang.Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		// BEGIN USER CODE
		
		try { 
			IMetaObject targetChunk = Core.getMetaObject(TargetChunk);
			ChunkUtils.validateTargetChunk(targetChunk);
			
			// call a microflow to retrieve chunks
			java.util.List<KnowledgeBaseChunk> chunkList = mxgenaiconnector.proxies.microflows.Microflows.knowledgeBaseChunkList_Embed_RetrieveNearestNeighbors(
					getContext(), Content, MinimumSimilarity, MaxNumberOfResults, DeployedKnowledgeBase, MetadataCollection);
			
			//map to target chunks to return
			return ChunkUtils.getTargetChunkList(getContext(), chunkList, targetChunk);
			
		} catch (Exception e) {
			LOGGER.error(e, "Retrieve nearest neighbor and set association was not successful.");
			return null;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "KnowledgeBaseChunkList_Embed_RetrieveNearestNeighbors_SetAssociation";
	}

	// BEGIN EXTRA CODE
	private static final MxLogger LOGGER = new MxLogger(KnowledgeBaseChunkList_Embed_RetrieveNearestNeighbors_SetAssociation.class);
	// END EXTRA CODE
}
