// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mxgenaiconnector.actions;

import java.util.ArrayList;
import java.util.stream.Collectors;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;
import genaicommons.proxies.KnowledgeBaseChunk;
import mxgenaiconnector.impl.ChunkUtils;
import mxgenaiconnector.impl.MxLogger;

/**
 * Use this operation to retrieve chunks from a collection. This operation returns a list of KnowledgeBaseChunks.
 * 
 * Additional selection and filtering can be done by specifying the optional input parameters.
 * 
 * Previously inserted or changed chunks are only available in the knowledge base after 60-120 seconds due to asynchronous data synchronization for better scalability.
 */
public class KnowledgeBaseChunkList_Retrieve extends UserAction<java.util.List<IMendixObject>>
{
	/** @deprecated use DeployedKnowledgeBase.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __DeployedKnowledgeBase;
	private final genaicommons.proxies.DeployedKnowledgeBase DeployedKnowledgeBase;
	private final IMendixObject MxObject;
	/** @deprecated use MetadataCollection.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __MetadataCollection;
	private final genaicommons.proxies.MetadataCollection MetadataCollection;
	private final java.lang.Long MaxNumberOfResults;
	private final java.lang.Long Offset;

	public KnowledgeBaseChunkList_Retrieve(
		IContext context,
		IMendixObject _deployedKnowledgeBase,
		IMendixObject _mxObject,
		IMendixObject _metadataCollection,
		java.lang.Long _maxNumberOfResults,
		java.lang.Long _offset
	)
	{
		super(context);
		this.__DeployedKnowledgeBase = _deployedKnowledgeBase;
		this.DeployedKnowledgeBase = _deployedKnowledgeBase == null ? null : genaicommons.proxies.DeployedKnowledgeBase.initialize(getContext(), _deployedKnowledgeBase);
		this.MxObject = _mxObject;
		this.__MetadataCollection = _metadataCollection;
		this.MetadataCollection = _metadataCollection == null ? null : genaicommons.proxies.MetadataCollection.initialize(getContext(), _metadataCollection);
		this.MaxNumberOfResults = _maxNumberOfResults;
		this.Offset = _offset;
	}

	@java.lang.Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		// BEGIN USER CODE
		try {
			java.util.List<KnowledgeBaseChunk> chunkList = new ArrayList<>();
			if (MxObject == null) {
				LOGGER.trace("No MxObject was passed, retrieve will be executed without MendixIDs specified");
			}
			else {
				ChunkUtils.addChunkWithMxObjectID(getContext(), MxObject, chunkList);
			}
			java.util.List<KnowledgeBaseChunk> knowledgeBaseChunkList = mxgenaiconnector.proxies.microflows.Microflows.knowledgeBaseChunkList_Retrieve(getContext(), MetadataCollection, MaxNumberOfResults, DeployedKnowledgeBase, chunkList, Offset);
			java.util.List<IMendixObject> returnList = knowledgeBaseChunkList.stream().map(o -> o.getMendixObject()).collect(Collectors.toList());
			return returnList;
		} catch (Error e) {
			LOGGER.error(e, "Retrieve was not successful.");
			return null;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "KnowledgeBaseChunkList_Retrieve";
	}

	// BEGIN EXTRA CODE
	private static final MxLogger LOGGER = new MxLogger(KnowledgeBaseChunkList_Retrieve.class);
	// END EXTRA CODE
}
