// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mxgenaiconnector.actions;

import java.util.ArrayList;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;
import genaicommons.proxies.KnowledgeBaseChunk;
import mxgenaiconnector.impl.ChunkUtils;
import mxgenaiconnector.impl.MxLogger;
import mxgenaiconnector.proxies.Collection;

/**
 * Use this operation to delete existing chunks in a collection based on the MxObjectID. 
 * MxObjectList is the list of (original) Mendix objects that the chunks in the knowledge base represent. Only chunks related to these Mendix objects are to be deleted.
 * 
 * Once deleted, chunks are no longer available for read operations in the KB after 60-120 seconds due to asynchronous data synchronization for better scalability.
 */
public class KnowledgeBaseChunkList_Delete_ByMxObjectList extends UserAction<java.lang.Boolean>
{
	/** @deprecated use DeployedKnowledgeBase.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __DeployedKnowledgeBase;
	private final genaicommons.proxies.DeployedKnowledgeBase DeployedKnowledgeBase;
	private final java.util.List<IMendixObject> MxObjectList;

	public KnowledgeBaseChunkList_Delete_ByMxObjectList(
		IContext context,
		IMendixObject _deployedKnowledgeBase,
		java.util.List<IMendixObject> _mxObjectList
	)
	{
		super(context);
		this.__DeployedKnowledgeBase = _deployedKnowledgeBase;
		this.DeployedKnowledgeBase = _deployedKnowledgeBase == null ? null : genaicommons.proxies.DeployedKnowledgeBase.initialize(getContext(), _deployedKnowledgeBase);
		this.MxObjectList = _mxObjectList;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		try {
			if (MxObjectList.isEmpty()) {
				LOGGER.warn("Empty list was passed, nothing was deleted");
			}
			java.util.List<KnowledgeBaseChunk> chunkList = new ArrayList<>();
			MxObjectList.forEach(o -> ChunkUtils.addChunkWithMxObjectID(getContext(), o, chunkList));
			return mxgenaiconnector.proxies.microflows.Microflows.knowledgeBaseChunkList_Delete_FromKnowledgeBase(getContext(), chunkList, Collection.initialize(getContext(), DeployedKnowledgeBase.getMendixObject()));
		} catch (Error e) {
			LOGGER.error(e, "Delete list was not successful.");
			return false;
		}
		
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "KnowledgeBaseChunkList_Delete_ByMxObjectList";
	}

	// BEGIN EXTRA CODE
	private static final MxLogger LOGGER = new MxLogger(KnowledgeBaseChunkList_Delete_ByMxObjectList.class);
	// END EXTRA CODE
}
