// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mxgenaiconnector.actions;

import static java.util.Objects.requireNonNull;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ArrayNode;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IDataType;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;
import genaicommons.impl.FunctionImpl;
import genaicommons.impl.FunctionMappingImpl;
import genaicommons.impl.MessageImpl;
import genaicommons.proxies.ArgumentInput;
import genaicommons.proxies.ENUM_MessageRole;
import genaicommons.proxies.Message;
import genaicommons.proxies.Tool;
import genaicommons.proxies.ToolCall;
import mxgenaiconnector.impl.ConverseVisionDocument;
import mxgenaiconnector.impl.ConverseFunctionCalling;
import mxgenaiconnector.impl.MxLogger;

public class Request_Modify_Converse extends UserAction<java.lang.String>
{
	/** @deprecated use Request.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __Request;
	private final genaicommons.proxies.Request Request;
	private final java.lang.String RequestBodyJSON;

	public Request_Modify_Converse(
		IContext context,
		IMendixObject _request,
		java.lang.String _requestBodyJSON
	)
	{
		super(context);
		this.__Request = _request;
		this.Request = _request == null ? null : genaicommons.proxies.Request.initialize(getContext(), _request);
		this.RequestBodyJSON = _requestBodyJSON;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		try {
			requireNonNull(this.RequestBodyJSON, "RequestBody JSON is required");
			requireNonNull(this.Request, "Request object is required");
			ObjectNode rootNode = (ObjectNode) MAPPER.readTree(RequestBodyJSON);
			
			//System prompt node needs to be removed if empty
			removeSystemPromptIfEmpty(rootNode);
			//Add image for vision or ToolResults/ToolUse for function calling
			updateMessages(rootNode);
			//ToolConfig describes the available functions/tools to the model
			addToolConfig(rootNode);
			
			return MAPPER.writeValueAsString(rootNode);

		} catch (Exception e) {
			throw e;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Request_Modify_Converse";
	}

	// BEGIN EXTRA CODE
	private static final ObjectMapper MAPPER = new ObjectMapper();
	
	private static final MxLogger LOGGER = new MxLogger(Request_Modify_Converse.class);
	
	
	private void updateMessages(ObjectNode rootNode)throws Exception {
		ArrayNode messagesNode = (ArrayNode) rootNode.path("messages");
		
		for (int i = 0; i < messagesNode.size(); i++) {
			//Map "tool" messages to Converse ToolResult
			ConverseFunctionCalling.mapToolResult(messagesNode, i, getContext(), Request);
			
            //If a fileCollection has been added, add a new Converse ContentBlock
            ConverseVisionDocument.mapFileCollection(messagesNode, i);
        }
		//Update messages of rootNode
		rootNode.set("messages", messagesNode);
	}
	
	

	//Removes system prompt node if empty (system prompt is not required, but can't be null)
	private void removeSystemPromptIfEmpty(ObjectNode rootNode) {
		if (rootNode.has("system")) {
            JsonNode systemNode = rootNode.get("system").get(0);
            if (systemNode != null && systemNode.size() == 0 || (systemNode.get("text") != null && systemNode.get("text").asText().isBlank())) {
                rootNode.remove("system");
            }
		}
	}
	//........Add ToolConfig to Request........
	//Creates toolConfig node
		private void addToolConfig(ObjectNode rootNode) throws CoreException {
			if(rootNode == null || (rootNode.path("toolConfig").asText().isBlank() && rootNode.path("toolConfig").path("tools").size() == 0)) {
				//If there is no ToolCollection (toolConfig), this needs to be removed
				rootNode.remove("toolConfig");
				return;
			}
			
			ArrayNode toolsNode = (ArrayNode) rootNode.path("toolConfig").path("tools");
			for (int i = 0; i < toolsNode.size(); i++) {
				JsonNode toolNode = toolsNode.get(i);
				String microflow = toolNode.path("microflow").asText();
				if (microflow.isBlank() == false) {
					ObjectNode toolNodeObject = (ObjectNode) toolNode;
					setInputSchemaForToolNode(microflow,toolNodeObject);
					
					//Add toolSpec node around tool
					ObjectNode toolSpecNode = MAPPER.createObjectNode();
					toolSpecNode.set("toolSpec",toolNode);
					//Existing node is replaced by new toolSpec node.
					toolsNode.set(i,toolSpecNode);
					
					//Remove functionMicrofow node which is not part of the Converse request
					((ObjectNode) toolNode).remove("microflow");
				}
			}
			
			setToolChoice(rootNode);
		}
		
		//This will create the input schema JSON needed for specifying the input of a tool
		private void setInputSchemaForToolNode(String microflow, ObjectNode toolNode) throws CoreException {
			
			// Create the root object node
	        ObjectNode inputSchemaNode = MAPPER.createObjectNode();
	        inputSchemaNode.put("type", "object");

	        // Create the properties node (if input parameter is available)
			ObjectNode propertiesNode = MAPPER.createObjectNode();
			ArrayNode requiredNode = MAPPER.createArrayNode();
	        
			// Add properties (either from microflow or if arguments are present based on those
			Tool tool = FunctionImpl.getToolByName(Request, toolNode.get("name").asText() ,getContext());
			List<ArgumentInput> arguments = tool.getTool_ArgumentInput();
			if (arguments == null || arguments.isEmpty()) {
				Map<String, IDataType> parameterList = FunctionMappingImpl.getInputParametersForModel(microflow);
				parameterList.entrySet().forEach(t -> FunctionImpl.addProperty(propertiesNode, requiredNode, t));
				
			}else {
				FunctionImpl.addPropertiesForTool(tool.getTool_ArgumentInput(), propertiesNode, requiredNode);
			}
		        
	        inputSchemaNode.set("properties", propertiesNode);
	        inputSchemaNode.set("required", requiredNode);
	        // Add a "json" wrapper around the inputSchema
	        ObjectNode jsonNode = MAPPER.createObjectNode();
	        jsonNode.set("json", inputSchemaNode);
	        
	        // Set the whole InputSchema as new node to toolNode
	        toolNode.set("inputSchema",jsonNode);
		}
		
		private void setToolChoice(ObjectNode rootNode) {
			JsonNode toolConfig = rootNode.path("toolConfig");
			if(toolConfig.isEmpty()) {
				return;
			}
			JsonNode toolChoiceNode = toolConfig.path("toolChoice");
			
			if(toolChoiceNode.isEmpty()) {
				((ObjectNode) toolConfig).remove("toolChoice");
				return;
			}
	
            String toolType = toolChoiceNode.has("toolChoiceType") ? toolChoiceNode.path("toolChoiceType").asText() : "";
            switch (toolType) {
            	//"tool" choice can only be used once for the same function to prevent infinity loops
                case "tool":
                	JsonNode toolNode = toolChoiceNode.get("tool");
                	if(!toolNode.isEmpty() && isToolRecall(toolNode.path("name").asText())) {
                		((ObjectNode) toolConfig).remove("toolChoice");
                	}
                    break;
                
                //"any" choice can only be used once at the first iteration to prevent infinity loops
                case "any":
                	if(FunctionMappingImpl.getToolCallMessages(Request,getContext()).size() == 0) {
                		ObjectNode wrapper = MAPPER.createObjectNode();
	                    wrapper.set(toolType, MAPPER.createObjectNode());
	                    ((ObjectNode) toolConfig).set("toolChoice", wrapper);
                	}
                	else {
                		((ObjectNode) toolConfig).remove("toolChoice");
                	}
                	break;
                //"auto" is the default
   	            case "auto":
   	            	ObjectNode wrapper = MAPPER.createObjectNode();
                    wrapper.set(toolType, MAPPER.createObjectNode());
                    ((ObjectNode) toolConfig).set("toolChoice", wrapper);
                    break;

                default:
                    LOGGER.warn(("Unknown or missing type for ToolChoice: " + toolType));
                    break;
            }
            ((ObjectNode) toolChoiceNode).remove("toolChoiceType");
	        
			
		}
		
		private boolean isToolRecall(String toolChoiceFunctionName) {
			List<genaicommons.proxies.Message> messageListTool = FunctionMappingImpl.getToolCallMessages(Request,getContext());

			// No tool calls yet; thus no tool recall
			if (messageListTool.size() == 0) {
				return false;
			}

			// Get all messages with role assistant
			// Assistant messages optionally have an array of tool_calls that contain an id and the functionName
			List<Message> messageListAssistant = MessageImpl
					.retrieveMessageListByRole(Request, ENUM_MessageRole.assistant, getContext());

			// HashMap with ToolCall._id and ToolCallFunction.Name created from the messageListAssistant
			// The map contains only those tool calls, where functionName equals the toolChoiceFunctionName
			Map<String, String> toolChoiceToolCallMap = new HashMap<>();

			for (Message message : messageListAssistant) {

				// Get ToolCall list for each assistant message where the function name equals
				// the function name from the tool choice (toolChoiceFunctionName)
				List<ToolCall> toolCallList = Core.retrieveByPath(getContext(), message.getMendixObject(),
								Message.MemberNames.Message_ToolCall.toString())
						.stream()
						.filter(mxObject -> {
							return filterToolCallByFunctionName(toolChoiceFunctionName, mxObject);
						})
						.map(mxObject -> ToolCall.initialize(getContext(), mxObject))
						.collect(Collectors.toList());

				// Loop over toolCallList and add _id and functionName to a HashMap
				for (ToolCall toolCall : toolCallList) {
					String toolCallId = toolCall.getToolCallId();
					String toolName = toolCall.getName();
					toolChoiceToolCallMap.put(toolCallId, toolName);
				}
			}

			// Loop over Tool messages and compare ToolCallId with Ids from Assistant
			// messages in HashMap to see whether the function from the Tool Choice has
			// already been called
			for (Message messageTool : messageListTool) {
				String toolId = messageTool.getToolCallId();
				if (toolChoiceToolCallMap.containsKey(toolId)) {
					return true;
				}
			}
			return false;
		}
		
		private boolean filterToolCallByFunctionName(String toolChoiceFunctionName, IMendixObject mxObject) {
			String functionName = "";
			functionName = ToolCall.initialize(getContext(), mxObject).getName();
			// Return true if the functionName equals toolChoiceFunctionName
			return functionName.equals(toolChoiceFunctionName);
		}
	// END EXTRA CODE
}
