// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mxgenaiconnector.actions;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.node.ArrayNode;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.UserAction;
import static java.util.Objects.requireNonNull;
import java.util.Iterator;
import java.util.Map;

public class Response_ModifyForMapping_Converse extends UserAction<java.lang.String>
{
	private final java.lang.String ResponseJSON;

	public Response_ModifyForMapping_Converse(
		IContext context,
		java.lang.String _responseJSON
	)
	{
		super(context);
		this.ResponseJSON = _responseJSON;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		try {
			requireNonNull(this.ResponseJSON, "Response JSON is required");
			ObjectNode rootNode = (ObjectNode) MAPPER.readTree(ResponseJSON);
			
			//Prepare JSON for Mendix ToolUse Objects (map the arguments)
			normalizeMessage(rootNode);
				
			return MAPPER.writeValueAsString(rootNode);

		} catch (Exception e) {
			throw e;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Response_ModifyForMapping_Converse";
	}

	// BEGIN EXTRA CODE
	private static final ObjectMapper MAPPER = new ObjectMapper();
	
	//Prepare for mapping to GenAI Commons structure
	private void normalizeMessage(ObjectNode rootNode) {
	    JsonNode contentArray = rootNode.path("output").path("message").path("content");
	    if (!contentArray.isArray()) return;

	    ObjectNode messageNode = (ObjectNode) rootNode.path("output").path("message");

	    // Collect text and tool calls
	    String text = null;
	    ArrayNode toolCallsArray = MAPPER.createArrayNode();

	    for (JsonNode contentNode : contentArray) {
	        // Extract first non-null text
	        if (text == null && contentNode.has("text") && !contentNode.get("text").isNull()) {
	            text = contentNode.get("text").asText();
	        }

	        // Extract toolUse and create GenAICommons-mappable nodes
	        JsonNode toolUseNode = contentNode.path("toolUse");
	        if (toolUseNode != null && toolUseNode.isObject()) {
	            ObjectNode toolCall = toolUseNode.deepCopy();
	            mapToolUse(toolCall);
	            toolCallsArray.add(toolCall);
	        }
	    }

	    // Replace "content" node
	    messageNode.remove("content");
	    if (text != null) {
	        messageNode.put("text", text);
	    }
	    if (toolCallsArray.size() > 0) {
	        messageNode.set("toolCalls", toolCallsArray);
	    }
	}
	
	private void mapToolUse(ObjectNode toolUseNode) {
	    // Replace "input" with key and value attributes
	    JsonNode inputNode = toolUseNode.remove("input");
	    ArrayNode argumentsArray = MAPPER.createArrayNode();

	    if (inputNode != null && inputNode.isObject()) {
	        Iterator<Map.Entry<String, JsonNode>> fields = inputNode.fields();
	        while (fields.hasNext()) {
	            Map.Entry<String, JsonNode> field = fields.next();
	            ObjectNode keyValueNode = MAPPER.createObjectNode();
	            keyValueNode.put("key", field.getKey());
	            keyValueNode.set("value", field.getValue());
	            argumentsArray.add(keyValueNode);
	        }
	    }

	    toolUseNode.set("arguments", argumentsArray);
	}
	
	// END EXTRA CODE
}
