// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mxgenaiconnector.proxies;

/**
 * This entity stores the connectivity information for a MxCloud deployed model or knowledge base resource.
 * It contains the location URL and the credentials, as well as metadata about the key. 
 */
public class Configuration implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject configurationMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MxGenAIConnector.Configuration";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Environment("Environment"),
		KeyName("KeyName");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Configuration(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Configuration(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject configurationMendixObject)
	{
		if (configurationMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, configurationMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.configurationMendixObject = configurationMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static mxgenaiconnector.proxies.Configuration initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new mxgenaiconnector.proxies.Configuration(context, mendixObject);
	}

	public static mxgenaiconnector.proxies.Configuration load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return mxgenaiconnector.proxies.Configuration.initialize(context, mendixObject);
	}

	public static java.util.List<mxgenaiconnector.proxies.Configuration> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> mxgenaiconnector.proxies.Configuration.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of Environment
	 */
	public final java.lang.String getEnvironment()
	{
		return getEnvironment(getContext());
	}

	/**
	 * @param context
	 * @return value of Environment
	 */
	public final java.lang.String getEnvironment(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Environment.toString());
	}

	/**
	 * Set value of Environment
	 * @param environment
	 */
	public final void setEnvironment(java.lang.String environment)
	{
		setEnvironment(getContext(), environment);
	}

	/**
	 * Set value of Environment
	 * @param context
	 * @param environment
	 */
	public final void setEnvironment(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String environment)
	{
		getMendixObject().setValue(context, MemberNames.Environment.toString(), environment);
	}

	/**
	 * @return value of KeyName
	 */
	public final java.lang.String getKeyName()
	{
		return getKeyName(getContext());
	}

	/**
	 * @param context
	 * @return value of KeyName
	 */
	public final java.lang.String getKeyName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.KeyName.toString());
	}

	/**
	 * Set value of KeyName
	 * @param keyname
	 */
	public final void setKeyName(java.lang.String keyname)
	{
		setKeyName(getContext(), keyname);
	}

	/**
	 * Set value of KeyName
	 * @param context
	 * @param keyname
	 */
	public final void setKeyName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String keyname)
	{
		getMendixObject().setValue(context, MemberNames.KeyName.toString(), keyname);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return configurationMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final mxgenaiconnector.proxies.Configuration that = (mxgenaiconnector.proxies.Configuration) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
