// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mxgenaiconnector.proxies;

/**
 * This represents a deployment of a GenAI model. An instance of this entity is created automatically upon importing a key from the Mendix Portal.
 * It contains model-specific information that is required for the execution of a call to the language model. Both text generation and embedding models can be represented by this entity.
 * The details for the connectionn are stored in the associatied configuration entity, which is also automatically created at the same time (upon importing a key from the Mendix portal).
 */
public class MxCloudDeployedModel extends genaicommons.proxies.DeployedModel
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MxGenAIConnector.MxCloudDeployedModel";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		DisplayName("DisplayName"),
		Architecture("Architecture"),
		Model("Model"),
		OutputModality("OutputModality"),
		Microflow("Microflow"),
		SupportsSystemPrompt("SupportsSystemPrompt"),
		SupportsConversationsWithHistory("SupportsConversationsWithHistory"),
		SupportsFunctionCalling("SupportsFunctionCalling"),
		IsActive("IsActive"),
		MxCloudDeployedModel_Configuration("MxGenAIConnector.MxCloudDeployedModel_Configuration"),
		DeployedModel_InputModality("GenAICommons.DeployedModel_InputModality");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public MxCloudDeployedModel(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected MxCloudDeployedModel(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mxCloudDeployedModelMendixObject)
	{
		super(context, mxCloudDeployedModelMendixObject);
		if (!com.mendix.core.Core.isSubClassOf(entityName, mxCloudDeployedModelMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static mxgenaiconnector.proxies.MxCloudDeployedModel initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new mxgenaiconnector.proxies.MxCloudDeployedModel(context, mendixObject);
	}

	public static mxgenaiconnector.proxies.MxCloudDeployedModel load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return mxgenaiconnector.proxies.MxCloudDeployedModel.initialize(context, mendixObject);
	}

	public static java.util.List<mxgenaiconnector.proxies.MxCloudDeployedModel> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> mxgenaiconnector.proxies.MxCloudDeployedModel.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of MxCloudDeployedModel_Configuration
	 */
	public final mxgenaiconnector.proxies.Configuration getMxCloudDeployedModel_Configuration() throws com.mendix.core.CoreException
	{
		return getMxCloudDeployedModel_Configuration(getContext());
	}

	/**
	 * @param context
	 * @return value of MxCloudDeployedModel_Configuration
	 * @throws com.mendix.core.CoreException
	 */
	public final mxgenaiconnector.proxies.Configuration getMxCloudDeployedModel_Configuration(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		mxgenaiconnector.proxies.Configuration result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.MxCloudDeployedModel_Configuration.toString());
		if (identifier != null) {
			result = mxgenaiconnector.proxies.Configuration.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of MxCloudDeployedModel_Configuration
	 * @param mxclouddeployedmodel_configuration
	 */
	public final void setMxCloudDeployedModel_Configuration(mxgenaiconnector.proxies.Configuration mxclouddeployedmodel_configuration)
	{
		setMxCloudDeployedModel_Configuration(getContext(), mxclouddeployedmodel_configuration);
	}

	/**
	 * Set value of MxCloudDeployedModel_Configuration
	 * @param context
	 * @param mxclouddeployedmodel_configuration
	 */
	public final void setMxCloudDeployedModel_Configuration(com.mendix.systemwideinterfaces.core.IContext context, mxgenaiconnector.proxies.Configuration mxclouddeployedmodel_configuration)
	{
		if (mxclouddeployedmodel_configuration == null) {
			getMendixObject().setValue(context, MemberNames.MxCloudDeployedModel_Configuration.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.MxCloudDeployedModel_Configuration.toString(), mxclouddeployedmodel_configuration.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final mxgenaiconnector.proxies.MxCloudDeployedModel that = (mxgenaiconnector.proxies.MxCloudDeployedModel) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
