// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mxgenaiconnector.proxies;

/**
 * This represents a knowledge base resource that is available in the Mendix cloud. An instance of this entity is created automatically upon importing a key from the Mendix Portal.
 * It contains knowledge base specific information that is needed to insert and retrieve data (knowledge base chunks). 
 * Within a knowledge base resource, one or more separate collections of data exist, to support multiple use cases in parallel without mixing up data.
 * 
 * The details for the connectionn are stored in the associatied configuration entity, which is also automatically created at the same time (upon importing a key from the Mendix portal).
 */
public class MxCloudKnowledgeBase implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject mxCloudKnowledgeBaseMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MxGenAIConnector.MxCloudKnowledgeBase";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		DisplayName("DisplayName"),
		MxCloudKnowledgeBase_MxCloudDeployedModel("MxGenAIConnector.MxCloudKnowledgeBase_MxCloudDeployedModel"),
		MxCloudKnowledgeBase_Configuration("MxGenAIConnector.MxCloudKnowledgeBase_Configuration");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public MxCloudKnowledgeBase(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected MxCloudKnowledgeBase(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mxCloudKnowledgeBaseMendixObject)
	{
		if (mxCloudKnowledgeBaseMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, mxCloudKnowledgeBaseMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.mxCloudKnowledgeBaseMendixObject = mxCloudKnowledgeBaseMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static mxgenaiconnector.proxies.MxCloudKnowledgeBase initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new mxgenaiconnector.proxies.MxCloudKnowledgeBase(context, mendixObject);
	}

	public static mxgenaiconnector.proxies.MxCloudKnowledgeBase load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return mxgenaiconnector.proxies.MxCloudKnowledgeBase.initialize(context, mendixObject);
	}

	public static java.util.List<mxgenaiconnector.proxies.MxCloudKnowledgeBase> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> mxgenaiconnector.proxies.MxCloudKnowledgeBase.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of DisplayName
	 */
	public final java.lang.String getDisplayName()
	{
		return getDisplayName(getContext());
	}

	/**
	 * @param context
	 * @return value of DisplayName
	 */
	public final java.lang.String getDisplayName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DisplayName.toString());
	}

	/**
	 * Set value of DisplayName
	 * @param displayname
	 */
	public final void setDisplayName(java.lang.String displayname)
	{
		setDisplayName(getContext(), displayname);
	}

	/**
	 * Set value of DisplayName
	 * @param context
	 * @param displayname
	 */
	public final void setDisplayName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String displayname)
	{
		getMendixObject().setValue(context, MemberNames.DisplayName.toString(), displayname);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of MxCloudKnowledgeBase_MxCloudDeployedModel
	 */
	public final mxgenaiconnector.proxies.MxCloudDeployedModel getMxCloudKnowledgeBase_MxCloudDeployedModel() throws com.mendix.core.CoreException
	{
		return getMxCloudKnowledgeBase_MxCloudDeployedModel(getContext());
	}

	/**
	 * @param context
	 * @return value of MxCloudKnowledgeBase_MxCloudDeployedModel
	 * @throws com.mendix.core.CoreException
	 */
	public final mxgenaiconnector.proxies.MxCloudDeployedModel getMxCloudKnowledgeBase_MxCloudDeployedModel(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		mxgenaiconnector.proxies.MxCloudDeployedModel result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.MxCloudKnowledgeBase_MxCloudDeployedModel.toString());
		if (identifier != null) {
			result = mxgenaiconnector.proxies.MxCloudDeployedModel.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of MxCloudKnowledgeBase_MxCloudDeployedModel
	 * @param mxcloudknowledgebase_mxclouddeployedmodel
	 */
	public final void setMxCloudKnowledgeBase_MxCloudDeployedModel(mxgenaiconnector.proxies.MxCloudDeployedModel mxcloudknowledgebase_mxclouddeployedmodel)
	{
		setMxCloudKnowledgeBase_MxCloudDeployedModel(getContext(), mxcloudknowledgebase_mxclouddeployedmodel);
	}

	/**
	 * Set value of MxCloudKnowledgeBase_MxCloudDeployedModel
	 * @param context
	 * @param mxcloudknowledgebase_mxclouddeployedmodel
	 */
	public final void setMxCloudKnowledgeBase_MxCloudDeployedModel(com.mendix.systemwideinterfaces.core.IContext context, mxgenaiconnector.proxies.MxCloudDeployedModel mxcloudknowledgebase_mxclouddeployedmodel)
	{
		if (mxcloudknowledgebase_mxclouddeployedmodel == null) {
			getMendixObject().setValue(context, MemberNames.MxCloudKnowledgeBase_MxCloudDeployedModel.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.MxCloudKnowledgeBase_MxCloudDeployedModel.toString(), mxcloudknowledgebase_mxclouddeployedmodel.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of MxCloudKnowledgeBase_Configuration
	 */
	public final mxgenaiconnector.proxies.Configuration getMxCloudKnowledgeBase_Configuration() throws com.mendix.core.CoreException
	{
		return getMxCloudKnowledgeBase_Configuration(getContext());
	}

	/**
	 * @param context
	 * @return value of MxCloudKnowledgeBase_Configuration
	 * @throws com.mendix.core.CoreException
	 */
	public final mxgenaiconnector.proxies.Configuration getMxCloudKnowledgeBase_Configuration(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		mxgenaiconnector.proxies.Configuration result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.MxCloudKnowledgeBase_Configuration.toString());
		if (identifier != null) {
			result = mxgenaiconnector.proxies.Configuration.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of MxCloudKnowledgeBase_Configuration
	 * @param mxcloudknowledgebase_configuration
	 */
	public final void setMxCloudKnowledgeBase_Configuration(mxgenaiconnector.proxies.Configuration mxcloudknowledgebase_configuration)
	{
		setMxCloudKnowledgeBase_Configuration(getContext(), mxcloudknowledgebase_configuration);
	}

	/**
	 * Set value of MxCloudKnowledgeBase_Configuration
	 * @param context
	 * @param mxcloudknowledgebase_configuration
	 */
	public final void setMxCloudKnowledgeBase_Configuration(com.mendix.systemwideinterfaces.core.IContext context, mxgenaiconnector.proxies.Configuration mxcloudknowledgebase_configuration)
	{
		if (mxcloudknowledgebase_configuration == null) {
			getMendixObject().setValue(context, MemberNames.MxCloudKnowledgeBase_Configuration.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.MxCloudKnowledgeBase_Configuration.toString(), mxcloudknowledgebase_configuration.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return mxCloudKnowledgeBaseMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final mxgenaiconnector.proxies.MxCloudKnowledgeBase that = (mxgenaiconnector.proxies.MxCloudKnowledgeBase) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
