// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mxgenaiconnector.proxies;

/**
 * Connection to be used in operations (GenAI Commons compatible). Can be created via MxKnowledgeBaseConnection_Create.
 * Currently only used for knowledge base interactions.
 */
public class MxKnowledgeBaseConnection extends genaicommons.proxies.Connection
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MxGenAIConnector.MxKnowledgeBaseConnection";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		CollectionName("CollectionName"),
		MxKnowledgeBaseConnection_MxCloudKnowledgeBase("MxGenAIConnector.MxKnowledgeBaseConnection_MxCloudKnowledgeBase");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public MxKnowledgeBaseConnection(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected MxKnowledgeBaseConnection(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mxKnowledgeBaseConnectionMendixObject)
	{
		super(context, mxKnowledgeBaseConnectionMendixObject);
		if (!com.mendix.core.Core.isSubClassOf(entityName, mxKnowledgeBaseConnectionMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static mxgenaiconnector.proxies.MxKnowledgeBaseConnection initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new mxgenaiconnector.proxies.MxKnowledgeBaseConnection(context, mendixObject);
	}

	public static mxgenaiconnector.proxies.MxKnowledgeBaseConnection load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return mxgenaiconnector.proxies.MxKnowledgeBaseConnection.initialize(context, mendixObject);
	}

	/**
	 * @return value of CollectionName
	 */
	public final java.lang.String getCollectionName()
	{
		return getCollectionName(getContext());
	}

	/**
	 * @param context
	 * @return value of CollectionName
	 */
	public final java.lang.String getCollectionName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CollectionName.toString());
	}

	/**
	 * Set value of CollectionName
	 * @param collectionname
	 */
	public final void setCollectionName(java.lang.String collectionname)
	{
		setCollectionName(getContext(), collectionname);
	}

	/**
	 * Set value of CollectionName
	 * @param context
	 * @param collectionname
	 */
	public final void setCollectionName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String collectionname)
	{
		getMendixObject().setValue(context, MemberNames.CollectionName.toString(), collectionname);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of MxKnowledgeBaseConnection_MxCloudKnowledgeBase
	 */
	public final mxgenaiconnector.proxies.MxCloudKnowledgeBase getMxKnowledgeBaseConnection_MxCloudKnowledgeBase() throws com.mendix.core.CoreException
	{
		return getMxKnowledgeBaseConnection_MxCloudKnowledgeBase(getContext());
	}

	/**
	 * @param context
	 * @return value of MxKnowledgeBaseConnection_MxCloudKnowledgeBase
	 * @throws com.mendix.core.CoreException
	 */
	public final mxgenaiconnector.proxies.MxCloudKnowledgeBase getMxKnowledgeBaseConnection_MxCloudKnowledgeBase(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		mxgenaiconnector.proxies.MxCloudKnowledgeBase result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.MxKnowledgeBaseConnection_MxCloudKnowledgeBase.toString());
		if (identifier != null) {
			result = mxgenaiconnector.proxies.MxCloudKnowledgeBase.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of MxKnowledgeBaseConnection_MxCloudKnowledgeBase
	 * @param mxknowledgebaseconnection_mxcloudknowledgebase
	 */
	public final void setMxKnowledgeBaseConnection_MxCloudKnowledgeBase(mxgenaiconnector.proxies.MxCloudKnowledgeBase mxknowledgebaseconnection_mxcloudknowledgebase)
	{
		setMxKnowledgeBaseConnection_MxCloudKnowledgeBase(getContext(), mxknowledgebaseconnection_mxcloudknowledgebase);
	}

	/**
	 * Set value of MxKnowledgeBaseConnection_MxCloudKnowledgeBase
	 * @param context
	 * @param mxknowledgebaseconnection_mxcloudknowledgebase
	 */
	public final void setMxKnowledgeBaseConnection_MxCloudKnowledgeBase(com.mendix.systemwideinterfaces.core.IContext context, mxgenaiconnector.proxies.MxCloudKnowledgeBase mxknowledgebaseconnection_mxcloudknowledgebase)
	{
		if (mxknowledgebaseconnection_mxcloudknowledgebase == null) {
			getMendixObject().setValue(context, MemberNames.MxKnowledgeBaseConnection_MxCloudKnowledgeBase.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.MxKnowledgeBaseConnection_MxCloudKnowledgeBase.toString(), mxknowledgebaseconnection_mxcloudknowledgebase.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final mxgenaiconnector.proxies.MxKnowledgeBaseConnection that = (mxgenaiconnector.proxies.MxKnowledgeBaseConnection) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
