// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mxgenaiconnector.proxies;

/**
 * This entity contains the additional attributes that are relevant for a retrieve-and-generate operation.
 */
public class RetrieveAndGenerateRequest_Extension implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject retrieveAndGenerateRequest_ExtensionMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MxGenAIConnector.RetrieveAndGenerateRequest_Extension";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		MaxNumberOfResults("MaxNumberOfResults"),
		MinimumSimilarity("MinimumSimilarity"),
		ForceModelToUseKnowledgeBase("ForceModelToUseKnowledgeBase"),
		RetrieveAndGenerateRequest_Extension_MetadataCollection("MxGenAIConnector.RetrieveAndGenerateRequest_Extension_MetadataCollection"),
		RetrieveAndGenerateRequest_Extension_Request("MxGenAIConnector.RetrieveAndGenerateRequest_Extension_Request");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public RetrieveAndGenerateRequest_Extension(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected RetrieveAndGenerateRequest_Extension(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject retrieveAndGenerateRequest_ExtensionMendixObject)
	{
		if (retrieveAndGenerateRequest_ExtensionMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, retrieveAndGenerateRequest_ExtensionMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.retrieveAndGenerateRequest_ExtensionMendixObject = retrieveAndGenerateRequest_ExtensionMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static mxgenaiconnector.proxies.RetrieveAndGenerateRequest_Extension initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new mxgenaiconnector.proxies.RetrieveAndGenerateRequest_Extension(context, mendixObject);
	}

	public static mxgenaiconnector.proxies.RetrieveAndGenerateRequest_Extension load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return mxgenaiconnector.proxies.RetrieveAndGenerateRequest_Extension.initialize(context, mendixObject);
	}

	/**
	 * @return value of MaxNumberOfResults
	 */
	public final java.lang.Integer getMaxNumberOfResults()
	{
		return getMaxNumberOfResults(getContext());
	}

	/**
	 * @param context
	 * @return value of MaxNumberOfResults
	 */
	public final java.lang.Integer getMaxNumberOfResults(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.MaxNumberOfResults.toString());
	}

	/**
	 * Set value of MaxNumberOfResults
	 * @param maxnumberofresults
	 */
	public final void setMaxNumberOfResults(java.lang.Integer maxnumberofresults)
	{
		setMaxNumberOfResults(getContext(), maxnumberofresults);
	}

	/**
	 * Set value of MaxNumberOfResults
	 * @param context
	 * @param maxnumberofresults
	 */
	public final void setMaxNumberOfResults(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer maxnumberofresults)
	{
		getMendixObject().setValue(context, MemberNames.MaxNumberOfResults.toString(), maxnumberofresults);
	}

	/**
	 * @return value of MinimumSimilarity
	 */
	public final java.math.BigDecimal getMinimumSimilarity()
	{
		return getMinimumSimilarity(getContext());
	}

	/**
	 * @param context
	 * @return value of MinimumSimilarity
	 */
	public final java.math.BigDecimal getMinimumSimilarity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.MinimumSimilarity.toString());
	}

	/**
	 * Set value of MinimumSimilarity
	 * @param minimumsimilarity
	 */
	public final void setMinimumSimilarity(java.math.BigDecimal minimumsimilarity)
	{
		setMinimumSimilarity(getContext(), minimumsimilarity);
	}

	/**
	 * Set value of MinimumSimilarity
	 * @param context
	 * @param minimumsimilarity
	 */
	public final void setMinimumSimilarity(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal minimumsimilarity)
	{
		getMendixObject().setValue(context, MemberNames.MinimumSimilarity.toString(), minimumsimilarity);
	}

	/**
	 * @return value of ForceModelToUseKnowledgeBase
	 */
	public final java.lang.Boolean getForceModelToUseKnowledgeBase()
	{
		return getForceModelToUseKnowledgeBase(getContext());
	}

	/**
	 * @param context
	 * @return value of ForceModelToUseKnowledgeBase
	 */
	public final java.lang.Boolean getForceModelToUseKnowledgeBase(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ForceModelToUseKnowledgeBase.toString());
	}

	/**
	 * Set value of ForceModelToUseKnowledgeBase
	 * @param forcemodeltouseknowledgebase
	 */
	public final void setForceModelToUseKnowledgeBase(java.lang.Boolean forcemodeltouseknowledgebase)
	{
		setForceModelToUseKnowledgeBase(getContext(), forcemodeltouseknowledgebase);
	}

	/**
	 * Set value of ForceModelToUseKnowledgeBase
	 * @param context
	 * @param forcemodeltouseknowledgebase
	 */
	public final void setForceModelToUseKnowledgeBase(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean forcemodeltouseknowledgebase)
	{
		getMendixObject().setValue(context, MemberNames.ForceModelToUseKnowledgeBase.toString(), forcemodeltouseknowledgebase);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of RetrieveAndGenerateRequest_Extension_MetadataCollection
	 */
	public final genaicommons.proxies.MetadataCollection getRetrieveAndGenerateRequest_Extension_MetadataCollection() throws com.mendix.core.CoreException
	{
		return getRetrieveAndGenerateRequest_Extension_MetadataCollection(getContext());
	}

	/**
	 * @param context
	 * @return value of RetrieveAndGenerateRequest_Extension_MetadataCollection
	 * @throws com.mendix.core.CoreException
	 */
	public final genaicommons.proxies.MetadataCollection getRetrieveAndGenerateRequest_Extension_MetadataCollection(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		genaicommons.proxies.MetadataCollection result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.RetrieveAndGenerateRequest_Extension_MetadataCollection.toString());
		if (identifier != null) {
			result = genaicommons.proxies.MetadataCollection.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of RetrieveAndGenerateRequest_Extension_MetadataCollection
	 * @param retrieveandgeneraterequest_extension_metadatacollection
	 */
	public final void setRetrieveAndGenerateRequest_Extension_MetadataCollection(genaicommons.proxies.MetadataCollection retrieveandgeneraterequest_extension_metadatacollection)
	{
		setRetrieveAndGenerateRequest_Extension_MetadataCollection(getContext(), retrieveandgeneraterequest_extension_metadatacollection);
	}

	/**
	 * Set value of RetrieveAndGenerateRequest_Extension_MetadataCollection
	 * @param context
	 * @param retrieveandgeneraterequest_extension_metadatacollection
	 */
	public final void setRetrieveAndGenerateRequest_Extension_MetadataCollection(com.mendix.systemwideinterfaces.core.IContext context, genaicommons.proxies.MetadataCollection retrieveandgeneraterequest_extension_metadatacollection)
	{
		if (retrieveandgeneraterequest_extension_metadatacollection == null) {
			getMendixObject().setValue(context, MemberNames.RetrieveAndGenerateRequest_Extension_MetadataCollection.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.RetrieveAndGenerateRequest_Extension_MetadataCollection.toString(), retrieveandgeneraterequest_extension_metadatacollection.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of RetrieveAndGenerateRequest_Extension_Request
	 */
	public final genaicommons.proxies.Request getRetrieveAndGenerateRequest_Extension_Request() throws com.mendix.core.CoreException
	{
		return getRetrieveAndGenerateRequest_Extension_Request(getContext());
	}

	/**
	 * @param context
	 * @return value of RetrieveAndGenerateRequest_Extension_Request
	 * @throws com.mendix.core.CoreException
	 */
	public final genaicommons.proxies.Request getRetrieveAndGenerateRequest_Extension_Request(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		genaicommons.proxies.Request result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.RetrieveAndGenerateRequest_Extension_Request.toString());
		if (identifier != null) {
			result = genaicommons.proxies.Request.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of RetrieveAndGenerateRequest_Extension_Request
	 * @param retrieveandgeneraterequest_extension_request
	 */
	public final void setRetrieveAndGenerateRequest_Extension_Request(genaicommons.proxies.Request retrieveandgeneraterequest_extension_request)
	{
		setRetrieveAndGenerateRequest_Extension_Request(getContext(), retrieveandgeneraterequest_extension_request);
	}

	/**
	 * Set value of RetrieveAndGenerateRequest_Extension_Request
	 * @param context
	 * @param retrieveandgeneraterequest_extension_request
	 */
	public final void setRetrieveAndGenerateRequest_Extension_Request(com.mendix.systemwideinterfaces.core.IContext context, genaicommons.proxies.Request retrieveandgeneraterequest_extension_request)
	{
		if (retrieveandgeneraterequest_extension_request == null) {
			getMendixObject().setValue(context, MemberNames.RetrieveAndGenerateRequest_Extension_Request.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.RetrieveAndGenerateRequest_Extension_Request.toString(), retrieveandgeneraterequest_extension_request.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return retrieveAndGenerateRequest_ExtensionMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final mxgenaiconnector.proxies.RetrieveAndGenerateRequest_Extension that = (mxgenaiconnector.proxies.RetrieveAndGenerateRequest_Extension) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
