// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package genaicommons.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * This Java Action should only be used by connector developers. It executes the Request by calling an LLM via the passed ModelCallMicroflow.
 * 
 * If the model returns a tool call response, the function microflows are automatically executed and added as messages with MessageRole "tool" to the request. Afterwards the ModelCallMicroflow is executed again. This process is repeated until the model returns a final assistant response.
 * 
 * Additionally, this java action takes care of storing token usage metrics by calling the Usage_Create_TextAndFiles microflow, if the StoreUsageMetrics constant was set to true by the developer.
 */
public class Request_ExecuteFromConnector extends CustomJavaAction<IMendixObject>
{
	/** @deprecated use Request.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __Request;
	private final genaicommons.proxies.Request Request;
	/** @deprecated use Connection.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __Connection;
	private final genaicommons.proxies.Connection Connection;
	private final java.lang.String CallModelMicroflow;
	private final java.lang.String DeploymentIdentifier;

	public Request_ExecuteFromConnector(
		IContext context,
		IMendixObject _request,
		IMendixObject _connection,
		java.lang.String _callModelMicroflow,
		java.lang.String _deploymentIdentifier
	)
	{
		super(context);
		this.__Request = _request;
		this.Request = _request == null ? null : genaicommons.proxies.Request.initialize(getContext(), _request);
		this.__Connection = _connection;
		this.Connection = _connection == null ? null : genaicommons.proxies.Connection.initialize(getContext(), _connection);
		this.CallModelMicroflow = _callModelMicroflow;
		this.DeploymentIdentifier = _deploymentIdentifier;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		throw new com.mendix.systemwideinterfaces.MendixRuntimeException("Java action was not implemented");
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Request_ExecuteFromConnector";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
