// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package genaicommons.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * Adds a new Function to a Request.
 * Parameters: 
 * - Request: The request to add the function to.
 * - ToolName: The name of the tool to call.
 * - FunctionMicroflow: The microflow that is called within this function.
 * - ToolDescription (optional): A description of what the function does, used by the model to choose when and how to call the function.
 * - ToolChoice: Controls which (if any) function is called by the model.
 * `none` means the model will not call a function and instead generates a message.
 * `auto` means the model can pick between generating a message or calling a function.
 * `function` means that the new function will become the tool choice of the FunctionCollection. This will force the model to call that particular function.
 * 
 * `auto` is the default if functions are present.
 * 
 * Note: This setting might be overwritten, when adding more functions to the FunctionCollection at a later point and setting `IsFunctionToolChoice` to true.
 */
public class Request_AddFunction extends CustomJavaAction<IMendixObject>
{
	/** @deprecated use Request.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __Request;
	private final genaicommons.proxies.Request Request;
	private final java.lang.String ToolName;
	private final java.lang.String ToolDescription;
	private final java.lang.String FunctionMicroflow;

	public Request_AddFunction(
		IContext context,
		IMendixObject _request,
		java.lang.String _toolName,
		java.lang.String _toolDescription,
		java.lang.String _functionMicroflow
	)
	{
		super(context);
		this.__Request = _request;
		this.Request = _request == null ? null : genaicommons.proxies.Request.initialize(getContext(), _request);
		this.ToolName = _toolName;
		this.ToolDescription = _toolDescription;
		this.FunctionMicroflow = _functionMicroflow;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		throw new com.mendix.systemwideinterfaces.MendixRuntimeException("Java action was not implemented");
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Request_AddFunction";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
