// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package genaicommons.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Request_AddKnowledgeBaseRetrieval extends CustomJavaAction<IMendixObject>
{
	/** @deprecated use Request.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __Request;
	private final genaicommons.proxies.Request Request;
	private final java.lang.String ToolName;
	private final java.lang.String RetrieveMicroflow;
	/** @deprecated use Connection.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __Connection;
	private final genaicommons.proxies.Connection Connection;
	private final java.lang.String ToolDescription;
	/** @deprecated use MetadataCollection.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __MetadataCollection;
	private final genaicommons.proxies.MetadataCollection MetadataCollection;
	private final java.math.BigDecimal MinimumSimilarity;
	private final java.lang.Long MaxNumberOfResults;

	public Request_AddKnowledgeBaseRetrieval(
		IContext context,
		IMendixObject _request,
		java.lang.String _toolName,
		java.lang.String _retrieveMicroflow,
		IMendixObject _connection,
		java.lang.String _toolDescription,
		IMendixObject _metadataCollection,
		java.math.BigDecimal _minimumSimilarity,
		java.lang.Long _maxNumberOfResults
	)
	{
		super(context);
		this.__Request = _request;
		this.Request = _request == null ? null : genaicommons.proxies.Request.initialize(getContext(), _request);
		this.ToolName = _toolName;
		this.RetrieveMicroflow = _retrieveMicroflow;
		this.__Connection = _connection;
		this.Connection = _connection == null ? null : genaicommons.proxies.Connection.initialize(getContext(), _connection);
		this.ToolDescription = _toolDescription;
		this.__MetadataCollection = _metadataCollection;
		this.MetadataCollection = _metadataCollection == null ? null : genaicommons.proxies.MetadataCollection.initialize(getContext(), _metadataCollection);
		this.MinimumSimilarity = _minimumSimilarity;
		this.MaxNumberOfResults = _maxNumberOfResults;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		throw new com.mendix.systemwideinterfaces.MendixRuntimeException("Java action was not implemented");
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Request_AddKnowledgeBaseRetrieval";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
