// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package genaicommons.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * This operation processes a response that was created by an image generation operation. A return entity can be specified using ResponseImageEntity (needs to be of type System.Image or its specialization). An image of that type will be created and returned.
 */
public class Response_GetSingleResponseImage extends CustomJavaAction<IMendixObject>
{
	private final java.lang.String ResponseImageEntity;
	/** @deprecated use Response.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __Response;
	private final genaicommons.proxies.Response Response;

	public Response_GetSingleResponseImage(
		IContext context,
		java.lang.String _responseImageEntity,
		IMendixObject _response
	)
	{
		super(context);
		this.ResponseImageEntity = _responseImageEntity;
		this.__Response = _response;
		this.Response = _response == null ? null : genaicommons.proxies.Response.initialize(getContext(), _response);
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		throw new com.mendix.systemwideinterfaces.MendixRuntimeException("Java action was not implemented");
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Response_GetSingleResponseImage";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
