// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package genaicommons.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Tool_ExecuteMicroflow extends CustomJavaAction<java.lang.String>
{
	/** @deprecated use Tool.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __Tool;
	private final genaicommons.proxies.Tool Tool;
	/** @deprecated use Request.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __Request;
	private final genaicommons.proxies.Request Request;
	private final java.lang.String Arguments;

	public Tool_ExecuteMicroflow(
		IContext context,
		IMendixObject _tool,
		IMendixObject _request,
		java.lang.String _arguments
	)
	{
		super(context);
		this.__Tool = _tool;
		this.Tool = _tool == null ? null : genaicommons.proxies.Tool.initialize(getContext(), _tool);
		this.__Request = _request;
		this.Request = _request == null ? null : genaicommons.proxies.Request.initialize(getContext(), _request);
		this.Arguments = _arguments;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		throw new com.mendix.systemwideinterfaces.MendixRuntimeException("Java action was not implemented");
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Tool_ExecuteMicroflow";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
