// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package synthiaconnector.proxies;

public class Configuration implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject configurationMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "SynthiaConnector.Configuration";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		DisplayName("DisplayName"),
		Model("Model"),
		Architecture("Architecture"),
		ResourceType("ResourceType");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Configuration(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Configuration(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject configurationMendixObject)
	{
		if (configurationMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, configurationMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.configurationMendixObject = configurationMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static synthiaconnector.proxies.Configuration initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		if (com.mendix.core.Core.isSubClassOf("SynthiaConnector.ConfigurationEmbeddings", mendixObject.getType())) {
			return synthiaconnector.proxies.ConfigurationEmbeddings.initialize(context, mendixObject);
		}
		if (com.mendix.core.Core.isSubClassOf("SynthiaConnector.ConfigurationKnowledgeBase", mendixObject.getType())) {
			return synthiaconnector.proxies.ConfigurationKnowledgeBase.initialize(context, mendixObject);
		}
		if (com.mendix.core.Core.isSubClassOf("SynthiaConnector.ConfigurationTextGeneration", mendixObject.getType())) {
			return synthiaconnector.proxies.ConfigurationTextGeneration.initialize(context, mendixObject);
		}
		return new synthiaconnector.proxies.Configuration(context, mendixObject);
	}

	public static synthiaconnector.proxies.Configuration load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return synthiaconnector.proxies.Configuration.initialize(context, mendixObject);
	}

	public static java.util.List<? extends synthiaconnector.proxies.Configuration> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> synthiaconnector.proxies.Configuration.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of DisplayName
	 */
	public final java.lang.String getDisplayName()
	{
		return getDisplayName(getContext());
	}

	/**
	 * @param context
	 * @return value of DisplayName
	 */
	public final java.lang.String getDisplayName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DisplayName.toString());
	}

	/**
	 * Set value of DisplayName
	 * @param displayname
	 */
	public final void setDisplayName(java.lang.String displayname)
	{
		setDisplayName(getContext(), displayname);
	}

	/**
	 * Set value of DisplayName
	 * @param context
	 * @param displayname
	 */
	public final void setDisplayName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String displayname)
	{
		getMendixObject().setValue(context, MemberNames.DisplayName.toString(), displayname);
	}

	/**
	 * @return value of Model
	 */
	public final java.lang.String getModel()
	{
		return getModel(getContext());
	}

	/**
	 * @param context
	 * @return value of Model
	 */
	public final java.lang.String getModel(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Model.toString());
	}

	/**
	 * Set value of Model
	 * @param model
	 */
	public final void setModel(java.lang.String model)
	{
		setModel(getContext(), model);
	}

	/**
	 * Set value of Model
	 * @param context
	 * @param model
	 */
	public final void setModel(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String model)
	{
		getMendixObject().setValue(context, MemberNames.Model.toString(), model);
	}

	/**
	 * Get value of Architecture
	 * @param architecture
	 */
	public final synthiaconnector.proxies.ENUM_Architecture getArchitecture()
	{
		return getArchitecture(getContext());
	}

	/**
	 * @param context
	 * @return value of Architecture
	 */
	public final synthiaconnector.proxies.ENUM_Architecture getArchitecture(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Architecture.toString());
		if (obj == null) {
			return null;
		}
		return synthiaconnector.proxies.ENUM_Architecture.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Architecture
	 * @param architecture
	 */
	public final void setArchitecture(synthiaconnector.proxies.ENUM_Architecture architecture)
	{
		setArchitecture(getContext(), architecture);
	}

	/**
	 * Set value of Architecture
	 * @param context
	 * @param architecture
	 */
	public final void setArchitecture(com.mendix.systemwideinterfaces.core.IContext context, synthiaconnector.proxies.ENUM_Architecture architecture)
	{
		if (architecture != null) {
			getMendixObject().setValue(context, MemberNames.Architecture.toString(), architecture.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.Architecture.toString(), null);
		}
	}

	/**
	 * Get value of ResourceType
	 * @param resourcetype
	 */
	public final synthiaconnector.proxies.ENUM_ResourceType getResourceType()
	{
		return getResourceType(getContext());
	}

	/**
	 * @param context
	 * @return value of ResourceType
	 */
	public final synthiaconnector.proxies.ENUM_ResourceType getResourceType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.ResourceType.toString());
		if (obj == null) {
			return null;
		}
		return synthiaconnector.proxies.ENUM_ResourceType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of ResourceType
	 * @param resourcetype
	 */
	public final void setResourceType(synthiaconnector.proxies.ENUM_ResourceType resourcetype)
	{
		setResourceType(getContext(), resourcetype);
	}

	/**
	 * Set value of ResourceType
	 * @param context
	 * @param resourcetype
	 */
	public final void setResourceType(com.mendix.systemwideinterfaces.core.IContext context, synthiaconnector.proxies.ENUM_ResourceType resourcetype)
	{
		if (resourcetype != null) {
			getMendixObject().setValue(context, MemberNames.ResourceType.toString(), resourcetype.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.ResourceType.toString(), null);
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return configurationMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final synthiaconnector.proxies.Configuration that = (synthiaconnector.proxies.Configuration) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
