// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package synthiaconnector.proxies;

public class ConfigurationKnowledgeBase extends synthiaconnector.proxies.Configuration
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "SynthiaConnector.ConfigurationKnowledgeBase";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		DisplayName("DisplayName"),
		Model("Model"),
		Architecture("Architecture"),
		ResourceType("ResourceType"),
		ConfigurationKnowledgeBase_ConfigurationEmbeddings("SynthiaConnector.ConfigurationKnowledgeBase_ConfigurationEmbeddings");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ConfigurationKnowledgeBase(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ConfigurationKnowledgeBase(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject configurationKnowledgeBaseMendixObject)
	{
		super(context, configurationKnowledgeBaseMendixObject);
		if (!com.mendix.core.Core.isSubClassOf(entityName, configurationKnowledgeBaseMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static synthiaconnector.proxies.ConfigurationKnowledgeBase initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new synthiaconnector.proxies.ConfigurationKnowledgeBase(context, mendixObject);
	}

	public static synthiaconnector.proxies.ConfigurationKnowledgeBase load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return synthiaconnector.proxies.ConfigurationKnowledgeBase.initialize(context, mendixObject);
	}

	public static java.util.List<synthiaconnector.proxies.ConfigurationKnowledgeBase> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> synthiaconnector.proxies.ConfigurationKnowledgeBase.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ConfigurationKnowledgeBase_ConfigurationEmbeddings
	 */
	public final synthiaconnector.proxies.ConfigurationEmbeddings getConfigurationKnowledgeBase_ConfigurationEmbeddings() throws com.mendix.core.CoreException
	{
		return getConfigurationKnowledgeBase_ConfigurationEmbeddings(getContext());
	}

	/**
	 * @param context
	 * @return value of ConfigurationKnowledgeBase_ConfigurationEmbeddings
	 * @throws com.mendix.core.CoreException
	 */
	public final synthiaconnector.proxies.ConfigurationEmbeddings getConfigurationKnowledgeBase_ConfigurationEmbeddings(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		synthiaconnector.proxies.ConfigurationEmbeddings result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ConfigurationKnowledgeBase_ConfigurationEmbeddings.toString());
		if (identifier != null) {
			result = synthiaconnector.proxies.ConfigurationEmbeddings.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ConfigurationKnowledgeBase_ConfigurationEmbeddings
	 * @param configurationknowledgebase_configurationembeddings
	 */
	public final void setConfigurationKnowledgeBase_ConfigurationEmbeddings(synthiaconnector.proxies.ConfigurationEmbeddings configurationknowledgebase_configurationembeddings)
	{
		setConfigurationKnowledgeBase_ConfigurationEmbeddings(getContext(), configurationknowledgebase_configurationembeddings);
	}

	/**
	 * Set value of ConfigurationKnowledgeBase_ConfigurationEmbeddings
	 * @param context
	 * @param configurationknowledgebase_configurationembeddings
	 */
	public final void setConfigurationKnowledgeBase_ConfigurationEmbeddings(com.mendix.systemwideinterfaces.core.IContext context, synthiaconnector.proxies.ConfigurationEmbeddings configurationknowledgebase_configurationembeddings)
	{
		if (configurationknowledgebase_configurationembeddings == null) {
			getMendixObject().setValue(context, MemberNames.ConfigurationKnowledgeBase_ConfigurationEmbeddings.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ConfigurationKnowledgeBase_ConfigurationEmbeddings.toString(), configurationknowledgebase_configurationembeddings.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final synthiaconnector.proxies.ConfigurationKnowledgeBase that = (synthiaconnector.proxies.ConfigurationKnowledgeBase) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
