// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package synthiaconnector.proxies;

/**
 * Connection to be used in operations (GenAI Commons compatible). Can be created via SynthiaConnection_Create.
 */
public class SynthiaConnection extends genaicommons.proxies.Connection
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "SynthiaConnector.SynthiaConnection";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		KnowledgeBaseName("KnowledgeBaseName"),
		Model("Model"),
		SynthiaConnection_Configuration("SynthiaConnector.SynthiaConnection_Configuration");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public SynthiaConnection(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected SynthiaConnection(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject synthiaConnectionMendixObject)
	{
		super(context, synthiaConnectionMendixObject);
		if (!com.mendix.core.Core.isSubClassOf(entityName, synthiaConnectionMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static synthiaconnector.proxies.SynthiaConnection initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new synthiaconnector.proxies.SynthiaConnection(context, mendixObject);
	}

	public static synthiaconnector.proxies.SynthiaConnection load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return synthiaconnector.proxies.SynthiaConnection.initialize(context, mendixObject);
	}

	/**
	 * @return value of KnowledgeBaseName
	 */
	public final java.lang.String getKnowledgeBaseName()
	{
		return getKnowledgeBaseName(getContext());
	}

	/**
	 * @param context
	 * @return value of KnowledgeBaseName
	 */
	public final java.lang.String getKnowledgeBaseName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.KnowledgeBaseName.toString());
	}

	/**
	 * Set value of KnowledgeBaseName
	 * @param knowledgebasename
	 */
	public final void setKnowledgeBaseName(java.lang.String knowledgebasename)
	{
		setKnowledgeBaseName(getContext(), knowledgebasename);
	}

	/**
	 * Set value of KnowledgeBaseName
	 * @param context
	 * @param knowledgebasename
	 */
	public final void setKnowledgeBaseName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String knowledgebasename)
	{
		getMendixObject().setValue(context, MemberNames.KnowledgeBaseName.toString(), knowledgebasename);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of SynthiaConnection_Configuration
	 */
	public final synthiaconnector.proxies.Configuration getSynthiaConnection_Configuration() throws com.mendix.core.CoreException
	{
		return getSynthiaConnection_Configuration(getContext());
	}

	/**
	 * @param context
	 * @return value of SynthiaConnection_Configuration
	 * @throws com.mendix.core.CoreException
	 */
	public final synthiaconnector.proxies.Configuration getSynthiaConnection_Configuration(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		synthiaconnector.proxies.Configuration result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.SynthiaConnection_Configuration.toString());
		if (identifier != null) {
			result = synthiaconnector.proxies.Configuration.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of SynthiaConnection_Configuration
	 * @param synthiaconnection_configuration
	 */
	public final void setSynthiaConnection_Configuration(synthiaconnector.proxies.Configuration synthiaconnection_configuration)
	{
		setSynthiaConnection_Configuration(getContext(), synthiaconnection_configuration);
	}

	/**
	 * Set value of SynthiaConnection_Configuration
	 * @param context
	 * @param synthiaconnection_configuration
	 */
	public final void setSynthiaConnection_Configuration(com.mendix.systemwideinterfaces.core.IContext context, synthiaconnector.proxies.Configuration synthiaconnection_configuration)
	{
		if (synthiaconnection_configuration == null) {
			getMendixObject().setValue(context, MemberNames.SynthiaConnection_Configuration.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.SynthiaConnection_Configuration.toString(), synthiaconnection_configuration.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final synthiaconnector.proxies.SynthiaConnection that = (synthiaconnector.proxies.SynthiaConnection) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
