// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package genaicommons.actions;

import static java.util.Objects.requireNonNull;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IDataType;
import com.mendix.webui.CustomJavaAction;
import genaicommons.impl.DeployedModelImpl;
import genaicommons.impl.MxLogger;
import genaicommons.proxies.ENUM_ModelModality;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;

public class ChatCompletions_WithHistory extends UserAction<IMendixObject>
{
	/** @deprecated use Request.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __Request;
	private final genaicommons.proxies.Request Request;
	/** @deprecated use DeployedModel.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __DeployedModel;
	private final genaicommons.proxies.DeployedModel DeployedModel;

	public ChatCompletions_WithHistory(
		IContext context,
		IMendixObject _request,
		IMendixObject _deployedModel
	)
	{
		super(context);
		this.__Request = _request;
		this.Request = _request == null ? null : genaicommons.proxies.Request.initialize(getContext(), _request);
		this.__DeployedModel = _deployedModel;
		this.DeployedModel = _deployedModel == null ? null : genaicommons.proxies.DeployedModel.initialize(getContext(), _deployedModel);
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		try {
			validate();
			return Core.microflowCall(DeployedModel.getMicroflow())
					.withParams(mapInputParameters())
					.execute(this.getContext());

		} catch (Exception e) {
			LOGGER.error(e);
			return null;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ChatCompletions_WithHistory";
	}

	// BEGIN EXTRA CODE
	private static final MxLogger LOGGER = new MxLogger(ChatCompletions_WithHistory.class);
	
	private void validate() {
		requireNonNull(Request, "Request is required.");
		DeployedModelImpl.validate(DeployedModel, ENUM_ModelModality.Text);
	}
	
	private Map<String, Object> mapInputParameters() {
		Map<String, Object> inputParameters = new java.util.HashMap<>();
		Map<String, IDataType> parametersAndTypes = Core.getInputParameters(DeployedModel.getMicroflow());
		parametersAndTypes.forEach((t, u) -> {
			if(Core.getMetaObject(u.getObjectType()).isSubClassOf(genaicommons.proxies.DeployedModel.getType())) {
				inputParameters.put(t, DeployedModel.getMendixObject());
			} else if(Core.getMetaObject(u.getObjectType()).isSubClassOf(genaicommons.proxies.Request.getType())) {
				inputParameters.put(t, Request.getMendixObject());
			}
		}
		);
		return inputParameters;
	}
	
	// END EXTRA CODE
}
