// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package genaicommons.actions;

import static java.util.Objects.requireNonNull;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;
import genaicommons.impl.MxLogger;

public class ConsumedKnowledgeBase_SetMicroflows extends UserAction<java.lang.Boolean>
{
	/** @deprecated use ConsumedKnowledgeBase.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __ConsumedKnowledgeBase;
	private final genaicommons.proxies.ConsumedKnowledgeBase ConsumedKnowledgeBase;
	private final java.lang.String RetrievalMicroflow;
	private final java.lang.String GetCollectionOptionsMicroflow;
	private final java.lang.String GetDeployedKnowledgeBaseMicroflow;

	public ConsumedKnowledgeBase_SetMicroflows(
		IContext context,
		IMendixObject _consumedKnowledgeBase,
		java.lang.String _retrievalMicroflow,
		java.lang.String _getCollectionOptionsMicroflow,
		java.lang.String _getDeployedKnowledgeBaseMicroflow
	)
	{
		super(context);
		this.__ConsumedKnowledgeBase = _consumedKnowledgeBase;
		this.ConsumedKnowledgeBase = _consumedKnowledgeBase == null ? null : genaicommons.proxies.ConsumedKnowledgeBase.initialize(getContext(), _consumedKnowledgeBase);
		this.RetrievalMicroflow = _retrievalMicroflow;
		this.GetCollectionOptionsMicroflow = _getCollectionOptionsMicroflow;
		this.GetDeployedKnowledgeBaseMicroflow = _getDeployedKnowledgeBaseMicroflow;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		try {
			requireNonNull(RetrievalMicroflow, "Retrieval Microflow is required.");
			requireNonNull(GetCollectionOptionsMicroflow, "GetCollectionOptions Microflow is required.");
			requireNonNull(GetDeployedKnowledgeBaseMicroflow, "GetDeployedKnowledgeBase Microflow is required.");
			requireNonNull(ConsumedKnowledgeBase, "ConsumedKnowledgeBase is required.");
			
			ConsumedKnowledgeBase.setRetrievalMicroflow(RetrievalMicroflow);
			ConsumedKnowledgeBase.setGetCollectionsMicroflow(GetCollectionOptionsMicroflow);
			ConsumedKnowledgeBase.setGetDeployedKnowledgeBaseMicroflow(GetDeployedKnowledgeBaseMicroflow);
			
			return true;
			
		} catch (Exception e) {
			LOGGER.error(e);
			return false;
		}
		// END U
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ConsumedKnowledgeBase_SetMicroflows";
	}

	// BEGIN EXTRA CODE
	private static final MxLogger LOGGER = new MxLogger(ConsumedKnowledgeBase_SetMicroflows.class);
	// END EXTRA CODE
}
