// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package genaicommons.actions;

import static java.util.Objects.requireNonNull;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;

public class ConsumedKnowledgeBase_GetCollectionOptions extends UserAction<java.util.List<IMendixObject>>
{
	/** @deprecated use ConsumedKnowledgeBase.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __ConsumedKnowledgeBase;
	private final genaicommons.proxies.ConsumedKnowledgeBase ConsumedKnowledgeBase;

	public ConsumedKnowledgeBase_GetCollectionOptions(
		IContext context,
		IMendixObject _consumedKnowledgeBase
	)
	{
		super(context);
		this.__ConsumedKnowledgeBase = _consumedKnowledgeBase;
		this.ConsumedKnowledgeBase = _consumedKnowledgeBase == null ? null : genaicommons.proxies.ConsumedKnowledgeBase.initialize(getContext(), _consumedKnowledgeBase);
	}

	@java.lang.Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		// BEGIN USER CODE
		requireNonNull(ConsumedKnowledgeBase, "ConsumedKnowledgeBse is required.");
		requireNonNull(ConsumedKnowledgeBase.getGetCollectionsMicroflow(), "ConsumedKnowledgeBase has no GetCollections microflow.");
		Map<String, Object> params = new java.util.HashMap<>();
		params.put("ConsumedKnowledgeBase", ConsumedKnowledgeBase);
		return	Core.microflowCall(ConsumedKnowledgeBase.getGetCollectionsMicroflow()).withParams(params).execute(getContext());
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ConsumedKnowledgeBase_GetCollectionOptions";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
