// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package genaicommons.actions;

import static java.util.Objects.requireNonNull;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;

public class ConsumedKnowledgeBase_GetDeployedKnowledgeBase extends UserAction<IMendixObject>
{
	/** @deprecated use ConsumedKnowledgeBase.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __ConsumedKnowledgeBase;
	private final genaicommons.proxies.ConsumedKnowledgeBase ConsumedKnowledgeBase;
	private final java.lang.String CollectionIdentifier;

	public ConsumedKnowledgeBase_GetDeployedKnowledgeBase(
		IContext context,
		IMendixObject _consumedKnowledgeBase,
		java.lang.String _collectionIdentifier
	)
	{
		super(context);
		this.__ConsumedKnowledgeBase = _consumedKnowledgeBase;
		this.ConsumedKnowledgeBase = _consumedKnowledgeBase == null ? null : genaicommons.proxies.ConsumedKnowledgeBase.initialize(getContext(), _consumedKnowledgeBase);
		this.CollectionIdentifier = _collectionIdentifier;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		requireNonNull(ConsumedKnowledgeBase, "ConsumedKnowledgeBase is required.");
		requireNonNull(ConsumedKnowledgeBase.getGetDeployedKnowledgeBaseMicroflow(), "ConsumedKnowledgeBase has no GetDeployedKnowledgeBase microflow.");
		Map<String, Object> params = new java.util.HashMap<>();
		params.put("CollectionIdentifier", CollectionIdentifier);
		params.put("ConsumedKnowledgeBase", ConsumedKnowledgeBase);
		return	Core.microflowCall(ConsumedKnowledgeBase.getGetDeployedKnowledgeBaseMicroflow()).withParams(params).execute(getContext());
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ConsumedKnowledgeBase_GetDeployedKnowledgeBase";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
