// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package genaicommons.actions;

import static java.util.Objects.requireNonNull;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import genaicommons.impl.DeployedModelImpl;
import genaicommons.impl.MxLogger;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Sets the microflow to execute for the specified model and type of the DeployedModel. The microflow should follow the principles from GenAI commons that are applicable for the model type.
 * 
 * E.g. For text generation, the following input and response parameters are required:
 * - Input parameters: GenAICommons.Request and GenAICommons.DeployedModel
 * - Return type: GenAICommons.Response
 */
public class DeployedModel_SetMicroflow extends UserAction<java.lang.Boolean>
{
	/** @deprecated use DeployedModel.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __DeployedModel;
	private final genaicommons.proxies.DeployedModel DeployedModel;
	private final java.lang.String Microflow;

	public DeployedModel_SetMicroflow(
		IContext context,
		IMendixObject _deployedModel,
		java.lang.String _microflow
	)
	{
		super(context);
		this.__DeployedModel = _deployedModel;
		this.DeployedModel = _deployedModel == null ? null : genaicommons.proxies.DeployedModel.initialize(getContext(), _deployedModel);
		this.Microflow = _microflow;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		try {
			requireNonNull(Microflow, "Microflow is required.");
			requireNonNull(DeployedModel, "DeployedModel is required.");
			if (DeployedModel.getOutputModality() != null)
				DeployedModelImpl.validateMicroflow(Microflow, DeployedModel.getOutputModality());
			
			DeployedModel.setMicroflow(Microflow);
			
			return true;
			
		} catch (Exception e) {
			LOGGER.error(e);
			return false;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "DeployedModel_SetMicroflow";
	}

	// BEGIN EXTRA CODE
	private static final MxLogger LOGGER = new MxLogger(DeployedModel_SetMicroflow.class);

	// END EXTRA CODE
}
