// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package genaicommons.actions;

import static java.util.Objects.requireNonNull;
import com.mendix.systemwideinterfaces.core.IContext;
import genaicommons.impl.MxLogger;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Sets the microflow to retrieve data from the selected type of DeployedKnowledgeBase.
 */
public class DeployedKnowledgeBase_SetMicroflow extends UserAction<java.lang.Boolean>
{
	/** @deprecated use DeployedKnowledgeBase.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __DeployedKnowledgeBase;
	private final genaicommons.proxies.DeployedKnowledgeBase DeployedKnowledgeBase;
	private final java.lang.String Microflow;

	public DeployedKnowledgeBase_SetMicroflow(
		IContext context,
		IMendixObject _deployedKnowledgeBase,
		java.lang.String _microflow
	)
	{
		super(context);
		this.__DeployedKnowledgeBase = _deployedKnowledgeBase;
		this.DeployedKnowledgeBase = _deployedKnowledgeBase == null ? null : genaicommons.proxies.DeployedKnowledgeBase.initialize(getContext(), _deployedKnowledgeBase);
		this.Microflow = _microflow;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		try {
			requireNonNull(Microflow, "Microflow is required.");
			requireNonNull(DeployedKnowledgeBase, "DeployedKnowledgeBase is required.");
			
			DeployedKnowledgeBase.setMicroflow(Microflow);
			
			return true;
			
		} catch (Exception e) {
			LOGGER.error(e);
			return false;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "DeployedKnowledgeBase_SetMicroflow";
	}

	// BEGIN EXTRA CODE
	private static final MxLogger LOGGER = new MxLogger(DeployedKnowledgeBase_SetMicroflow.class);

	// END EXTRA CODE
}
