// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package genaicommons.actions;

import static java.util.Objects.requireNonNull;
import java.util.Date;
import java.util.UUID;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import genaicommons.proxies.ENUM_ModelModality;
import genaicommons.proxies.Message;
import genaicommons.proxies.ModelSpan;
import genaicommons.proxies.Response;
import genaicommons.proxies.Trace;
import genaicommons.proxies.Usage;
import genaicommons.proxies.microflows.Microflows;
import genaicommons.impl.DeployedModelImpl;
import genaicommons.impl.MxLogger;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * This Java Action should only be used by connector developers. It executes the Request by calling an LLM via the passed ModelCallMicroflow.
 * 
 * If the model returns a tool call response, the function microflows are automatically executed and added as messages with MessageRole "tool" to the request. Afterwards the ModelCallMicroflow is executed again. This process is repeated until the model returns a final assistant response.
 * 
 * Additionally, this java action takes care of storing token usage metrics by calling the Usage_Create_TextAndFiles microflow, if the StoreUsageMetrics constant was set to true by the developer.
 */
public class Request_ExecuteFromConnector extends UserAction<IMendixObject>
{
	/** @deprecated use Request.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __Request;
	private final genaicommons.proxies.Request Request;
	/** @deprecated use DeployedModel.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __DeployedModel;
	private final genaicommons.proxies.DeployedModel DeployedModel;
	private final java.lang.String CallModelMicroflow;

	public Request_ExecuteFromConnector(
		IContext context,
		IMendixObject _request,
		IMendixObject _deployedModel,
		java.lang.String _callModelMicroflow
	)
	{
		super(context);
		this.__Request = _request;
		this.Request = _request == null ? null : genaicommons.proxies.Request.initialize(getContext(), _request);
		this.__DeployedModel = _deployedModel;
		this.DeployedModel = _deployedModel == null ? null : genaicommons.proxies.DeployedModel.initialize(getContext(), _deployedModel);
		this.CallModelMicroflow = _callModelMicroflow;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		try {
			validate();
			startTime = System.currentTimeMillis();
			Response response = processRequest();
			if(response != null) {
				return response.getMendixObject();
			} else {
				return null;
			}
		} catch (Exception e) {
			throw e;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Request_ExecuteFromConnector";
	}

	// BEGIN EXTRA CODE
	private static final MxLogger LOGGER = new genaicommons.impl.MxLogger(Request_ExecuteFromConnector.class);
	private int totalTokens = 0;
	private int requestTokens = 0;
	private int responseTokens = 0;
	private long startTime;
	
	//Recursive response processing until there is no ToolCall available
	private Response processRequest() throws CoreException {
		ModelSpan modelSpan = createModelSpan();
		IMendixObject responseMendixObject = Core.microflowCall(CallModelMicroflow).withParam("DeployedModel", DeployedModel.getMendixObject()).withParam("Request", Request.getMendixObject()).execute(this.getContext());
		if(responseMendixObject == null) {
			LOGGER.debug("Microflow " + CallModelMicroflow  + " returned null.");
			return null;
		}
		Response response = genaicommons.proxies.Response.load(getContext(), responseMendixObject.getId());
		
		Message assistantMessage = response.getResponse_Message();
		response.setResponseText(assistantMessage.getContent());
		updateModelSpan(modelSpan, response);
		responseUpdateTokenCount(response);
		
		boolean toolCallsProcessed = Microflows.response_ProcessToolCalls(getContext(), response, Request, modelSpan);
		
		//Recursion if tool calls are available
		if (toolCallsProcessed) {
			return processRequest();
		}
		
		responsePostProcessing(response);
		return response;
	}

	/**
	 * Sets duration of final response, sets response Id; creates Usage and updates Trace.
	 * @param response
	 * @throws CoreException
	 */
	private void responsePostProcessing(Response response) throws CoreException {
		response.setDurationMilliseconds((int) Math.ceil(System.currentTimeMillis() - startTime));
		if(response.get_ID() == null || response.get_ID().isBlank()) {
			if(Request.get_ID() != null && !Request.get_ID().isBlank()) {
				response.set_ID(Request.get_ID());
				
			}else {
				response.set_ID(UUID.randomUUID().toString());
			}
		}
		
		Trace trace = Request.getRequest_Trace();
		
		//trace == null if the constant was empty
		if (trace != null || genaicommons.proxies.constants.Constants.getStoreUsageMetrics()) {
			Usage usage = Microflows.usage_Create_TextAndFiles(getContext(), response, DeployedModel);

			if(trace != null) {
				trace.setTrace_Usage(usage);
				trace.setOutput(response.getResponseText());
				trace.setSystemPrompt(Request.getSystemPrompt());
			}
		}
	}
	
	//Updates modelspan after the response was created
	private void updateModelSpan(ModelSpan modelSpan, Response response) throws CoreException {
		if(modelSpan != null) {
			//modelSpan.setSpan_Trace(trace);
			modelSpan.setIsError(false);
			modelSpan.setInputTokens(response.getRequestTokens());
			modelSpan.setOutputTokens(response.getResponseTokens());
			modelSpan.setOutput(response.getResponseText());
			modelSpan.setEndTime(new Date(System.currentTimeMillis()));
			modelSpan.setDurationMilliseconds((int) (modelSpan.getEndTime().getTime() -  modelSpan.getStartTime().getTime()));
		}
	}
	
	//Creates ModelSpan with known startTime
	private ModelSpan createModelSpan() throws CoreException {
		Trace trace = Request.getRequest_Trace();
		if(trace != null) {
			ModelSpan modelSpan = new ModelSpan(getContext());
			modelSpan.setInput(Microflows.trace_GetModelSpanInput(getContext(),trace)); 
			modelSpan.setSpanId(UUID.randomUUID().toString());
			modelSpan.setSpan_Trace(trace);
			modelSpan.setIsError(true);
			modelSpan.set_DeploymentIdentifier(DeployedModel.getArchitecture() + ' ' + DeployedModel.getDisplayName());
			modelSpan.setStartTime(new Date(System.currentTimeMillis()));
			return modelSpan;
			
		} else {
			return null;
		}
	}
	
	private void responseUpdateTokenCount(Response response) {
		requestTokens += response.getRequestTokens() != null ? response.getRequestTokens() : 0;
		responseTokens += response.getResponseTokens() != null ? response.getResponseTokens() : 0;
		totalTokens += response.getTotalTokens() != null ? response.getTotalTokens() : 0;
		
		response.setRequestTokens(requestTokens);
		response.setResponseTokens(responseTokens);
		response.setTotalTokens(totalTokens);
	}
	
	private void validate() {
		requireNonNull(Request, "Request is required.");
		
		if (CallModelMicroflow == null || CallModelMicroflow.isBlank()) {
			throw new IllegalArgumentException("CallModelMicroflow is required.");
		}
		
		DeployedModelImpl.validate(DeployedModel, ENUM_ModelModality.Text);
	}
	// END EXTRA CODE
}
