// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package genaicommons.actions;

import static java.util.Objects.requireNonNull;
import java.util.List;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import genaicommons.impl.FunctionImpl;
import genaicommons.impl.MxLogger;
import genaicommons.impl.ToolCollectionImpl;
import genaicommons.proxies.Function;
import genaicommons.proxies.ToolCollection;
import genaicommons.proxies.Tool;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Adds a new Function to a Request.
 * Parameters: 
 * - Request: The request to add the function to.
 * - ToolName: The name of the tool to call.
 * - FunctionMicroflow: The microflow that is called within this function.
 * - ToolDescription (optional): A description of what the function does, used by the model to choose when and how to call the function.
 * 
 * The action returns empty if adding the function was not successful (errors are logged).
 */
public class Request_AddFunction extends UserAction<IMendixObject>
{
	/** @deprecated use Request.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __Request;
	private final genaicommons.proxies.Request Request;
	private final java.lang.String ToolName;
	private final java.lang.String ToolDescription;
	private final java.lang.String FunctionMicroflow;
	private final genaicommons.proxies.ENUM_UserAccessApproval UserAccessApproval;
	private final java.lang.String DisplayTitle;
	private final java.lang.String DisplayDescription;

	public Request_AddFunction(
		IContext context,
		IMendixObject _request,
		java.lang.String _toolName,
		java.lang.String _toolDescription,
		java.lang.String _functionMicroflow,
		java.lang.String _userAccessApproval,
		java.lang.String _displayTitle,
		java.lang.String _displayDescription
	)
	{
		super(context);
		this.__Request = _request;
		this.Request = _request == null ? null : genaicommons.proxies.Request.initialize(getContext(), _request);
		this.ToolName = _toolName;
		this.ToolDescription = _toolDescription;
		this.FunctionMicroflow = _functionMicroflow;
		this.UserAccessApproval = _userAccessApproval == null ? null : genaicommons.proxies.ENUM_UserAccessApproval.valueOf(_userAccessApproval);
		this.DisplayTitle = _displayTitle;
		this.DisplayDescription = _displayDescription;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		try{
			requireNonNull(Request, "Request is required.");
			FunctionImpl.validateFunctionInput(FunctionMicroflow, ToolName);
			
			return createFunction().getMendixObject();

		} catch (Exception e) {
			LOGGER.error(e);
			return null;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Request_AddFunction";
	}

	// BEGIN EXTRA CODE
	private static final MxLogger LOGGER = new genaicommons.impl.MxLogger(Request_AddFunction.class);

	/**
	 * Creates a function object, adds it to a toolcollection
	 * @param context
	 * @param functionMicroflow
	 * @param functionName
	 * @param functionDescription
	 * @param toolCollection
	 * @return
	 * @throws CoreException
	 */
	private Function createFunction() throws CoreException {
		ToolCollection toolCollection = ToolCollectionImpl.getOrCreateToolCollection(getContext(), Request);
		Function function = new Function(getContext());
		function.setMicroflow(FunctionMicroflow);
		function.setName(ToolName);	

		//Optional parameters
		function.setDescription(ToolDescription); 
		function.setDisplayTitle(DisplayTitle);
		function.setDisplayDescription(DisplayDescription);
		if(UserAccessApproval != null) {
			function.setUserAccessApproval(UserAccessApproval);
		}else {
			function.setUserAccessApproval(genaicommons.proxies.ENUM_UserAccessApproval.HiddenForUser);
		}

		List<Tool> ToolList = toolCollection.getToolCollection_Tool();
		ToolList.add(function);
		toolCollection.setToolCollection_Tool(ToolList); 

		return function;
	}
	// END EXTRA CODE
}
