// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package genaicommons.actions;

import static java.util.Objects.requireNonNull;
import java.util.ArrayList;
import java.util.List;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import genaicommons.impl.FileContentImpl;
import genaicommons.impl.ImageGenImpl;
import genaicommons.impl.MxLogger;
import genaicommons.proxies.FileContent;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * This operation processes a response that was created by an image generation operation. A return entity can be specified using ResponseImageEntity (needs to be of type System.Image or its specialization). A list of images of that type will be created and returned.
 */
public class Response_GetResponseImageList extends UserAction<java.util.List<IMendixObject>>
{
	private final java.lang.String ResponseImageEntity;
	/** @deprecated use Response.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __Response;
	private final genaicommons.proxies.Response Response;

	public Response_GetResponseImageList(
		IContext context,
		java.lang.String _responseImageEntity,
		IMendixObject _response
	)
	{
		super(context);
		this.ResponseImageEntity = _responseImageEntity;
		this.__Response = _response;
		this.Response = _response == null ? null : genaicommons.proxies.Response.initialize(getContext(), _response);
	}

	@java.lang.Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		// BEGIN USER CODE
		try {
			requireNonNull(Response, "Response is required.");
			requireNonNull(ResponseImageEntity, "ResponseImageEntity is required");
			ImageGenImpl.validateTargetEntity(ResponseImageEntity);
			
			List<FileContent> fileContentList = FileContentImpl.getFileContentList(Response);
			List<IMendixObject> returnList = createGeneratedImageList(fileContentList);
			
			return returnList;
			
		} catch (Exception e) {
			LOGGER.error(e);
			return null;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Response_GetResponseImageList";
	}

	// BEGIN EXTRA CODE
	private static final MxLogger LOGGER = new MxLogger(Response_GetResponseImageList.class);
	
	private List<IMendixObject> createGeneratedImageList(List<FileContent> fileContentList) {
		List<IMendixObject> imageList = new ArrayList<>();
		
		for (FileContent fileContent : fileContentList) {
			if (fileContent == null || fileContent.getFileContent().isBlank()) {
				LOGGER.warn("Empty FileContent found as part of the response.");
				continue;
			}
			IMendixObject generatedImage = ImageGenImpl.getSingleGeneratedImage(fileContent, ResponseImageEntity, getContext());
			imageList.add(generatedImage);
		}
		
		return imageList;
	}
	
	// END EXTRA CODE
}
