// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package genaicommons.actions;

import static java.util.Objects.requireNonNull;
import java.util.Date;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IDataType;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import genaicommons.impl.MxLogger;
import genaicommons.proxies.Argument;
import genaicommons.proxies.ArgumentInput;
import genaicommons.proxies.KnowledgeBaseSpan;
import genaicommons.proxies.MCPSpan;
import genaicommons.proxies.ModelSpan;
import genaicommons.proxies.ToolSpan;
import genaicommons.proxies.Trace;
import genaicommons.proxies.microflows.Microflows;
import com.mendix.systemwideinterfaces.core.UserAction;
import com.mendix.systemwideinterfaces.core.meta.IMetaObject;

public class Tool_ExecuteMicroflow extends UserAction<java.lang.String>
{
	/** @deprecated use Tool.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __Tool;
	private final genaicommons.proxies.Tool Tool;
	/** @deprecated use Request.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __Request;
	private final genaicommons.proxies.Request Request;
	/** @deprecated use ToolCall.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __ToolCall;
	private final genaicommons.proxies.ToolCall ToolCall;
	/** @deprecated use ModelSpan.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __ModelSpan;
	private final genaicommons.proxies.ModelSpan ModelSpan;

	public Tool_ExecuteMicroflow(
		IContext context,
		IMendixObject _tool,
		IMendixObject _request,
		IMendixObject _toolCall,
		IMendixObject _modelSpan
	)
	{
		super(context);
		this.__Tool = _tool;
		this.Tool = _tool == null ? null : genaicommons.proxies.Tool.initialize(getContext(), _tool);
		this.__Request = _request;
		this.Request = _request == null ? null : genaicommons.proxies.Request.initialize(getContext(), _request);
		this.__ToolCall = _toolCall;
		this.ToolCall = _toolCall == null ? null : genaicommons.proxies.ToolCall.initialize(getContext(), _toolCall);
		this.__ModelSpan = _modelSpan;
		this.ModelSpan = _modelSpan == null ? null : genaicommons.proxies.ModelSpan.initialize(getContext(), _modelSpan);
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		try {
			requireNonNull(Tool, "Tool is required.");
			requireNonNull(Tool.getMicroflow(), "Tool has no Microflow.");
			startTime = System.currentTimeMillis();
			
			return callTool();
		
		} catch (Exception e) {
			//makes sure that a toolSpan exists; response/output is set in microflow later
			long executionTime = System.currentTimeMillis() - startTime;
			getCreateToolSpan(executionTime, "");
			throw e;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Tool_ExecuteMicroflow";
	}

	// BEGIN EXTRA CODE
	private static final MxLogger LOGGER = new genaicommons.impl.MxLogger(Tool_ExecuteMicroflow.class);
	
	private long startTime;
	
	/**
	 * If the Tool is of the generalization type, only Tool and Request are added to the microflow
	 * Otherwise the parameters from the microflow are mapped
	 * @throws Exception
	 */
	private String callTool() throws Exception {
		if(Tool.getClass().equals(genaicommons.proxies.Tool.class)) {
			Map<String, Object> parametersAndValues = new java.util.HashMap<>();
			parametersAndValues.put("Tool",  Tool.getMendixObject());
			parametersAndValues.put("Request",  Request.getMendixObject());
			return executeAndLogToolMicroflow(parametersAndValues);
			
		}
		else {
			return executeToolMicroflow();
		}
	}

	private String executeToolMicroflow() throws Exception {
		
		Map<String, Object> parametersAndValues = new java.util.HashMap<>();
		//Iterate over input params
		Map<String, IDataType> parametersAndTypes = Core.getInputParameters(Tool.getMicroflow());
		
		for(Map.Entry<String, IDataType> entry : parametersAndTypes.entrySet()) {
			IDataType value = entry.getValue();
			String key = entry.getKey();
			//find Argument.Value in ArgumentList
			List<Argument> argumentList = ToolCall.getToolCall_Argument();
			String argumentValue = argumentList.stream()
				    .filter(arg -> key.equals(arg.getKey()))
				    .map(Argument::getValue)
				    .findFirst()
				    .orElse(null);
			
			//If there is no argumentValue, it is either a Mendix Object or nothing was passed
			if (argumentValue == null && isMetaObjectSubClass(value,genaicommons.proxies.Tool.getType())){
				parametersAndValues.put(key,  Tool.getMendixObject());
				continue;
				
			} else if (argumentValue == null && isMetaObjectSubClass(value, genaicommons.proxies.Request.getType())){
				parametersAndValues.put(key, Request.getMendixObject());
				continue;
				
			} else if (argumentValue == null) {
				parametersAndValues.put(key, null);
				continue;
			}
						
			// Convert input into type of tool microflow's parameter type and add to list
			if (IDataType.DataTypeEnum.Boolean.equals(value.getType())) {
				parametersAndValues.put(key, Boolean.parseBoolean(argumentValue));
				
			} else if (IDataType.DataTypeEnum.Integer.equals(value.getType()) || IDataType.DataTypeEnum.Long.equals(value.getType()) ) {
					parametersAndValues.put(key, Long.parseLong(argumentValue));
					
			} else if (IDataType.DataTypeEnum.Datetime.equals(value.getType())) {
				Date date = new Date(Long.parseLong(argumentValue) *1000L); //Convert UNIX timestamp to DateTime
				parametersAndValues.put(key, date);
				
			} else if (IDataType.DataTypeEnum.Decimal.equals(value.getType())) {
				parametersAndValues.put(key, Float.parseFloat(argumentValue));
				
			} else if(IDataType.DataTypeEnum.String.equals(value.getType())){
				parametersAndValues.put(key, argumentValue);	
				
			} else if(IDataType.DataTypeEnum.Enumeration.equals(value.getType())){
				parametersAndValues.put(key, argumentValue);	
				
			}
		}		
		return executeAndLogToolMicroflow(parametersAndValues);
	}
	
	/**
	 * Checks if the input object of a parameter (as IDataType) matches the (Sub)class of a given String type (should be passed using the class.getType() method)
	 * @param value
	 * @param type
	 * @return true if the Object matches the Sub(class).
	 */
	private Boolean isMetaObjectSubClass(IDataType value, String type) {
		String objectType = value.getObjectType();
		
		if(objectType == null) {
			return false;
		}
		
		IMetaObject metaObject = Core.getMetaObject(objectType);
		if (metaObject != null) {
			return metaObject.isSubClassOf(type);
		}
	
		return false;		
	}
	
	private String executeAndLogToolMicroflow(Map<String, Object> params) throws CoreException {
		String response;
		String logMessageInfo = "Finished toolcall " + ToolCall.getName() + " with Id " + ToolCall.getToolCallId() + " using microflow " + Tool.getMicroflow() + " with " + getContext();
		String logMessageTrace = logMessageInfo;
		if(params == null || params.isEmpty()) {
			logMessageTrace = logMessageTrace + "\nwithout input parameters ";
			response = Core.microflowCall(Tool.getMicroflow()).execute(getContext());
		} else {
			logMessageTrace = logMessageTrace +  "\n\nInput parameter(s):";
			logMessageTrace = addLogTracesForArguments(logMessageTrace);
			logMessageTrace = logMessageTrace + params.toString();
			response = Core.microflowCall(Tool.getMicroflow()).withParams(params).execute(getContext());
		}
		
		long executionTime = System.currentTimeMillis() - startTime;
		String duration = "\n\nDuration:\n" + executionTime + "ms";
		LOGGER.info(logMessageInfo + duration);
		LOGGER.trace(logMessageTrace+ "\n\nReturn value:\n" + response + duration);
		
		getCreateToolSpan(executionTime, response);
		return response;
	}
	
	/**
	 * If there are ArgumentInput objects associated to a Tool, they are likely not part of the input parameters and need to be added individually
	 */
	private String addLogTracesForArguments(String logMessageTrace) throws CoreException{
		List<ArgumentInput> args = Tool.getTool_ArgumentInput();
		
		if(args != null && !args.isEmpty()) {
			logMessageTrace += getArgumentsString();
		}
		return logMessageTrace;
	}
	
	/**
	 * Gets a string of input arguments (passed by the model only)
	 */
	private String getArgumentsString() throws CoreException {
		List<Argument> argumentList = ToolCall.getToolCall_Argument();
		String argumentString = "\n\n" + "{";
		for (int i = 0; i < argumentList.size(); i++) {
		    Argument arg = argumentList.get(i);
		    argumentString += arg.getKey() + "=" + arg.getValue();
		    if (i < argumentList.size() - 1) {
		        argumentString += ", ";
		    }
		}
		argumentString += "}";
		return argumentString;
	}
	
	/**
	 * Gets an existing toolSpan from the trace via the toolCallId or creates a new one based on the specialization
	 * @throws CoreException
	 */
	private ToolSpan getCreateToolSpan(long executionTime, String response) throws CoreException {
		//If there is no trace for the request, then traceability was not enabled
		Trace trace = Request.getRequest_Trace();
		if(trace == null) {
			return null;
		}
		
		ToolSpan toolSpan = Microflows.trace_GetToolSpan_ByToolCallId(getContext(), trace, ToolCall.getToolCallId()); 
		if(toolSpan != null) {
			return toolSpan;
		}
		
		if (Tool.getMCPServerName()!= null) {
			MCPSpan mxMCPSpan = new MCPSpan(getContext());
			setToolSpanAttributes(mxMCPSpan, trace, executionTime, response);
			mxMCPSpan.setServerName(Tool.getMCPServerName());
			return mxMCPSpan;
		}
		else if(Tool.getClass().equals(genaicommons.proxies.KnowledgeBaseRetrieval.class)){
			genaicommons.proxies.KnowledgeBaseRetrieval mxKnowledgeBaseRetrieval = (genaicommons.proxies.KnowledgeBaseRetrieval)Tool;
			KnowledgeBaseSpan knowledgeBaseSpan = new KnowledgeBaseSpan(getContext());
			setToolSpanAttributes(knowledgeBaseSpan, trace, executionTime, response);
			knowledgeBaseSpan.setMinimumSimilarity(mxKnowledgeBaseRetrieval.getMinimumSimilarity());
			knowledgeBaseSpan.setMaxNumberOfResults(mxKnowledgeBaseRetrieval.getMaxNumberOfResults());
			knowledgeBaseSpan.setArchitecture(mxKnowledgeBaseRetrieval.getKnowledgeBaseRetrieval_DeployedKnowledgeBase().getArchitecture());
			knowledgeBaseSpan.setKBDisplayName(mxKnowledgeBaseRetrieval.getKnowledgeBaseRetrieval_DeployedKnowledgeBase().getDisplayName());
			return knowledgeBaseSpan;
			
		} else {
			ToolSpan newToolSpan = new ToolSpan(getContext());
			setToolSpanAttributes(newToolSpan, trace, executionTime, response);
			return newToolSpan;
		}	
	}
	
	/**
	 * Sets all attributes of the tool span
	 */
	private void setToolSpanAttributes(ToolSpan toolSpan, Trace trace, long executionTime, String response) throws CoreException {
		toolSpan.setSpanId(UUID.randomUUID().toString());
		toolSpan.setSpan_Trace(trace);
		toolSpan.setStartTime(new Date(startTime));
		toolSpan.set_ToolCallId(ToolCall.getToolCallId());
		toolSpan.setToolName(Tool.getName());
		toolSpan.setToolDescription(Tool.getDescription());
		toolSpan.setEndTime(new Date(System.currentTimeMillis()));			
		toolSpan.setInput(getArgumentsString());
		toolSpan.setDurationMilliseconds((int) executionTime);
		toolSpan.setOutput(response);
		toolSpan.setSpan_SubSpan(ModelSpan);
	}
	
	
	// END EXTRA CODE
}
