// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {string} targetSelector - CSS selector of target element
 * @param {string} className - CSS Class to add to the target element.
 * @param {boolean} targetMultiple - If set to true, will use querySelectorAll to match multiple targets. Otherwise, only finds the first match.
 * @returns {Promise.<void>}
 */
export async function AddClass(targetSelector, className, targetMultiple) {
	// BEGIN USER CODE
	throw new Error("JavaScript action was not implemented");
	// END USER CODE
}
